; Copyright (c) 2025 ivfzhou
; csms is licensed under Mulan PSL v2.
; You can use this software according to the terms and conditions of the Mulan PSL v2.
; You may obtain a copy of Mulan PSL v2 at:
;          http://license.coscl.org.cn/MulanPSL2
; THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
; EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
; MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
; See the Mulan PSL v2 for more details.

# 配置含义参见：comm/cfg/api/api.go#Configurer

environment = local
timeZone = Asia/Shanghai
gatewayHost = 127.0.0.1
gatewayInternalServerPort = 8000
tlsInsecureSkipVerify = true

[log]
name = sign_server.log
fileMaximumSizeByMegabytes = 20
fileMaximumBackups = 50
fileMaximumAgeByDays = 90
level = info
slowSqlThreshold = 100ms
consoleColorful = true

# 先更新服务，再更新配置。否则请重新保存下配置。
[rabbitmq]
username = ivfzhou
password = 123456
host = 127.0.0.1
port = 5672
virtualHost = csms
prefetchCount = 64
windowsOVSigningJobQueue = queue_windows_ov
windowsEVSigningJobQueuePrefix = queue_windows_ev_
androidSigningJobQueue = queue_android
appleSigningJobQueue = queue_apple
