; Copyright (c) 2025 ivfzhou
; csms is licensed under Mulan PSL v2.
; You can use this software according to the terms and conditions of the Mulan PSL v2.
; You may obtain a copy of Mulan PSL v2 at:
;          http://license.coscl.org.cn/MulanPSL2
; THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
; EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
; MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
; See the Mulan PSL v2 for more details.

# 配置含义参见：comm/cfg/api/api.go#Configurer

environment = local
timeZone = Asia/Shanghai
gatewayHost = 192.168.137.1
gatewayInternalServerPort = 8000
tlsInsecureSkipVerify = true

# 端口变更不自动更新服务。
[hlkManagerHost]
port = 8093

[hlkManagerTest]

[hlkManagerController]

# 虚拟机上报给宿主机的日志，宿主机管理该日志时，不会随配置更新而变更。
[log]
name = hlk_manager.log
fileMaximumSizeByMegabytes = 20
fileMaximumBackups = 50
fileMaximumAgeByDays = 90
level = info
consoleColorful = false
reportPath = /internal/host/reportLog
