base:
  # 应用 ID，必填。
  appId: 3f3e426d48fc480e9a543d39bc1c2411
  # 请求凭证 ID，必填。
  accountId: windows_api_account
  # 请求凭证密钥，必填。
  secret: p02YboFVdQ"]^1OF\N5iX(;,'D?wv}-wg:'q5RY|w>`q!Ns#34^J"'-6].Id}xL2}c2mz9M^PWi&8AkV8X'4,#DD}rcxM$09q:`s3!r=R^.e5z!m8AdBYtv]l>/y6I@k
  # 待签名文件，必填。
  inFile: /home/ivfzhou/文档/Win11_25H2_China_GGK_Chinese_Simplified_x64_v2.iso
  # 签名结果文件，必填。
  outFile: /home/ivfzhou/文档/Win11_25H2_China_GGK_Chinese_Simplified_x64_v2.iso.1
  # 任务类型，必填。windows、whql、android、apple。
  jobType: windows

signConfig:
  # Windows 签名。
  windows:
    # 任务类型，必填。pe、attestation、peAndAttestation。
    type: pe
    # 证书 ID，必填。
    certificateId: 933b9d84bbcb4a0596a454a903324446
  # WHQL 认证。
  whql:
    # 任务类型，必填。hlk、testAndHlk。
    type: testAndHlk
    # 测试系统，必填。
    testSystem: Windows 10 22H2_64
    # 服务进程名。
    serviceName: KMDFDriver
    # 测试标的。
    testTarget: KMDFDriver.sys
    # 测试配置文件路径。配置文件中，0 为默认值，1 为 关闭，2 为开启。
    testConfigFilePath: ./default_hlk_test_config.json
  # 安卓签名。
  android:
    # 类型，必填。apk、aab、patch。
    type: apk
    # 签名方案，必填。
    signatureSchema:
      - 1
      - 2
      - 3
      - 4
    # 证书 ID，必填.
    certificateId: 1c5cf472a8bb4ef689e968fc80e8f8ae
    # Android API 版本。
    minimumSDKVersion: 19
  # Apple 签名配置。
  apple:
    # 描述文件 ID，必填。
    provisionId: 6e80885e077647c7a84b0ab72ba30ea8
