base:
  # 应用 ID，必填。
  appId: 16d87e3944a0435db55ac67cbf809d9f
  # 请求凭证 ID，必填。
  accountId: windows_api_account
  # 请求凭证密钥，必填。
  secret: Pb?2Y>OUNWfftJjsOjq(.kRb\S(tcS_QfS.>22=+[>L;n#{_c85:gNZ~<&W0R"QX3Lu3`FGcyMDsmz@SUv;ekbv+</*:%E>B6]\$i3TUG5!Vd2AR,Y[D_Im;v5QdevhP
  # 待签名文件，必填。
  inFile: /home/ivfzhou/下载/test_file.exe
  # 签名结果文件，必填。
  outFile: /home/ivfzhou/下载/test_file.exe
  # 任务类型，必填。windows、whql、android、apple。
  jobType: windows

signConfig:
  # Windows 签名。
  windows:
    # 任务类型，必填。pe、attestation、peAndAttestation。
    type: pe
    # 证书 ID，必填。
    certificateId: 4603348c70934d1bbe3689449284791a
  # WHQL 认证。
  whql:
    # 任务类型，必填。hlk、testAndHlk。
    type: testAndHlk
    # 测试系统，必填。
    testSystem: Windows 10 22H2_64
    # 服务进程名。
    serviceName: KMDFDriver
    # 测试标的。
    testTarget: KMDFDriver.sys
    # 测试配置文件路径。配置文件中，0 为默认值，1 为 关闭，2 为开启。
    testConfigFilePath: ./auto_signer/default_hlk_test_config.json
  # 安卓签名。
  android:
    # 类型，必填。apk、aab、patch。
    type: apk
    # 签名方案，必填。
    signatureSchema:
      - 1
      - 2
      - 3
      - 4
    # 证书 ID，必填.
    certificateId: 1c5cf472a8bb4ef689e968fc80e8f8ae
    # Android API 版本。
    minimumSDKVersion: 19
  # Apple 签名配置。
  apple:
    # 描述文件 ID，必填。
    provisionId: 2430461a19504dbebe7d473edc676573
