// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                              db,
		APIAccount:                      newAPIAccount(db, opts...),
		APIAuthorization:                newAPIAuthorization(db, opts...),
		AesKey:                          newAesKey(db, opts...),
		AndroidCertificate:              newAndroidCertificate(db, opts...),
		AndroidOrganization:             newAndroidOrganization(db, opts...),
		AndroidSigningJob:               newAndroidSigningJob(db, opts...),
		App:                             newApp(db, opts...),
		AppleBundleID:                   newAppleBundleID(db, opts...),
		AppleCertificate:                newAppleCertificate(db, opts...),
		AppleDevice:                     newAppleDevice(db, opts...),
		AppleProfile:                    newAppleProfile(db, opts...),
		AppleSigningJob:                 newAppleSigningJob(db, opts...),
		Event:                           newEvent(db, opts...),
		File:                            newFile(db, opts...),
		Notice:                          newNotice(db, opts...),
		Todo:                            newTodo(db, opts...),
		User:                            newUser(db, opts...),
		UserRole:                        newUserRole(db, opts...),
		WhqlJob:                         newWhqlJob(db, opts...),
		WindowsCertificate:              newWindowsCertificate(db, opts...),
		WindowsCertificateAuthorization: newWindowsCertificateAuthorization(db, opts...),
		WindowsSigningJob:               newWindowsSigningJob(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	APIAccount                      aPIAccount
	APIAuthorization                aPIAuthorization
	AesKey                          aesKey
	AndroidCertificate              androidCertificate
	AndroidOrganization             androidOrganization
	AndroidSigningJob               androidSigningJob
	App                             app
	AppleBundleID                   appleBundleID
	AppleCertificate                appleCertificate
	AppleDevice                     appleDevice
	AppleProfile                    appleProfile
	AppleSigningJob                 appleSigningJob
	Event                           event
	File                            file
	Notice                          notice
	Todo                            todo
	User                            user
	UserRole                        userRole
	WhqlJob                         whqlJob
	WindowsCertificate              windowsCertificate
	WindowsCertificateAuthorization windowsCertificateAuthorization
	WindowsSigningJob               windowsSigningJob
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                              db,
		APIAccount:                      q.APIAccount.clone(db),
		APIAuthorization:                q.APIAuthorization.clone(db),
		AesKey:                          q.AesKey.clone(db),
		AndroidCertificate:              q.AndroidCertificate.clone(db),
		AndroidOrganization:             q.AndroidOrganization.clone(db),
		AndroidSigningJob:               q.AndroidSigningJob.clone(db),
		App:                             q.App.clone(db),
		AppleBundleID:                   q.AppleBundleID.clone(db),
		AppleCertificate:                q.AppleCertificate.clone(db),
		AppleDevice:                     q.AppleDevice.clone(db),
		AppleProfile:                    q.AppleProfile.clone(db),
		AppleSigningJob:                 q.AppleSigningJob.clone(db),
		Event:                           q.Event.clone(db),
		File:                            q.File.clone(db),
		Notice:                          q.Notice.clone(db),
		Todo:                            q.Todo.clone(db),
		User:                            q.User.clone(db),
		UserRole:                        q.UserRole.clone(db),
		WhqlJob:                         q.WhqlJob.clone(db),
		WindowsCertificate:              q.WindowsCertificate.clone(db),
		WindowsCertificateAuthorization: q.WindowsCertificateAuthorization.clone(db),
		WindowsSigningJob:               q.WindowsSigningJob.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                              db,
		APIAccount:                      q.APIAccount.replaceDB(db),
		APIAuthorization:                q.APIAuthorization.replaceDB(db),
		AesKey:                          q.AesKey.replaceDB(db),
		AndroidCertificate:              q.AndroidCertificate.replaceDB(db),
		AndroidOrganization:             q.AndroidOrganization.replaceDB(db),
		AndroidSigningJob:               q.AndroidSigningJob.replaceDB(db),
		App:                             q.App.replaceDB(db),
		AppleBundleID:                   q.AppleBundleID.replaceDB(db),
		AppleCertificate:                q.AppleCertificate.replaceDB(db),
		AppleDevice:                     q.AppleDevice.replaceDB(db),
		AppleProfile:                    q.AppleProfile.replaceDB(db),
		AppleSigningJob:                 q.AppleSigningJob.replaceDB(db),
		Event:                           q.Event.replaceDB(db),
		File:                            q.File.replaceDB(db),
		Notice:                          q.Notice.replaceDB(db),
		Todo:                            q.Todo.replaceDB(db),
		User:                            q.User.replaceDB(db),
		UserRole:                        q.UserRole.replaceDB(db),
		WhqlJob:                         q.WhqlJob.replaceDB(db),
		WindowsCertificate:              q.WindowsCertificate.replaceDB(db),
		WindowsCertificateAuthorization: q.WindowsCertificateAuthorization.replaceDB(db),
		WindowsSigningJob:               q.WindowsSigningJob.replaceDB(db),
	}
}

type queryCtx struct {
	APIAccount                      IAPIAccountDo
	APIAuthorization                IAPIAuthorizationDo
	AesKey                          IAesKeyDo
	AndroidCertificate              IAndroidCertificateDo
	AndroidOrganization             IAndroidOrganizationDo
	AndroidSigningJob               IAndroidSigningJobDo
	App                             IAppDo
	AppleBundleID                   IAppleBundleIDDo
	AppleCertificate                IAppleCertificateDo
	AppleDevice                     IAppleDeviceDo
	AppleProfile                    IAppleProfileDo
	AppleSigningJob                 IAppleSigningJobDo
	Event                           IEventDo
	File                            IFileDo
	Notice                          INoticeDo
	Todo                            ITodoDo
	User                            IUserDo
	UserRole                        IUserRoleDo
	WhqlJob                         IWhqlJobDo
	WindowsCertificate              IWindowsCertificateDo
	WindowsCertificateAuthorization IWindowsCertificateAuthorizationDo
	WindowsSigningJob               IWindowsSigningJobDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		APIAccount:                      q.APIAccount.WithContext(ctx),
		APIAuthorization:                q.APIAuthorization.WithContext(ctx),
		AesKey:                          q.AesKey.WithContext(ctx),
		AndroidCertificate:              q.AndroidCertificate.WithContext(ctx),
		AndroidOrganization:             q.AndroidOrganization.WithContext(ctx),
		AndroidSigningJob:               q.AndroidSigningJob.WithContext(ctx),
		App:                             q.App.WithContext(ctx),
		AppleBundleID:                   q.AppleBundleID.WithContext(ctx),
		AppleCertificate:                q.AppleCertificate.WithContext(ctx),
		AppleDevice:                     q.AppleDevice.WithContext(ctx),
		AppleProfile:                    q.AppleProfile.WithContext(ctx),
		AppleSigningJob:                 q.AppleSigningJob.WithContext(ctx),
		Event:                           q.Event.WithContext(ctx),
		File:                            q.File.WithContext(ctx),
		Notice:                          q.Notice.WithContext(ctx),
		Todo:                            q.Todo.WithContext(ctx),
		User:                            q.User.WithContext(ctx),
		UserRole:                        q.UserRole.WithContext(ctx),
		WhqlJob:                         q.WhqlJob.WithContext(ctx),
		WindowsCertificate:              q.WindowsCertificate.WithContext(ctx),
		WindowsCertificateAuthorization: q.WindowsCertificateAuthorization.WithContext(ctx),
		WindowsSigningJob:               q.WindowsSigningJob.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
