// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/ivfzhou/csms/comm/model"
)

func newAesKey(db *gorm.DB, opts ...gen.DOOption) aesKey {
	_aesKey := aesKey{}

	_aesKey.aesKeyDo.UseDB(db, opts...)
	_aesKey.aesKeyDo.UseModel(&model.AesKey{})

	tableName := _aesKey.aesKeyDo.TableName()
	_aesKey.ALL = field.NewAsterisk(tableName)
	_aesKey.ID = field.NewInt(tableName, "id")
	_aesKey.Secret = field.NewBytes(tableName, "secret")
	_aesKey.CreatedTime = field.NewTime(tableName, "created_time")

	_aesKey.fillFieldMap()

	return _aesKey
}

// aesKey 证书加密密钥表
type aesKey struct {
	aesKeyDo

	ALL         field.Asterisk
	ID          field.Int   // 自增主码
	Secret      field.Bytes // 密钥
	CreatedTime field.Time  // 创建时间

	fieldMap map[string]field.Expr
}

func (a aesKey) Table(newTableName string) *aesKey {
	a.aesKeyDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a aesKey) As(alias string) *aesKey {
	a.aesKeyDo.DO = *(a.aesKeyDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *aesKey) updateTableName(table string) *aesKey {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt(table, "id")
	a.Secret = field.NewBytes(table, "secret")
	a.CreatedTime = field.NewTime(table, "created_time")

	a.fillFieldMap()

	return a
}

func (a *aesKey) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *aesKey) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 3)
	a.fieldMap["id"] = a.ID
	a.fieldMap["secret"] = a.Secret
	a.fieldMap["created_time"] = a.CreatedTime
}

func (a aesKey) clone(db *gorm.DB) aesKey {
	a.aesKeyDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a aesKey) replaceDB(db *gorm.DB) aesKey {
	a.aesKeyDo.ReplaceDB(db)
	return a
}

type aesKeyDo struct{ gen.DO }

type IAesKeyDo interface {
	gen.SubQuery
	Debug() IAesKeyDo
	WithContext(ctx context.Context) IAesKeyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAesKeyDo
	WriteDB() IAesKeyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAesKeyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAesKeyDo
	Not(conds ...gen.Condition) IAesKeyDo
	Or(conds ...gen.Condition) IAesKeyDo
	Select(conds ...field.Expr) IAesKeyDo
	Where(conds ...gen.Condition) IAesKeyDo
	Order(conds ...field.Expr) IAesKeyDo
	Distinct(cols ...field.Expr) IAesKeyDo
	Omit(cols ...field.Expr) IAesKeyDo
	Join(table schema.Tabler, on ...field.Expr) IAesKeyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAesKeyDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAesKeyDo
	Group(cols ...field.Expr) IAesKeyDo
	Having(conds ...gen.Condition) IAesKeyDo
	Limit(limit int) IAesKeyDo
	Offset(offset int) IAesKeyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAesKeyDo
	Unscoped() IAesKeyDo
	Create(values ...*model.AesKey) error
	CreateInBatches(values []*model.AesKey, batchSize int) error
	Save(values ...*model.AesKey) error
	First() (*model.AesKey, error)
	Take() (*model.AesKey, error)
	Last() (*model.AesKey, error)
	Find() ([]*model.AesKey, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AesKey, err error)
	FindInBatches(result *[]*model.AesKey, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AesKey) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAesKeyDo
	Assign(attrs ...field.AssignExpr) IAesKeyDo
	Joins(fields ...field.RelationField) IAesKeyDo
	Preload(fields ...field.RelationField) IAesKeyDo
	FirstOrInit() (*model.AesKey, error)
	FirstOrCreate() (*model.AesKey, error)
	FindByPage(offset int, limit int) (result []*model.AesKey, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAesKeyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a aesKeyDo) Debug() IAesKeyDo {
	return a.withDO(a.DO.Debug())
}

func (a aesKeyDo) WithContext(ctx context.Context) IAesKeyDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a aesKeyDo) ReadDB() IAesKeyDo {
	return a.Clauses(dbresolver.Read)
}

func (a aesKeyDo) WriteDB() IAesKeyDo {
	return a.Clauses(dbresolver.Write)
}

func (a aesKeyDo) Session(config *gorm.Session) IAesKeyDo {
	return a.withDO(a.DO.Session(config))
}

func (a aesKeyDo) Clauses(conds ...clause.Expression) IAesKeyDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a aesKeyDo) Returning(value interface{}, columns ...string) IAesKeyDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a aesKeyDo) Not(conds ...gen.Condition) IAesKeyDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a aesKeyDo) Or(conds ...gen.Condition) IAesKeyDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a aesKeyDo) Select(conds ...field.Expr) IAesKeyDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a aesKeyDo) Where(conds ...gen.Condition) IAesKeyDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a aesKeyDo) Order(conds ...field.Expr) IAesKeyDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a aesKeyDo) Distinct(cols ...field.Expr) IAesKeyDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a aesKeyDo) Omit(cols ...field.Expr) IAesKeyDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a aesKeyDo) Join(table schema.Tabler, on ...field.Expr) IAesKeyDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a aesKeyDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAesKeyDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a aesKeyDo) RightJoin(table schema.Tabler, on ...field.Expr) IAesKeyDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a aesKeyDo) Group(cols ...field.Expr) IAesKeyDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a aesKeyDo) Having(conds ...gen.Condition) IAesKeyDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a aesKeyDo) Limit(limit int) IAesKeyDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a aesKeyDo) Offset(offset int) IAesKeyDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a aesKeyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAesKeyDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a aesKeyDo) Unscoped() IAesKeyDo {
	return a.withDO(a.DO.Unscoped())
}

func (a aesKeyDo) Create(values ...*model.AesKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a aesKeyDo) CreateInBatches(values []*model.AesKey, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a aesKeyDo) Save(values ...*model.AesKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a aesKeyDo) First() (*model.AesKey, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AesKey), nil
	}
}

func (a aesKeyDo) Take() (*model.AesKey, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AesKey), nil
	}
}

func (a aesKeyDo) Last() (*model.AesKey, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AesKey), nil
	}
}

func (a aesKeyDo) Find() ([]*model.AesKey, error) {
	result, err := a.DO.Find()
	return result.([]*model.AesKey), err
}

func (a aesKeyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AesKey, err error) {
	buf := make([]*model.AesKey, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a aesKeyDo) FindInBatches(result *[]*model.AesKey, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a aesKeyDo) Attrs(attrs ...field.AssignExpr) IAesKeyDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a aesKeyDo) Assign(attrs ...field.AssignExpr) IAesKeyDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a aesKeyDo) Joins(fields ...field.RelationField) IAesKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a aesKeyDo) Preload(fields ...field.RelationField) IAesKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a aesKeyDo) FirstOrInit() (*model.AesKey, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AesKey), nil
	}
}

func (a aesKeyDo) FirstOrCreate() (*model.AesKey, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AesKey), nil
	}
}

func (a aesKeyDo) FindByPage(offset int, limit int) (result []*model.AesKey, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a aesKeyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a aesKeyDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a aesKeyDo) Delete(models ...*model.AesKey) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *aesKeyDo) withDO(do gen.Dao) *aesKeyDo {
	a.DO = *do.(*gen.DO)
	return a
}
