// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/ivfzhou/csms/comm/model"
)

func newAndroidOrganization(db *gorm.DB, opts ...gen.DOOption) androidOrganization {
	_androidOrganization := androidOrganization{}

	_androidOrganization.androidOrganizationDo.UseDB(db, opts...)
	_androidOrganization.androidOrganizationDo.UseModel(&model.AndroidOrganization{})

	tableName := _androidOrganization.androidOrganizationDo.TableName()
	_androidOrganization.ALL = field.NewAsterisk(tableName)
	_androidOrganization.ID = field.NewInt(tableName, "id")
	_androidOrganization.Name = field.NewString(tableName, "name")
	_androidOrganization.UserID = field.NewInt(tableName, "user_id")
	_androidOrganization.Owner = field.NewString(tableName, "owner")
	_androidOrganization.CreatedTime = field.NewTime(tableName, "created_time")

	_androidOrganization.fillFieldMap()

	return _androidOrganization
}

// androidOrganization 安卓证书主体表
type androidOrganization struct {
	androidOrganizationDo

	ALL         field.Asterisk
	ID          field.Int    // 自增主码
	Name        field.String // 通用名 CN
	UserID      field.Int    // 添加人 ID
	Owner       field.String // 所有者，用于 keytool 中的 dname 参数值
	CreatedTime field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (a androidOrganization) Table(newTableName string) *androidOrganization {
	a.androidOrganizationDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a androidOrganization) As(alias string) *androidOrganization {
	a.androidOrganizationDo.DO = *(a.androidOrganizationDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *androidOrganization) updateTableName(table string) *androidOrganization {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt(table, "id")
	a.Name = field.NewString(table, "name")
	a.UserID = field.NewInt(table, "user_id")
	a.Owner = field.NewString(table, "owner")
	a.CreatedTime = field.NewTime(table, "created_time")

	a.fillFieldMap()

	return a
}

func (a *androidOrganization) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *androidOrganization) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 5)
	a.fieldMap["id"] = a.ID
	a.fieldMap["name"] = a.Name
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["owner"] = a.Owner
	a.fieldMap["created_time"] = a.CreatedTime
}

func (a androidOrganization) clone(db *gorm.DB) androidOrganization {
	a.androidOrganizationDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a androidOrganization) replaceDB(db *gorm.DB) androidOrganization {
	a.androidOrganizationDo.ReplaceDB(db)
	return a
}

type androidOrganizationDo struct{ gen.DO }

type IAndroidOrganizationDo interface {
	gen.SubQuery
	Debug() IAndroidOrganizationDo
	WithContext(ctx context.Context) IAndroidOrganizationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAndroidOrganizationDo
	WriteDB() IAndroidOrganizationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAndroidOrganizationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAndroidOrganizationDo
	Not(conds ...gen.Condition) IAndroidOrganizationDo
	Or(conds ...gen.Condition) IAndroidOrganizationDo
	Select(conds ...field.Expr) IAndroidOrganizationDo
	Where(conds ...gen.Condition) IAndroidOrganizationDo
	Order(conds ...field.Expr) IAndroidOrganizationDo
	Distinct(cols ...field.Expr) IAndroidOrganizationDo
	Omit(cols ...field.Expr) IAndroidOrganizationDo
	Join(table schema.Tabler, on ...field.Expr) IAndroidOrganizationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAndroidOrganizationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAndroidOrganizationDo
	Group(cols ...field.Expr) IAndroidOrganizationDo
	Having(conds ...gen.Condition) IAndroidOrganizationDo
	Limit(limit int) IAndroidOrganizationDo
	Offset(offset int) IAndroidOrganizationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAndroidOrganizationDo
	Unscoped() IAndroidOrganizationDo
	Create(values ...*model.AndroidOrganization) error
	CreateInBatches(values []*model.AndroidOrganization, batchSize int) error
	Save(values ...*model.AndroidOrganization) error
	First() (*model.AndroidOrganization, error)
	Take() (*model.AndroidOrganization, error)
	Last() (*model.AndroidOrganization, error)
	Find() ([]*model.AndroidOrganization, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AndroidOrganization, err error)
	FindInBatches(result *[]*model.AndroidOrganization, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AndroidOrganization) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAndroidOrganizationDo
	Assign(attrs ...field.AssignExpr) IAndroidOrganizationDo
	Joins(fields ...field.RelationField) IAndroidOrganizationDo
	Preload(fields ...field.RelationField) IAndroidOrganizationDo
	FirstOrInit() (*model.AndroidOrganization, error)
	FirstOrCreate() (*model.AndroidOrganization, error)
	FindByPage(offset int, limit int) (result []*model.AndroidOrganization, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAndroidOrganizationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a androidOrganizationDo) Debug() IAndroidOrganizationDo {
	return a.withDO(a.DO.Debug())
}

func (a androidOrganizationDo) WithContext(ctx context.Context) IAndroidOrganizationDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a androidOrganizationDo) ReadDB() IAndroidOrganizationDo {
	return a.Clauses(dbresolver.Read)
}

func (a androidOrganizationDo) WriteDB() IAndroidOrganizationDo {
	return a.Clauses(dbresolver.Write)
}

func (a androidOrganizationDo) Session(config *gorm.Session) IAndroidOrganizationDo {
	return a.withDO(a.DO.Session(config))
}

func (a androidOrganizationDo) Clauses(conds ...clause.Expression) IAndroidOrganizationDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a androidOrganizationDo) Returning(value interface{}, columns ...string) IAndroidOrganizationDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a androidOrganizationDo) Not(conds ...gen.Condition) IAndroidOrganizationDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a androidOrganizationDo) Or(conds ...gen.Condition) IAndroidOrganizationDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a androidOrganizationDo) Select(conds ...field.Expr) IAndroidOrganizationDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a androidOrganizationDo) Where(conds ...gen.Condition) IAndroidOrganizationDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a androidOrganizationDo) Order(conds ...field.Expr) IAndroidOrganizationDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a androidOrganizationDo) Distinct(cols ...field.Expr) IAndroidOrganizationDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a androidOrganizationDo) Omit(cols ...field.Expr) IAndroidOrganizationDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a androidOrganizationDo) Join(table schema.Tabler, on ...field.Expr) IAndroidOrganizationDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a androidOrganizationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAndroidOrganizationDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a androidOrganizationDo) RightJoin(table schema.Tabler, on ...field.Expr) IAndroidOrganizationDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a androidOrganizationDo) Group(cols ...field.Expr) IAndroidOrganizationDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a androidOrganizationDo) Having(conds ...gen.Condition) IAndroidOrganizationDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a androidOrganizationDo) Limit(limit int) IAndroidOrganizationDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a androidOrganizationDo) Offset(offset int) IAndroidOrganizationDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a androidOrganizationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAndroidOrganizationDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a androidOrganizationDo) Unscoped() IAndroidOrganizationDo {
	return a.withDO(a.DO.Unscoped())
}

func (a androidOrganizationDo) Create(values ...*model.AndroidOrganization) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a androidOrganizationDo) CreateInBatches(values []*model.AndroidOrganization, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a androidOrganizationDo) Save(values ...*model.AndroidOrganization) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a androidOrganizationDo) First() (*model.AndroidOrganization, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AndroidOrganization), nil
	}
}

func (a androidOrganizationDo) Take() (*model.AndroidOrganization, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AndroidOrganization), nil
	}
}

func (a androidOrganizationDo) Last() (*model.AndroidOrganization, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AndroidOrganization), nil
	}
}

func (a androidOrganizationDo) Find() ([]*model.AndroidOrganization, error) {
	result, err := a.DO.Find()
	return result.([]*model.AndroidOrganization), err
}

func (a androidOrganizationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AndroidOrganization, err error) {
	buf := make([]*model.AndroidOrganization, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a androidOrganizationDo) FindInBatches(result *[]*model.AndroidOrganization, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a androidOrganizationDo) Attrs(attrs ...field.AssignExpr) IAndroidOrganizationDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a androidOrganizationDo) Assign(attrs ...field.AssignExpr) IAndroidOrganizationDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a androidOrganizationDo) Joins(fields ...field.RelationField) IAndroidOrganizationDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a androidOrganizationDo) Preload(fields ...field.RelationField) IAndroidOrganizationDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a androidOrganizationDo) FirstOrInit() (*model.AndroidOrganization, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AndroidOrganization), nil
	}
}

func (a androidOrganizationDo) FirstOrCreate() (*model.AndroidOrganization, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AndroidOrganization), nil
	}
}

func (a androidOrganizationDo) FindByPage(offset int, limit int) (result []*model.AndroidOrganization, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a androidOrganizationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a androidOrganizationDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a androidOrganizationDo) Delete(models ...*model.AndroidOrganization) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *androidOrganizationDo) withDO(do gen.Dao) *androidOrganizationDo {
	a.DO = *do.(*gen.DO)
	return a
}
