// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/ivfzhou/csms/comm/model"
)

func newAndroidCertificate(db *gorm.DB, opts ...gen.DOOption) androidCertificate {
	_androidCertificate := androidCertificate{}

	_androidCertificate.androidCertificateDo.UseDB(db, opts...)
	_androidCertificate.androidCertificateDo.UseModel(&model.AndroidCertificate{})

	tableName := _androidCertificate.androidCertificateDo.TableName()
	_androidCertificate.ALL = field.NewAsterisk(tableName)
	_androidCertificate.ID = field.NewInt(tableName, "id")
	_androidCertificate.CertificateID = field.NewString(tableName, "certificate_id")
	_androidCertificate.AppID = field.NewInt(tableName, "app_id")
	_androidCertificate.UserID = field.NewInt(tableName, "user_id")
	_androidCertificate.Alias_ = field.NewString(tableName, "alias")
	_androidCertificate.Category = field.NewInt(tableName, "category")
	_androidCertificate.Publisher = field.NewString(tableName, "publisher")
	_androidCertificate.Owner = field.NewString(tableName, "owner")
	_androidCertificate.SignatureAlgorithm = field.NewString(tableName, "signature_algorithm")
	_androidCertificate.PublicKeyAlgorithm = field.NewString(tableName, "public_key_algorithm")
	_androidCertificate.Version = field.NewString(tableName, "version")
	_androidCertificate.SerialNumber = field.NewString(tableName, "serial_number")
	_androidCertificate.StoreProvider = field.NewString(tableName, "store_provider")
	_androidCertificate.StoreType = field.NewString(tableName, "store_type")
	_androidCertificate.CreationDate = field.NewTime(tableName, "creation_date")
	_androidCertificate.Sha1 = field.NewString(tableName, "sha1")
	_androidCertificate.Sha256 = field.NewString(tableName, "sha256")
	_androidCertificate.Storepass = field.NewString(tableName, "storepass")
	_androidCertificate.Keypass = field.NewString(tableName, "keypass")
	_androidCertificate.NotBefore = field.NewTime(tableName, "not_before")
	_androidCertificate.NotAfter = field.NewTime(tableName, "not_after")
	_androidCertificate.AesKeyID = field.NewInt(tableName, "aes_key_id")
	_androidCertificate.Content = field.NewBytes(tableName, "content")
	_androidCertificate.CreatedTime = field.NewTime(tableName, "created_time")
	_androidCertificate.DeletedTime = field.NewTime(tableName, "deleted_time")

	_androidCertificate.fillFieldMap()

	return _androidCertificate
}

// androidCertificate 安卓证书信息表
type androidCertificate struct {
	androidCertificateDo

	ALL                field.Asterisk
	ID                 field.Int    // 自增主码
	CertificateID      field.String // 唯一标识
	AppID              field.Int    // 所属应用 ID
	UserID             field.Int    // 创建人 ID
	Alias_             field.String // 别名
	Category           field.Int    // 类型，1=调试、2=发布
	Publisher          field.String // 颁发者
	Owner              field.String // 所有者
	SignatureAlgorithm field.String // 签名算法
	PublicKeyAlgorithm field.String // 公钥密码算法
	Version            field.String // 版本号
	SerialNumber       field.String // 序列号
	StoreProvider      field.String // 证书提供方
	StoreType          field.String // 证书格式类型
	CreationDate       field.Time   // 证书创建时间
	Sha1               field.String // 证书 SHA1 摘要值
	Sha256             field.String // 证书 SHA256 摘要值
	Storepass          field.String // 密钥库解密密码
	Keypass            field.String // 私钥解密密码
	NotBefore          field.Time   // 生效时间
	NotAfter           field.Time   // 失效时间
	AesKeyID           field.Int    // 证书加密密钥 ID
	Content            field.Bytes  // 加密了的密钥库
	CreatedTime        field.Time   // 创建时间
	DeletedTime        field.Time   // 删除时间

	fieldMap map[string]field.Expr
}

func (a androidCertificate) Table(newTableName string) *androidCertificate {
	a.androidCertificateDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a androidCertificate) As(alias string) *androidCertificate {
	a.androidCertificateDo.DO = *(a.androidCertificateDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *androidCertificate) updateTableName(table string) *androidCertificate {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt(table, "id")
	a.CertificateID = field.NewString(table, "certificate_id")
	a.AppID = field.NewInt(table, "app_id")
	a.UserID = field.NewInt(table, "user_id")
	a.Alias_ = field.NewString(table, "alias")
	a.Category = field.NewInt(table, "category")
	a.Publisher = field.NewString(table, "publisher")
	a.Owner = field.NewString(table, "owner")
	a.SignatureAlgorithm = field.NewString(table, "signature_algorithm")
	a.PublicKeyAlgorithm = field.NewString(table, "public_key_algorithm")
	a.Version = field.NewString(table, "version")
	a.SerialNumber = field.NewString(table, "serial_number")
	a.StoreProvider = field.NewString(table, "store_provider")
	a.StoreType = field.NewString(table, "store_type")
	a.CreationDate = field.NewTime(table, "creation_date")
	a.Sha1 = field.NewString(table, "sha1")
	a.Sha256 = field.NewString(table, "sha256")
	a.Storepass = field.NewString(table, "storepass")
	a.Keypass = field.NewString(table, "keypass")
	a.NotBefore = field.NewTime(table, "not_before")
	a.NotAfter = field.NewTime(table, "not_after")
	a.AesKeyID = field.NewInt(table, "aes_key_id")
	a.Content = field.NewBytes(table, "content")
	a.CreatedTime = field.NewTime(table, "created_time")
	a.DeletedTime = field.NewTime(table, "deleted_time")

	a.fillFieldMap()

	return a
}

func (a *androidCertificate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *androidCertificate) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 25)
	a.fieldMap["id"] = a.ID
	a.fieldMap["certificate_id"] = a.CertificateID
	a.fieldMap["app_id"] = a.AppID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["alias"] = a.Alias_
	a.fieldMap["category"] = a.Category
	a.fieldMap["publisher"] = a.Publisher
	a.fieldMap["owner"] = a.Owner
	a.fieldMap["signature_algorithm"] = a.SignatureAlgorithm
	a.fieldMap["public_key_algorithm"] = a.PublicKeyAlgorithm
	a.fieldMap["version"] = a.Version
	a.fieldMap["serial_number"] = a.SerialNumber
	a.fieldMap["store_provider"] = a.StoreProvider
	a.fieldMap["store_type"] = a.StoreType
	a.fieldMap["creation_date"] = a.CreationDate
	a.fieldMap["sha1"] = a.Sha1
	a.fieldMap["sha256"] = a.Sha256
	a.fieldMap["storepass"] = a.Storepass
	a.fieldMap["keypass"] = a.Keypass
	a.fieldMap["not_before"] = a.NotBefore
	a.fieldMap["not_after"] = a.NotAfter
	a.fieldMap["aes_key_id"] = a.AesKeyID
	a.fieldMap["content"] = a.Content
	a.fieldMap["created_time"] = a.CreatedTime
	a.fieldMap["deleted_time"] = a.DeletedTime
}

func (a androidCertificate) clone(db *gorm.DB) androidCertificate {
	a.androidCertificateDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a androidCertificate) replaceDB(db *gorm.DB) androidCertificate {
	a.androidCertificateDo.ReplaceDB(db)
	return a
}

type androidCertificateDo struct{ gen.DO }

type IAndroidCertificateDo interface {
	gen.SubQuery
	Debug() IAndroidCertificateDo
	WithContext(ctx context.Context) IAndroidCertificateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAndroidCertificateDo
	WriteDB() IAndroidCertificateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAndroidCertificateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAndroidCertificateDo
	Not(conds ...gen.Condition) IAndroidCertificateDo
	Or(conds ...gen.Condition) IAndroidCertificateDo
	Select(conds ...field.Expr) IAndroidCertificateDo
	Where(conds ...gen.Condition) IAndroidCertificateDo
	Order(conds ...field.Expr) IAndroidCertificateDo
	Distinct(cols ...field.Expr) IAndroidCertificateDo
	Omit(cols ...field.Expr) IAndroidCertificateDo
	Join(table schema.Tabler, on ...field.Expr) IAndroidCertificateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAndroidCertificateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAndroidCertificateDo
	Group(cols ...field.Expr) IAndroidCertificateDo
	Having(conds ...gen.Condition) IAndroidCertificateDo
	Limit(limit int) IAndroidCertificateDo
	Offset(offset int) IAndroidCertificateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAndroidCertificateDo
	Unscoped() IAndroidCertificateDo
	Create(values ...*model.AndroidCertificate) error
	CreateInBatches(values []*model.AndroidCertificate, batchSize int) error
	Save(values ...*model.AndroidCertificate) error
	First() (*model.AndroidCertificate, error)
	Take() (*model.AndroidCertificate, error)
	Last() (*model.AndroidCertificate, error)
	Find() ([]*model.AndroidCertificate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AndroidCertificate, err error)
	FindInBatches(result *[]*model.AndroidCertificate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AndroidCertificate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAndroidCertificateDo
	Assign(attrs ...field.AssignExpr) IAndroidCertificateDo
	Joins(fields ...field.RelationField) IAndroidCertificateDo
	Preload(fields ...field.RelationField) IAndroidCertificateDo
	FirstOrInit() (*model.AndroidCertificate, error)
	FirstOrCreate() (*model.AndroidCertificate, error)
	FindByPage(offset int, limit int) (result []*model.AndroidCertificate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAndroidCertificateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a androidCertificateDo) Debug() IAndroidCertificateDo {
	return a.withDO(a.DO.Debug())
}

func (a androidCertificateDo) WithContext(ctx context.Context) IAndroidCertificateDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a androidCertificateDo) ReadDB() IAndroidCertificateDo {
	return a.Clauses(dbresolver.Read)
}

func (a androidCertificateDo) WriteDB() IAndroidCertificateDo {
	return a.Clauses(dbresolver.Write)
}

func (a androidCertificateDo) Session(config *gorm.Session) IAndroidCertificateDo {
	return a.withDO(a.DO.Session(config))
}

func (a androidCertificateDo) Clauses(conds ...clause.Expression) IAndroidCertificateDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a androidCertificateDo) Returning(value interface{}, columns ...string) IAndroidCertificateDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a androidCertificateDo) Not(conds ...gen.Condition) IAndroidCertificateDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a androidCertificateDo) Or(conds ...gen.Condition) IAndroidCertificateDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a androidCertificateDo) Select(conds ...field.Expr) IAndroidCertificateDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a androidCertificateDo) Where(conds ...gen.Condition) IAndroidCertificateDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a androidCertificateDo) Order(conds ...field.Expr) IAndroidCertificateDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a androidCertificateDo) Distinct(cols ...field.Expr) IAndroidCertificateDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a androidCertificateDo) Omit(cols ...field.Expr) IAndroidCertificateDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a androidCertificateDo) Join(table schema.Tabler, on ...field.Expr) IAndroidCertificateDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a androidCertificateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAndroidCertificateDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a androidCertificateDo) RightJoin(table schema.Tabler, on ...field.Expr) IAndroidCertificateDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a androidCertificateDo) Group(cols ...field.Expr) IAndroidCertificateDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a androidCertificateDo) Having(conds ...gen.Condition) IAndroidCertificateDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a androidCertificateDo) Limit(limit int) IAndroidCertificateDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a androidCertificateDo) Offset(offset int) IAndroidCertificateDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a androidCertificateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAndroidCertificateDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a androidCertificateDo) Unscoped() IAndroidCertificateDo {
	return a.withDO(a.DO.Unscoped())
}

func (a androidCertificateDo) Create(values ...*model.AndroidCertificate) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a androidCertificateDo) CreateInBatches(values []*model.AndroidCertificate, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a androidCertificateDo) Save(values ...*model.AndroidCertificate) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a androidCertificateDo) First() (*model.AndroidCertificate, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AndroidCertificate), nil
	}
}

func (a androidCertificateDo) Take() (*model.AndroidCertificate, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AndroidCertificate), nil
	}
}

func (a androidCertificateDo) Last() (*model.AndroidCertificate, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AndroidCertificate), nil
	}
}

func (a androidCertificateDo) Find() ([]*model.AndroidCertificate, error) {
	result, err := a.DO.Find()
	return result.([]*model.AndroidCertificate), err
}

func (a androidCertificateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AndroidCertificate, err error) {
	buf := make([]*model.AndroidCertificate, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a androidCertificateDo) FindInBatches(result *[]*model.AndroidCertificate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a androidCertificateDo) Attrs(attrs ...field.AssignExpr) IAndroidCertificateDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a androidCertificateDo) Assign(attrs ...field.AssignExpr) IAndroidCertificateDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a androidCertificateDo) Joins(fields ...field.RelationField) IAndroidCertificateDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a androidCertificateDo) Preload(fields ...field.RelationField) IAndroidCertificateDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a androidCertificateDo) FirstOrInit() (*model.AndroidCertificate, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AndroidCertificate), nil
	}
}

func (a androidCertificateDo) FirstOrCreate() (*model.AndroidCertificate, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AndroidCertificate), nil
	}
}

func (a androidCertificateDo) FindByPage(offset int, limit int) (result []*model.AndroidCertificate, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a androidCertificateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a androidCertificateDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a androidCertificateDo) Delete(models ...*model.AndroidCertificate) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *androidCertificateDo) withDO(do gen.Dao) *androidCertificateDo {
	a.DO = *do.(*gen.DO)
	return a
}
