// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/ivfzhou/csms/comm/model"

	"time"
)

func newAndroidSigningJob(db *gorm.DB, opts ...gen.DOOption) androidSigningJob {
	_androidSigningJob := androidSigningJob{}

	_androidSigningJob.androidSigningJobDo.UseDB(db, opts...)
	_androidSigningJob.androidSigningJobDo.UseModel(&model.AndroidSigningJob{})

	tableName := _androidSigningJob.androidSigningJobDo.TableName()
	_androidSigningJob.ALL = field.NewAsterisk(tableName)
	_androidSigningJob.ID = field.NewInt(tableName, "id")
	_androidSigningJob.JobID = field.NewString(tableName, "job_id")
	_androidSigningJob.AppID = field.NewInt(tableName, "app_id")
	_androidSigningJob.UserID = field.NewInt(tableName, "user_id")
	_androidSigningJob.Type = field.NewInt(tableName, "type")
	_androidSigningJob.CertificateID = field.NewInt(tableName, "certificate_id")
	_androidSigningJob.FileID = field.NewString(tableName, "file_id")
	_androidSigningJob.SignedFileID = field.NewString(tableName, "signed_file_id")
	_androidSigningJob.Log = field.NewString(tableName, "log")
	_androidSigningJob.SignatureSchemas = field.NewField(tableName, "signature_schemas")
	_androidSigningJob.MinimumSdkLevel = field.NewInt(tableName, "minimum_sdk_level")
	_androidSigningJob.Source = field.NewInt(tableName, "source")
	_androidSigningJob.FinishedTime = field.NewTime(tableName, "finished_time")
	_androidSigningJob.Status = field.NewInt(tableName, "status")
	_androidSigningJob.CreatedTime = field.NewTime(tableName, "created_time")

	_androidSigningJob.fillFieldMap()

	return _androidSigningJob
}

// androidSigningJob 安卓签名任务表
type androidSigningJob struct {
	androidSigningJobDo

	ALL              field.Asterisk
	ID               field.Int    // 自增主码
	JobID            field.String // 任务 ID，前 6 为是年月，后面是 UUID
	AppID            field.Int    // 所属应用 ID
	UserID           field.Int    // 提交人 ID
	Type             field.Int    // 类型，1=APK 签名、2=AAB 签名、3=补丁签名
	CertificateID    field.Int    // 安卓证书表 ID
	FileID           field.String // 待签名文件 ID
	SignedFileID     field.String // 已签名文件 ID
	Log              field.String // 任务日志
	SignatureSchemas field.Field  // APK 签名方案，英文逗号分隔
	MinimumSdkLevel  field.Int    // 补丁包签名 SDK API 最低版本号
	Source           field.Int    // 来源，1=页面、2=OpenAPI
	FinishedTime     field.Time   // 结束时间
	Status           field.Int    // 状态，1=进行中，2=成功，3=失败
	CreatedTime      field.Time   // 提交时间

	fieldMap map[string]field.Expr
}

func (a androidSigningJob) Table(newTableName string) *androidSigningJob {
	a.androidSigningJobDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a androidSigningJob) As(alias string) *androidSigningJob {
	a.androidSigningJobDo.DO = *(a.androidSigningJobDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *androidSigningJob) updateTableName(table string) *androidSigningJob {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt(table, "id")
	a.JobID = field.NewString(table, "job_id")
	a.AppID = field.NewInt(table, "app_id")
	a.UserID = field.NewInt(table, "user_id")
	a.Type = field.NewInt(table, "type")
	a.CertificateID = field.NewInt(table, "certificate_id")
	a.FileID = field.NewString(table, "file_id")
	a.SignedFileID = field.NewString(table, "signed_file_id")
	a.Log = field.NewString(table, "log")
	a.SignatureSchemas = field.NewField(table, "signature_schemas")
	a.MinimumSdkLevel = field.NewInt(table, "minimum_sdk_level")
	a.Source = field.NewInt(table, "source")
	a.FinishedTime = field.NewTime(table, "finished_time")
	a.Status = field.NewInt(table, "status")
	a.CreatedTime = field.NewTime(table, "created_time")

	a.fillFieldMap()

	return a
}

func (a *androidSigningJob) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *androidSigningJob) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 15)
	a.fieldMap["id"] = a.ID
	a.fieldMap["job_id"] = a.JobID
	a.fieldMap["app_id"] = a.AppID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["type"] = a.Type
	a.fieldMap["certificate_id"] = a.CertificateID
	a.fieldMap["file_id"] = a.FileID
	a.fieldMap["signed_file_id"] = a.SignedFileID
	a.fieldMap["log"] = a.Log
	a.fieldMap["signature_schemas"] = a.SignatureSchemas
	a.fieldMap["minimum_sdk_level"] = a.MinimumSdkLevel
	a.fieldMap["source"] = a.Source
	a.fieldMap["finished_time"] = a.FinishedTime
	a.fieldMap["status"] = a.Status
	a.fieldMap["created_time"] = a.CreatedTime
}

func (a androidSigningJob) clone(db *gorm.DB) androidSigningJob {
	a.androidSigningJobDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a androidSigningJob) replaceDB(db *gorm.DB) androidSigningJob {
	a.androidSigningJobDo.ReplaceDB(db)
	return a
}

type androidSigningJobDo struct{ gen.DO }

type IAndroidSigningJobDo interface {
	gen.SubQuery
	Debug() IAndroidSigningJobDo
	WithContext(ctx context.Context) IAndroidSigningJobDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAndroidSigningJobDo
	WriteDB() IAndroidSigningJobDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAndroidSigningJobDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAndroidSigningJobDo
	Not(conds ...gen.Condition) IAndroidSigningJobDo
	Or(conds ...gen.Condition) IAndroidSigningJobDo
	Select(conds ...field.Expr) IAndroidSigningJobDo
	Where(conds ...gen.Condition) IAndroidSigningJobDo
	Order(conds ...field.Expr) IAndroidSigningJobDo
	Distinct(cols ...field.Expr) IAndroidSigningJobDo
	Omit(cols ...field.Expr) IAndroidSigningJobDo
	Join(table schema.Tabler, on ...field.Expr) IAndroidSigningJobDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAndroidSigningJobDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAndroidSigningJobDo
	Group(cols ...field.Expr) IAndroidSigningJobDo
	Having(conds ...gen.Condition) IAndroidSigningJobDo
	Limit(limit int) IAndroidSigningJobDo
	Offset(offset int) IAndroidSigningJobDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAndroidSigningJobDo
	Unscoped() IAndroidSigningJobDo
	Create(values ...*model.AndroidSigningJob) error
	CreateInBatches(values []*model.AndroidSigningJob, batchSize int) error
	Save(values ...*model.AndroidSigningJob) error
	First() (*model.AndroidSigningJob, error)
	Take() (*model.AndroidSigningJob, error)
	Last() (*model.AndroidSigningJob, error)
	Find() ([]*model.AndroidSigningJob, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AndroidSigningJob, err error)
	FindInBatches(result *[]*model.AndroidSigningJob, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AndroidSigningJob) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAndroidSigningJobDo
	Assign(attrs ...field.AssignExpr) IAndroidSigningJobDo
	Joins(fields ...field.RelationField) IAndroidSigningJobDo
	Preload(fields ...field.RelationField) IAndroidSigningJobDo
	FirstOrInit() (*model.AndroidSigningJob, error)
	FirstOrCreate() (*model.AndroidSigningJob, error)
	FindByPage(offset int, limit int) (result []*model.AndroidSigningJob, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAndroidSigningJobDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetTables(db string) (result []string, err error)
	List(tables []string, appID int, keyWord string, status int, certificateIDs []int, userIDs []int, limit int, offset int) (result []*model.AndroidSigningJob, err error)
	Count2(tables []string, appID int, keyWord string, status int, certificateIDs []int, userIDs []int) (result int, err error)
	CountWithDay(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	CountWithWeek(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	CountWithMonth(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	CostWithDay(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	CostWithWeek(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	CostWithMonth(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
}

// select TABLE_NAME from information_schema.TABLES where TABLE_SCHEMA = @db
// and TABLE_NAME like 't_android_signing_job%'
func (a androidSigningJobDo) GetTables(db string) (result []string, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, db)
	generateSQL.WriteString("select TABLE_NAME from information_schema.TABLES where TABLE_SCHEMA = ? and TABLE_NAME like 't_android_signing_job%' ")

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select * from (
// {{ for i, t := range tables }}
//
//	select * from @@t {{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// where t.app_id = @appID
// {{ if status > 0 }} and t.status = @status {{ end }}
// {{ if len(certificateIDs) > 0 }} and t.certificate_id in (@certificateIDs) {{ end }}
// {{ if len(keyWord) > 0 }}
//
//	and (
//	  t.job_id = @keyWord or t.file_id = @keyWord or t.signed_file_id = @keyWord
//	  {{ if len(userIDs) > 0 }} or t.user_id in (@userIDs) {{ end }}
//	)
//
// {{ end }}
// order by t.created_time desc, t.id desc limit @limit offset @offset
func (a androidSigningJobDo) List(tables []string, appID int, keyWord string, status int, certificateIDs []int, userIDs []int, limit int, offset int) (result []*model.AndroidSigningJob, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from ( ")
	for i, t := range tables {
		generateSQL.WriteString("select * from " + a.Quote(t) + " ")
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	params = append(params, appID)
	generateSQL.WriteString(") t where t.app_id = ? ")
	if status > 0 {
		params = append(params, status)
		generateSQL.WriteString("and t.status = ? ")
	}
	if len(certificateIDs) > 0 {
		params = append(params, certificateIDs)
		generateSQL.WriteString("and t.certificate_id in (?) ")
	}
	if len(keyWord) > 0 {
		params = append(params, keyWord)
		params = append(params, keyWord)
		params = append(params, keyWord)
		generateSQL.WriteString("and ( t.job_id = ? or t.file_id = ? or t.signed_file_id = ? ")
		if len(userIDs) > 0 {
			params = append(params, userIDs)
			generateSQL.WriteString("or t.user_id in (?) ")
		}
		generateSQL.WriteString(") ")
	}
	params = append(params, limit)
	params = append(params, offset)
	generateSQL.WriteString("order by t.created_time desc, t.id desc limit ? offset ? ")

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select count(*) from (
// {{ for i, t := range tables }}
//
//	select * from @@t {{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// where t.app_id = @appID
// {{ if status > 0 }} and t.status = @status {{ end }}
// {{ if len(certificateIDs) > 0 }} and t.certificate_id in (@certificateIDs) {{ end }}
// {{ if len(keyWord) > 0 }}
//
//	and (
//	  t.job_id = @keyWord or t.file_id = @keyWord or t.signed_file_id = @keyWord
//	  {{ if len(userIDs) > 0 }} or t.user_id in (@userIDs) {{ end }}
//	)
//
// {{ end }}
func (a androidSigningJobDo) Count2(tables []string, appID int, keyWord string, status int, certificateIDs []int, userIDs []int) (result int, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select count(*) from ( ")
	for i, t := range tables {
		generateSQL.WriteString("select * from " + a.Quote(t) + " ")
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	params = append(params, appID)
	generateSQL.WriteString(") t where t.app_id = ? ")
	if status > 0 {
		params = append(params, status)
		generateSQL.WriteString("and t.status = ? ")
	}
	if len(certificateIDs) > 0 {
		params = append(params, certificateIDs)
		generateSQL.WriteString("and t.certificate_id in (?) ")
	}
	if len(keyWord) > 0 {
		params = append(params, keyWord)
		params = append(params, keyWord)
		params = append(params, keyWord)
		generateSQL.WriteString("and ( t.job_id = ? or t.file_id = ? or t.signed_file_id = ? ")
		if len(userIDs) > 0 {
			params = append(params, userIDs)
			generateSQL.WriteString("or t.user_id in (?) ")
		}
		generateSQL.WriteString(") ")
	}

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.type `type`, count(*) `count`, date_format(t.created_time, '%Y%m%d') `day` from (
// {{ for i, t := range tables }}
//
//	select * from @@t where created_time between @begin and @end
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//	{{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// group by `day`, `type`
// order by `day`
func (a androidSigningJobDo) CountWithDay(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.type `type`, count(*) `count`, date_format(t.created_time, '%Y%m%d') `day` from ( ")
	for i, t := range tables {
		params = append(params, begin)
		params = append(params, end)
		generateSQL.WriteString("select * from " + a.Quote(t) + " where created_time between ? and ? ")
		if appID > 0 {
			params = append(params, appID)
			generateSQL.WriteString("and app_id = ? ")
		}
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	generateSQL.WriteString(") t group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.type `type`, count(*) `count`, date_format(date_sub(t.created_time, INTERVAL (dayofweek(t.created_time)-2) DAY), '%Y%m%d') `day` from (
// {{ for i, t := range tables }}
//
//	select * from @@t where created_time between @begin and @end
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//	{{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// group by `day`, `type`
// order by `day`
func (a androidSigningJobDo) CountWithWeek(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.type `type`, count(*) `count`, date_format(date_sub(t.created_time, INTERVAL (dayofweek(t.created_time)-2) DAY), '%Y%m%d') `day` from ( ")
	for i, t := range tables {
		params = append(params, begin)
		params = append(params, end)
		generateSQL.WriteString("select * from " + a.Quote(t) + " where created_time between ? and ? ")
		if appID > 0 {
			params = append(params, appID)
			generateSQL.WriteString("and app_id = ? ")
		}
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	generateSQL.WriteString(") t group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.type `type`, count(*) `count`, date_format(t.created_time, '%Y%m') `day` from (
// {{ for i, t := range tables }}
//
//	select * from @@t where created_time between @begin and @end
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//	{{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// group by `day`, `type`
// order by `day`
func (a androidSigningJobDo) CountWithMonth(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.type `type`, count(*) `count`, date_format(t.created_time, '%Y%m') `day` from ( ")
	for i, t := range tables {
		params = append(params, begin)
		params = append(params, end)
		generateSQL.WriteString("select * from " + a.Quote(t) + " where created_time between ? and ? ")
		if appID > 0 {
			params = append(params, appID)
			generateSQL.WriteString("and app_id = ? ")
		}
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	generateSQL.WriteString(") t group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.type `type`, date_format(t.created_time, '%Y%m%d') `day`, cast(round(avg(timestampdiff(SECOND, t.created_time, ifnull(t.finished_time, now()))), 0) as signed) `cost` from (
// {{ for i, t := range tables }}
//
//	select * from @@t where created_time between @begin and @end and status in (2, 3)
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//	{{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// group by `day`, `type`
// order by `day`
func (a androidSigningJobDo) CostWithDay(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.type `type`, date_format(t.created_time, '%Y%m%d') `day`, cast(round(avg(timestampdiff(SECOND, t.created_time, ifnull(t.finished_time, now()))), 0) as signed) `cost` from ( ")
	for i, t := range tables {
		params = append(params, begin)
		params = append(params, end)
		generateSQL.WriteString("select * from " + a.Quote(t) + " where created_time between ? and ? and status in (2, 3) ")
		if appID > 0 {
			params = append(params, appID)
			generateSQL.WriteString("and app_id = ? ")
		}
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	generateSQL.WriteString(") t group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.type `type`, date_format(date_sub(t.created_time, INTERVAL (dayofweek(t.created_time)-2) DAY), '%Y%m%d') `day`, cast(round(avg(timestampdiff(SECOND, t.created_time, ifnull(t.finished_time, now()))), 0) as signed) `cost` from (
// {{ for i, t := range tables }}
//
//	select * from @@t where created_time between @begin and @end and status in (2, 3)
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//	{{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// group by `day`, `type`
// order by `day`
func (a androidSigningJobDo) CostWithWeek(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.type `type`, date_format(date_sub(t.created_time, INTERVAL (dayofweek(t.created_time)-2) DAY), '%Y%m%d') `day`, cast(round(avg(timestampdiff(SECOND, t.created_time, ifnull(t.finished_time, now()))), 0) as signed) `cost` from ( ")
	for i, t := range tables {
		params = append(params, begin)
		params = append(params, end)
		generateSQL.WriteString("select * from " + a.Quote(t) + " where created_time between ? and ? and status in (2, 3) ")
		if appID > 0 {
			params = append(params, appID)
			generateSQL.WriteString("and app_id = ? ")
		}
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	generateSQL.WriteString(") t group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.type `type`, date_format(t.created_time, '%Y%m') `day`, cast(round(avg(timestampdiff(SECOND, t.created_time, ifnull(t.finished_time, now()))), 0) as signed) `cost` from (
// {{ for i, t := range tables }}
//
//	select * from @@t where created_time between @begin and @end and status in (2, 3)
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//	{{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// group by `day`, `type`
// order by `day`
func (a androidSigningJobDo) CostWithMonth(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.type `type`, date_format(t.created_time, '%Y%m') `day`, cast(round(avg(timestampdiff(SECOND, t.created_time, ifnull(t.finished_time, now()))), 0) as signed) `cost` from ( ")
	for i, t := range tables {
		params = append(params, begin)
		params = append(params, end)
		generateSQL.WriteString("select * from " + a.Quote(t) + " where created_time between ? and ? and status in (2, 3) ")
		if appID > 0 {
			params = append(params, appID)
			generateSQL.WriteString("and app_id = ? ")
		}
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	generateSQL.WriteString(") t group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (a androidSigningJobDo) Debug() IAndroidSigningJobDo {
	return a.withDO(a.DO.Debug())
}

func (a androidSigningJobDo) WithContext(ctx context.Context) IAndroidSigningJobDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a androidSigningJobDo) ReadDB() IAndroidSigningJobDo {
	return a.Clauses(dbresolver.Read)
}

func (a androidSigningJobDo) WriteDB() IAndroidSigningJobDo {
	return a.Clauses(dbresolver.Write)
}

func (a androidSigningJobDo) Session(config *gorm.Session) IAndroidSigningJobDo {
	return a.withDO(a.DO.Session(config))
}

func (a androidSigningJobDo) Clauses(conds ...clause.Expression) IAndroidSigningJobDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a androidSigningJobDo) Returning(value interface{}, columns ...string) IAndroidSigningJobDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a androidSigningJobDo) Not(conds ...gen.Condition) IAndroidSigningJobDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a androidSigningJobDo) Or(conds ...gen.Condition) IAndroidSigningJobDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a androidSigningJobDo) Select(conds ...field.Expr) IAndroidSigningJobDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a androidSigningJobDo) Where(conds ...gen.Condition) IAndroidSigningJobDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a androidSigningJobDo) Order(conds ...field.Expr) IAndroidSigningJobDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a androidSigningJobDo) Distinct(cols ...field.Expr) IAndroidSigningJobDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a androidSigningJobDo) Omit(cols ...field.Expr) IAndroidSigningJobDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a androidSigningJobDo) Join(table schema.Tabler, on ...field.Expr) IAndroidSigningJobDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a androidSigningJobDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAndroidSigningJobDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a androidSigningJobDo) RightJoin(table schema.Tabler, on ...field.Expr) IAndroidSigningJobDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a androidSigningJobDo) Group(cols ...field.Expr) IAndroidSigningJobDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a androidSigningJobDo) Having(conds ...gen.Condition) IAndroidSigningJobDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a androidSigningJobDo) Limit(limit int) IAndroidSigningJobDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a androidSigningJobDo) Offset(offset int) IAndroidSigningJobDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a androidSigningJobDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAndroidSigningJobDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a androidSigningJobDo) Unscoped() IAndroidSigningJobDo {
	return a.withDO(a.DO.Unscoped())
}

func (a androidSigningJobDo) Create(values ...*model.AndroidSigningJob) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a androidSigningJobDo) CreateInBatches(values []*model.AndroidSigningJob, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a androidSigningJobDo) Save(values ...*model.AndroidSigningJob) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a androidSigningJobDo) First() (*model.AndroidSigningJob, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AndroidSigningJob), nil
	}
}

func (a androidSigningJobDo) Take() (*model.AndroidSigningJob, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AndroidSigningJob), nil
	}
}

func (a androidSigningJobDo) Last() (*model.AndroidSigningJob, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AndroidSigningJob), nil
	}
}

func (a androidSigningJobDo) Find() ([]*model.AndroidSigningJob, error) {
	result, err := a.DO.Find()
	return result.([]*model.AndroidSigningJob), err
}

func (a androidSigningJobDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AndroidSigningJob, err error) {
	buf := make([]*model.AndroidSigningJob, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a androidSigningJobDo) FindInBatches(result *[]*model.AndroidSigningJob, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a androidSigningJobDo) Attrs(attrs ...field.AssignExpr) IAndroidSigningJobDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a androidSigningJobDo) Assign(attrs ...field.AssignExpr) IAndroidSigningJobDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a androidSigningJobDo) Joins(fields ...field.RelationField) IAndroidSigningJobDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a androidSigningJobDo) Preload(fields ...field.RelationField) IAndroidSigningJobDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a androidSigningJobDo) FirstOrInit() (*model.AndroidSigningJob, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AndroidSigningJob), nil
	}
}

func (a androidSigningJobDo) FirstOrCreate() (*model.AndroidSigningJob, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AndroidSigningJob), nil
	}
}

func (a androidSigningJobDo) FindByPage(offset int, limit int) (result []*model.AndroidSigningJob, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a androidSigningJobDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a androidSigningJobDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a androidSigningJobDo) Delete(models ...*model.AndroidSigningJob) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *androidSigningJobDo) withDO(do gen.Dao) *androidSigningJobDo {
	a.DO = *do.(*gen.DO)
	return a
}
