// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/ivfzhou/csms/comm/model"
)

func newAppleSigningJob(db *gorm.DB, opts ...gen.DOOption) appleSigningJob {
	_appleSigningJob := appleSigningJob{}

	_appleSigningJob.appleSigningJobDo.UseDB(db, opts...)
	_appleSigningJob.appleSigningJobDo.UseModel(&model.AppleSigningJob{})

	tableName := _appleSigningJob.appleSigningJobDo.TableName()
	_appleSigningJob.ALL = field.NewAsterisk(tableName)
	_appleSigningJob.ID = field.NewInt(tableName, "id")
	_appleSigningJob.JobID = field.NewString(tableName, "job_id")
	_appleSigningJob.AppID = field.NewInt(tableName, "app_id")
	_appleSigningJob.UserID = field.NewInt(tableName, "user_id")
	_appleSigningJob.ProfileID = field.NewInt(tableName, "profile_id")
	_appleSigningJob.FileID = field.NewString(tableName, "file_id")
	_appleSigningJob.SignedFileID = field.NewString(tableName, "signed_file_id")
	_appleSigningJob.Log = field.NewString(tableName, "log")
	_appleSigningJob.Source = field.NewInt(tableName, "source")
	_appleSigningJob.FinishedTime = field.NewTime(tableName, "finished_time")
	_appleSigningJob.Status = field.NewInt(tableName, "status")
	_appleSigningJob.CreatedTime = field.NewTime(tableName, "created_time")

	_appleSigningJob.fillFieldMap()

	return _appleSigningJob
}

// appleSigningJob 苹果签名任务表
type appleSigningJob struct {
	appleSigningJobDo

	ALL          field.Asterisk
	ID           field.Int    // 自增主码
	JobID        field.String // 任务 ID，前 6 为是年月，后面是 UUID
	AppID        field.Int    // 所属应用 ID
	UserID       field.Int    // 提交人 ID
	ProfileID    field.Int    // 描述文件表 ID
	FileID       field.String // 待签名文件 ID
	SignedFileID field.String // 已签名文件 ID
	Log          field.String // 任务日志
	Source       field.Int    // 来源，1=页面、2=OpenAPI
	FinishedTime field.Time   // 结束时间
	Status       field.Int    // 状态，1=进行中、2=成功、3=失败
	CreatedTime  field.Time   // 提交时间

	fieldMap map[string]field.Expr
}

func (a appleSigningJob) Table(newTableName string) *appleSigningJob {
	a.appleSigningJobDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a appleSigningJob) As(alias string) *appleSigningJob {
	a.appleSigningJobDo.DO = *(a.appleSigningJobDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *appleSigningJob) updateTableName(table string) *appleSigningJob {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt(table, "id")
	a.JobID = field.NewString(table, "job_id")
	a.AppID = field.NewInt(table, "app_id")
	a.UserID = field.NewInt(table, "user_id")
	a.ProfileID = field.NewInt(table, "profile_id")
	a.FileID = field.NewString(table, "file_id")
	a.SignedFileID = field.NewString(table, "signed_file_id")
	a.Log = field.NewString(table, "log")
	a.Source = field.NewInt(table, "source")
	a.FinishedTime = field.NewTime(table, "finished_time")
	a.Status = field.NewInt(table, "status")
	a.CreatedTime = field.NewTime(table, "created_time")

	a.fillFieldMap()

	return a
}

func (a *appleSigningJob) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *appleSigningJob) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 12)
	a.fieldMap["id"] = a.ID
	a.fieldMap["job_id"] = a.JobID
	a.fieldMap["app_id"] = a.AppID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["profile_id"] = a.ProfileID
	a.fieldMap["file_id"] = a.FileID
	a.fieldMap["signed_file_id"] = a.SignedFileID
	a.fieldMap["log"] = a.Log
	a.fieldMap["source"] = a.Source
	a.fieldMap["finished_time"] = a.FinishedTime
	a.fieldMap["status"] = a.Status
	a.fieldMap["created_time"] = a.CreatedTime
}

func (a appleSigningJob) clone(db *gorm.DB) appleSigningJob {
	a.appleSigningJobDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a appleSigningJob) replaceDB(db *gorm.DB) appleSigningJob {
	a.appleSigningJobDo.ReplaceDB(db)
	return a
}

type appleSigningJobDo struct{ gen.DO }

type IAppleSigningJobDo interface {
	gen.SubQuery
	Debug() IAppleSigningJobDo
	WithContext(ctx context.Context) IAppleSigningJobDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAppleSigningJobDo
	WriteDB() IAppleSigningJobDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAppleSigningJobDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAppleSigningJobDo
	Not(conds ...gen.Condition) IAppleSigningJobDo
	Or(conds ...gen.Condition) IAppleSigningJobDo
	Select(conds ...field.Expr) IAppleSigningJobDo
	Where(conds ...gen.Condition) IAppleSigningJobDo
	Order(conds ...field.Expr) IAppleSigningJobDo
	Distinct(cols ...field.Expr) IAppleSigningJobDo
	Omit(cols ...field.Expr) IAppleSigningJobDo
	Join(table schema.Tabler, on ...field.Expr) IAppleSigningJobDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAppleSigningJobDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAppleSigningJobDo
	Group(cols ...field.Expr) IAppleSigningJobDo
	Having(conds ...gen.Condition) IAppleSigningJobDo
	Limit(limit int) IAppleSigningJobDo
	Offset(offset int) IAppleSigningJobDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAppleSigningJobDo
	Unscoped() IAppleSigningJobDo
	Create(values ...*model.AppleSigningJob) error
	CreateInBatches(values []*model.AppleSigningJob, batchSize int) error
	Save(values ...*model.AppleSigningJob) error
	First() (*model.AppleSigningJob, error)
	Take() (*model.AppleSigningJob, error)
	Last() (*model.AppleSigningJob, error)
	Find() ([]*model.AppleSigningJob, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AppleSigningJob, err error)
	FindInBatches(result *[]*model.AppleSigningJob, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AppleSigningJob) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAppleSigningJobDo
	Assign(attrs ...field.AssignExpr) IAppleSigningJobDo
	Joins(fields ...field.RelationField) IAppleSigningJobDo
	Preload(fields ...field.RelationField) IAppleSigningJobDo
	FirstOrInit() (*model.AppleSigningJob, error)
	FirstOrCreate() (*model.AppleSigningJob, error)
	FindByPage(offset int, limit int) (result []*model.AppleSigningJob, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAppleSigningJobDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetTables(db string) (result []string, err error)
	List(tables []string, appID int, limit int, offset int) (result []*model.AppleSigningJob, err error)
	Count2(tables []string, appID int) (result int, err error)
}

// select TABLE_NAME from information_schema.TABLES where TABLE_SCHEMA = @db
// and TABLE_NAME like 't_apple_signing_job%'
func (a appleSigningJobDo) GetTables(db string) (result []string, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, db)
	generateSQL.WriteString("select TABLE_NAME from information_schema.TABLES where TABLE_SCHEMA = ? and TABLE_NAME like 't_apple_signing_job%' ")

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select * from (
// {{ for i, t := range tables }}
//
//	select * from @@t {{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// where t.app_id = @appID
// order by t.created_time desc, t.id desc limit @limit offset @offset
func (a appleSigningJobDo) List(tables []string, appID int, limit int, offset int) (result []*model.AppleSigningJob, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from ( ")
	for i, t := range tables {
		generateSQL.WriteString("select * from " + a.Quote(t) + " ")
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	params = append(params, appID)
	params = append(params, limit)
	params = append(params, offset)
	generateSQL.WriteString(") t where t.app_id = ? order by t.created_time desc, t.id desc limit ? offset ? ")

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select count(*) from (
// {{ for i, t := range tables }}
//
//	select * from @@t {{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// where t.app_id = @appID
func (a appleSigningJobDo) Count2(tables []string, appID int) (result int, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select count(*) from ( ")
	for i, t := range tables {
		generateSQL.WriteString("select * from " + a.Quote(t) + " ")
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	params = append(params, appID)
	generateSQL.WriteString(") t where t.app_id = ? ")

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (a appleSigningJobDo) Debug() IAppleSigningJobDo {
	return a.withDO(a.DO.Debug())
}

func (a appleSigningJobDo) WithContext(ctx context.Context) IAppleSigningJobDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a appleSigningJobDo) ReadDB() IAppleSigningJobDo {
	return a.Clauses(dbresolver.Read)
}

func (a appleSigningJobDo) WriteDB() IAppleSigningJobDo {
	return a.Clauses(dbresolver.Write)
}

func (a appleSigningJobDo) Session(config *gorm.Session) IAppleSigningJobDo {
	return a.withDO(a.DO.Session(config))
}

func (a appleSigningJobDo) Clauses(conds ...clause.Expression) IAppleSigningJobDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a appleSigningJobDo) Returning(value interface{}, columns ...string) IAppleSigningJobDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a appleSigningJobDo) Not(conds ...gen.Condition) IAppleSigningJobDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a appleSigningJobDo) Or(conds ...gen.Condition) IAppleSigningJobDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a appleSigningJobDo) Select(conds ...field.Expr) IAppleSigningJobDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a appleSigningJobDo) Where(conds ...gen.Condition) IAppleSigningJobDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a appleSigningJobDo) Order(conds ...field.Expr) IAppleSigningJobDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a appleSigningJobDo) Distinct(cols ...field.Expr) IAppleSigningJobDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a appleSigningJobDo) Omit(cols ...field.Expr) IAppleSigningJobDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a appleSigningJobDo) Join(table schema.Tabler, on ...field.Expr) IAppleSigningJobDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a appleSigningJobDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAppleSigningJobDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a appleSigningJobDo) RightJoin(table schema.Tabler, on ...field.Expr) IAppleSigningJobDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a appleSigningJobDo) Group(cols ...field.Expr) IAppleSigningJobDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a appleSigningJobDo) Having(conds ...gen.Condition) IAppleSigningJobDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a appleSigningJobDo) Limit(limit int) IAppleSigningJobDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a appleSigningJobDo) Offset(offset int) IAppleSigningJobDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a appleSigningJobDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAppleSigningJobDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a appleSigningJobDo) Unscoped() IAppleSigningJobDo {
	return a.withDO(a.DO.Unscoped())
}

func (a appleSigningJobDo) Create(values ...*model.AppleSigningJob) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a appleSigningJobDo) CreateInBatches(values []*model.AppleSigningJob, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a appleSigningJobDo) Save(values ...*model.AppleSigningJob) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a appleSigningJobDo) First() (*model.AppleSigningJob, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleSigningJob), nil
	}
}

func (a appleSigningJobDo) Take() (*model.AppleSigningJob, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleSigningJob), nil
	}
}

func (a appleSigningJobDo) Last() (*model.AppleSigningJob, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleSigningJob), nil
	}
}

func (a appleSigningJobDo) Find() ([]*model.AppleSigningJob, error) {
	result, err := a.DO.Find()
	return result.([]*model.AppleSigningJob), err
}

func (a appleSigningJobDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AppleSigningJob, err error) {
	buf := make([]*model.AppleSigningJob, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a appleSigningJobDo) FindInBatches(result *[]*model.AppleSigningJob, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a appleSigningJobDo) Attrs(attrs ...field.AssignExpr) IAppleSigningJobDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a appleSigningJobDo) Assign(attrs ...field.AssignExpr) IAppleSigningJobDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a appleSigningJobDo) Joins(fields ...field.RelationField) IAppleSigningJobDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a appleSigningJobDo) Preload(fields ...field.RelationField) IAppleSigningJobDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a appleSigningJobDo) FirstOrInit() (*model.AppleSigningJob, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleSigningJob), nil
	}
}

func (a appleSigningJobDo) FirstOrCreate() (*model.AppleSigningJob, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleSigningJob), nil
	}
}

func (a appleSigningJobDo) FindByPage(offset int, limit int) (result []*model.AppleSigningJob, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a appleSigningJobDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a appleSigningJobDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a appleSigningJobDo) Delete(models ...*model.AppleSigningJob) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *appleSigningJobDo) withDO(do gen.Dao) *appleSigningJobDo {
	a.DO = *do.(*gen.DO)
	return a
}
