// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/ivfzhou/csms/comm/model"
)

func newAPIAccount(db *gorm.DB, opts ...gen.DOOption) aPIAccount {
	_aPIAccount := aPIAccount{}

	_aPIAccount.aPIAccountDo.UseDB(db, opts...)
	_aPIAccount.aPIAccountDo.UseModel(&model.APIAccount{})

	tableName := _aPIAccount.aPIAccountDo.TableName()
	_aPIAccount.ALL = field.NewAsterisk(tableName)
	_aPIAccount.ID = field.NewInt(tableName, "id")
	_aPIAccount.AppID = field.NewInt(tableName, "app_id")
	_aPIAccount.UserID = field.NewInt(tableName, "user_id")
	_aPIAccount.AccountID = field.NewString(tableName, "account_id")
	_aPIAccount.IP = field.NewField(tableName, "ip")
	_aPIAccount.Frequency = field.NewInt(tableName, "frequency")
	_aPIAccount.Secret = field.NewString(tableName, "secret")
	_aPIAccount.ExpiredTime = field.NewTime(tableName, "expired_time")
	_aPIAccount.CreatedTime = field.NewTime(tableName, "created_time")
	_aPIAccount.UpdatedTime = field.NewTime(tableName, "updated_time")

	_aPIAccount.fillFieldMap()

	return _aPIAccount
}

// aPIAccount OpenAPI 凭证信息表
type aPIAccount struct {
	aPIAccountDo

	ALL         field.Asterisk
	ID          field.Int    // 自增主码
	AppID       field.Int    // 所属应用 ID
	UserID      field.Int    // 申请人 ID
	AccountID   field.String // 凭证 ID
	IP          field.Field  // 凭证可以放行的 IP、IP 段，*号表示所有，逗号分隔
	Frequency   field.Int    // 每分钟最高请求次数
	Secret      field.String // 密钥
	ExpiredTime field.Time   // 失效时间
	CreatedTime field.Time   // 创建时间
	UpdatedTime field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (a aPIAccount) Table(newTableName string) *aPIAccount {
	a.aPIAccountDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a aPIAccount) As(alias string) *aPIAccount {
	a.aPIAccountDo.DO = *(a.aPIAccountDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *aPIAccount) updateTableName(table string) *aPIAccount {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt(table, "id")
	a.AppID = field.NewInt(table, "app_id")
	a.UserID = field.NewInt(table, "user_id")
	a.AccountID = field.NewString(table, "account_id")
	a.IP = field.NewField(table, "ip")
	a.Frequency = field.NewInt(table, "frequency")
	a.Secret = field.NewString(table, "secret")
	a.ExpiredTime = field.NewTime(table, "expired_time")
	a.CreatedTime = field.NewTime(table, "created_time")
	a.UpdatedTime = field.NewTime(table, "updated_time")

	a.fillFieldMap()

	return a
}

func (a *aPIAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *aPIAccount) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["app_id"] = a.AppID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["account_id"] = a.AccountID
	a.fieldMap["ip"] = a.IP
	a.fieldMap["frequency"] = a.Frequency
	a.fieldMap["secret"] = a.Secret
	a.fieldMap["expired_time"] = a.ExpiredTime
	a.fieldMap["created_time"] = a.CreatedTime
	a.fieldMap["updated_time"] = a.UpdatedTime
}

func (a aPIAccount) clone(db *gorm.DB) aPIAccount {
	a.aPIAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a aPIAccount) replaceDB(db *gorm.DB) aPIAccount {
	a.aPIAccountDo.ReplaceDB(db)
	return a
}

type aPIAccountDo struct{ gen.DO }

type IAPIAccountDo interface {
	gen.SubQuery
	Debug() IAPIAccountDo
	WithContext(ctx context.Context) IAPIAccountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAPIAccountDo
	WriteDB() IAPIAccountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAPIAccountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAPIAccountDo
	Not(conds ...gen.Condition) IAPIAccountDo
	Or(conds ...gen.Condition) IAPIAccountDo
	Select(conds ...field.Expr) IAPIAccountDo
	Where(conds ...gen.Condition) IAPIAccountDo
	Order(conds ...field.Expr) IAPIAccountDo
	Distinct(cols ...field.Expr) IAPIAccountDo
	Omit(cols ...field.Expr) IAPIAccountDo
	Join(table schema.Tabler, on ...field.Expr) IAPIAccountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAPIAccountDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAPIAccountDo
	Group(cols ...field.Expr) IAPIAccountDo
	Having(conds ...gen.Condition) IAPIAccountDo
	Limit(limit int) IAPIAccountDo
	Offset(offset int) IAPIAccountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAPIAccountDo
	Unscoped() IAPIAccountDo
	Create(values ...*model.APIAccount) error
	CreateInBatches(values []*model.APIAccount, batchSize int) error
	Save(values ...*model.APIAccount) error
	First() (*model.APIAccount, error)
	Take() (*model.APIAccount, error)
	Last() (*model.APIAccount, error)
	Find() ([]*model.APIAccount, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.APIAccount, err error)
	FindInBatches(result *[]*model.APIAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.APIAccount) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAPIAccountDo
	Assign(attrs ...field.AssignExpr) IAPIAccountDo
	Joins(fields ...field.RelationField) IAPIAccountDo
	Preload(fields ...field.RelationField) IAPIAccountDo
	FirstOrInit() (*model.APIAccount, error)
	FirstOrCreate() (*model.APIAccount, error)
	FindByPage(offset int, limit int) (result []*model.APIAccount, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAPIAccountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a aPIAccountDo) Debug() IAPIAccountDo {
	return a.withDO(a.DO.Debug())
}

func (a aPIAccountDo) WithContext(ctx context.Context) IAPIAccountDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a aPIAccountDo) ReadDB() IAPIAccountDo {
	return a.Clauses(dbresolver.Read)
}

func (a aPIAccountDo) WriteDB() IAPIAccountDo {
	return a.Clauses(dbresolver.Write)
}

func (a aPIAccountDo) Session(config *gorm.Session) IAPIAccountDo {
	return a.withDO(a.DO.Session(config))
}

func (a aPIAccountDo) Clauses(conds ...clause.Expression) IAPIAccountDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a aPIAccountDo) Returning(value interface{}, columns ...string) IAPIAccountDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a aPIAccountDo) Not(conds ...gen.Condition) IAPIAccountDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a aPIAccountDo) Or(conds ...gen.Condition) IAPIAccountDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a aPIAccountDo) Select(conds ...field.Expr) IAPIAccountDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a aPIAccountDo) Where(conds ...gen.Condition) IAPIAccountDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a aPIAccountDo) Order(conds ...field.Expr) IAPIAccountDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a aPIAccountDo) Distinct(cols ...field.Expr) IAPIAccountDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a aPIAccountDo) Omit(cols ...field.Expr) IAPIAccountDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a aPIAccountDo) Join(table schema.Tabler, on ...field.Expr) IAPIAccountDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a aPIAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAPIAccountDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a aPIAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) IAPIAccountDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a aPIAccountDo) Group(cols ...field.Expr) IAPIAccountDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a aPIAccountDo) Having(conds ...gen.Condition) IAPIAccountDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a aPIAccountDo) Limit(limit int) IAPIAccountDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a aPIAccountDo) Offset(offset int) IAPIAccountDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a aPIAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAPIAccountDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a aPIAccountDo) Unscoped() IAPIAccountDo {
	return a.withDO(a.DO.Unscoped())
}

func (a aPIAccountDo) Create(values ...*model.APIAccount) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a aPIAccountDo) CreateInBatches(values []*model.APIAccount, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a aPIAccountDo) Save(values ...*model.APIAccount) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a aPIAccountDo) First() (*model.APIAccount, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIAccount), nil
	}
}

func (a aPIAccountDo) Take() (*model.APIAccount, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIAccount), nil
	}
}

func (a aPIAccountDo) Last() (*model.APIAccount, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIAccount), nil
	}
}

func (a aPIAccountDo) Find() ([]*model.APIAccount, error) {
	result, err := a.DO.Find()
	return result.([]*model.APIAccount), err
}

func (a aPIAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.APIAccount, err error) {
	buf := make([]*model.APIAccount, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a aPIAccountDo) FindInBatches(result *[]*model.APIAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a aPIAccountDo) Attrs(attrs ...field.AssignExpr) IAPIAccountDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a aPIAccountDo) Assign(attrs ...field.AssignExpr) IAPIAccountDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a aPIAccountDo) Joins(fields ...field.RelationField) IAPIAccountDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a aPIAccountDo) Preload(fields ...field.RelationField) IAPIAccountDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a aPIAccountDo) FirstOrInit() (*model.APIAccount, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIAccount), nil
	}
}

func (a aPIAccountDo) FirstOrCreate() (*model.APIAccount, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIAccount), nil
	}
}

func (a aPIAccountDo) FindByPage(offset int, limit int) (result []*model.APIAccount, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a aPIAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a aPIAccountDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a aPIAccountDo) Delete(models ...*model.APIAccount) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *aPIAccountDo) withDO(do gen.Dao) *aPIAccountDo {
	a.DO = *do.(*gen.DO)
	return a
}
