// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/ivfzhou/csms/comm/model"
)

func newAppleDevice(db *gorm.DB, opts ...gen.DOOption) appleDevice {
	_appleDevice := appleDevice{}

	_appleDevice.appleDeviceDo.UseDB(db, opts...)
	_appleDevice.appleDeviceDo.UseModel(&model.AppleDevice{})

	tableName := _appleDevice.appleDeviceDo.TableName()
	_appleDevice.ALL = field.NewAsterisk(tableName)
	_appleDevice.ID = field.NewInt(tableName, "id")
	_appleDevice.AppID = field.NewInt(tableName, "app_id")
	_appleDevice.UserID = field.NewInt(tableName, "user_id")
	_appleDevice.InAppleID = field.NewString(tableName, "in_apple_id")
	_appleDevice.Udid = field.NewString(tableName, "udid")
	_appleDevice.Model = field.NewString(tableName, "model")
	_appleDevice.Remark = field.NewString(tableName, "remark")
	_appleDevice.Platform = field.NewString(tableName, "platform")
	_appleDevice.Status = field.NewInt(tableName, "status")
	_appleDevice.CreatedTime = field.NewTime(tableName, "created_time")
	_appleDevice.UpdatedTime = field.NewTime(tableName, "updated_time")

	_appleDevice.fillFieldMap()

	return _appleDevice
}

// appleDevice 苹果测试设备信息表
type appleDevice struct {
	appleDeviceDo

	ALL         field.Asterisk
	ID          field.Int    // 自增主码
	AppID       field.Int    // 所属应用 ID
	UserID      field.Int    // 申请人 ID
	InAppleID   field.String // 在苹果服务器中的 ID
	Udid        field.String // 设备 ID
	Model       field.String // 设备型号
	Remark      field.String // 备注
	Platform    field.String // 平台
	Status      field.Int    // 状态，1=正常、2=待审核、3=未通过
	CreatedTime field.Time   // 创建时间
	UpdatedTime field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (a appleDevice) Table(newTableName string) *appleDevice {
	a.appleDeviceDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a appleDevice) As(alias string) *appleDevice {
	a.appleDeviceDo.DO = *(a.appleDeviceDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *appleDevice) updateTableName(table string) *appleDevice {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt(table, "id")
	a.AppID = field.NewInt(table, "app_id")
	a.UserID = field.NewInt(table, "user_id")
	a.InAppleID = field.NewString(table, "in_apple_id")
	a.Udid = field.NewString(table, "udid")
	a.Model = field.NewString(table, "model")
	a.Remark = field.NewString(table, "remark")
	a.Platform = field.NewString(table, "platform")
	a.Status = field.NewInt(table, "status")
	a.CreatedTime = field.NewTime(table, "created_time")
	a.UpdatedTime = field.NewTime(table, "updated_time")

	a.fillFieldMap()

	return a
}

func (a *appleDevice) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *appleDevice) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 11)
	a.fieldMap["id"] = a.ID
	a.fieldMap["app_id"] = a.AppID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["in_apple_id"] = a.InAppleID
	a.fieldMap["udid"] = a.Udid
	a.fieldMap["model"] = a.Model
	a.fieldMap["remark"] = a.Remark
	a.fieldMap["platform"] = a.Platform
	a.fieldMap["status"] = a.Status
	a.fieldMap["created_time"] = a.CreatedTime
	a.fieldMap["updated_time"] = a.UpdatedTime
}

func (a appleDevice) clone(db *gorm.DB) appleDevice {
	a.appleDeviceDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a appleDevice) replaceDB(db *gorm.DB) appleDevice {
	a.appleDeviceDo.ReplaceDB(db)
	return a
}

type appleDeviceDo struct{ gen.DO }

type IAppleDeviceDo interface {
	gen.SubQuery
	Debug() IAppleDeviceDo
	WithContext(ctx context.Context) IAppleDeviceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAppleDeviceDo
	WriteDB() IAppleDeviceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAppleDeviceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAppleDeviceDo
	Not(conds ...gen.Condition) IAppleDeviceDo
	Or(conds ...gen.Condition) IAppleDeviceDo
	Select(conds ...field.Expr) IAppleDeviceDo
	Where(conds ...gen.Condition) IAppleDeviceDo
	Order(conds ...field.Expr) IAppleDeviceDo
	Distinct(cols ...field.Expr) IAppleDeviceDo
	Omit(cols ...field.Expr) IAppleDeviceDo
	Join(table schema.Tabler, on ...field.Expr) IAppleDeviceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAppleDeviceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAppleDeviceDo
	Group(cols ...field.Expr) IAppleDeviceDo
	Having(conds ...gen.Condition) IAppleDeviceDo
	Limit(limit int) IAppleDeviceDo
	Offset(offset int) IAppleDeviceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAppleDeviceDo
	Unscoped() IAppleDeviceDo
	Create(values ...*model.AppleDevice) error
	CreateInBatches(values []*model.AppleDevice, batchSize int) error
	Save(values ...*model.AppleDevice) error
	First() (*model.AppleDevice, error)
	Take() (*model.AppleDevice, error)
	Last() (*model.AppleDevice, error)
	Find() ([]*model.AppleDevice, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AppleDevice, err error)
	FindInBatches(result *[]*model.AppleDevice, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AppleDevice) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAppleDeviceDo
	Assign(attrs ...field.AssignExpr) IAppleDeviceDo
	Joins(fields ...field.RelationField) IAppleDeviceDo
	Preload(fields ...field.RelationField) IAppleDeviceDo
	FirstOrInit() (*model.AppleDevice, error)
	FirstOrCreate() (*model.AppleDevice, error)
	FindByPage(offset int, limit int) (result []*model.AppleDevice, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAppleDeviceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a appleDeviceDo) Debug() IAppleDeviceDo {
	return a.withDO(a.DO.Debug())
}

func (a appleDeviceDo) WithContext(ctx context.Context) IAppleDeviceDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a appleDeviceDo) ReadDB() IAppleDeviceDo {
	return a.Clauses(dbresolver.Read)
}

func (a appleDeviceDo) WriteDB() IAppleDeviceDo {
	return a.Clauses(dbresolver.Write)
}

func (a appleDeviceDo) Session(config *gorm.Session) IAppleDeviceDo {
	return a.withDO(a.DO.Session(config))
}

func (a appleDeviceDo) Clauses(conds ...clause.Expression) IAppleDeviceDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a appleDeviceDo) Returning(value interface{}, columns ...string) IAppleDeviceDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a appleDeviceDo) Not(conds ...gen.Condition) IAppleDeviceDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a appleDeviceDo) Or(conds ...gen.Condition) IAppleDeviceDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a appleDeviceDo) Select(conds ...field.Expr) IAppleDeviceDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a appleDeviceDo) Where(conds ...gen.Condition) IAppleDeviceDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a appleDeviceDo) Order(conds ...field.Expr) IAppleDeviceDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a appleDeviceDo) Distinct(cols ...field.Expr) IAppleDeviceDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a appleDeviceDo) Omit(cols ...field.Expr) IAppleDeviceDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a appleDeviceDo) Join(table schema.Tabler, on ...field.Expr) IAppleDeviceDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a appleDeviceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAppleDeviceDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a appleDeviceDo) RightJoin(table schema.Tabler, on ...field.Expr) IAppleDeviceDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a appleDeviceDo) Group(cols ...field.Expr) IAppleDeviceDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a appleDeviceDo) Having(conds ...gen.Condition) IAppleDeviceDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a appleDeviceDo) Limit(limit int) IAppleDeviceDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a appleDeviceDo) Offset(offset int) IAppleDeviceDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a appleDeviceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAppleDeviceDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a appleDeviceDo) Unscoped() IAppleDeviceDo {
	return a.withDO(a.DO.Unscoped())
}

func (a appleDeviceDo) Create(values ...*model.AppleDevice) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a appleDeviceDo) CreateInBatches(values []*model.AppleDevice, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a appleDeviceDo) Save(values ...*model.AppleDevice) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a appleDeviceDo) First() (*model.AppleDevice, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleDevice), nil
	}
}

func (a appleDeviceDo) Take() (*model.AppleDevice, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleDevice), nil
	}
}

func (a appleDeviceDo) Last() (*model.AppleDevice, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleDevice), nil
	}
}

func (a appleDeviceDo) Find() ([]*model.AppleDevice, error) {
	result, err := a.DO.Find()
	return result.([]*model.AppleDevice), err
}

func (a appleDeviceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AppleDevice, err error) {
	buf := make([]*model.AppleDevice, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a appleDeviceDo) FindInBatches(result *[]*model.AppleDevice, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a appleDeviceDo) Attrs(attrs ...field.AssignExpr) IAppleDeviceDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a appleDeviceDo) Assign(attrs ...field.AssignExpr) IAppleDeviceDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a appleDeviceDo) Joins(fields ...field.RelationField) IAppleDeviceDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a appleDeviceDo) Preload(fields ...field.RelationField) IAppleDeviceDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a appleDeviceDo) FirstOrInit() (*model.AppleDevice, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleDevice), nil
	}
}

func (a appleDeviceDo) FirstOrCreate() (*model.AppleDevice, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleDevice), nil
	}
}

func (a appleDeviceDo) FindByPage(offset int, limit int) (result []*model.AppleDevice, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a appleDeviceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a appleDeviceDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a appleDeviceDo) Delete(models ...*model.AppleDevice) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *appleDeviceDo) withDO(do gen.Dao) *appleDeviceDo {
	a.DO = *do.(*gen.DO)
	return a
}
