// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/ivfzhou/csms/comm/model"
)

func newAppleBundleID(db *gorm.DB, opts ...gen.DOOption) appleBundleID {
	_appleBundleID := appleBundleID{}

	_appleBundleID.appleBundleIDDo.UseDB(db, opts...)
	_appleBundleID.appleBundleIDDo.UseModel(&model.AppleBundleID{})

	tableName := _appleBundleID.appleBundleIDDo.TableName()
	_appleBundleID.ALL = field.NewAsterisk(tableName)
	_appleBundleID.ID = field.NewInt(tableName, "id")
	_appleBundleID.AppID = field.NewInt(tableName, "app_id")
	_appleBundleID.UserID = field.NewInt(tableName, "user_id")
	_appleBundleID.InAppleID = field.NewString(tableName, "in_apple_id")
	_appleBundleID.BundleID = field.NewString(tableName, "bundle_id")
	_appleBundleID.Environment = field.NewInt(tableName, "environment")
	_appleBundleID.Platform = field.NewInt(tableName, "platform")
	_appleBundleID.Capabilities = field.NewField(tableName, "capabilities")
	_appleBundleID.CreatedTime = field.NewTime(tableName, "created_time")
	_appleBundleID.UpdatedTime = field.NewTime(tableName, "updated_time")

	_appleBundleID.fillFieldMap()

	return _appleBundleID
}

// appleBundleID BundleID 信息表
type appleBundleID struct {
	appleBundleIDDo

	ALL          field.Asterisk
	ID           field.Int    // 自增主码
	AppID        field.Int    // 所属应用 ID
	UserID       field.Int    // 申请人 ID
	InAppleID    field.String // 在苹果服务中的 ID
	BundleID     field.String // Apple 应用唯一标识，域名倒置点号分隔的形式
	Environment  field.Int    // 环境，1=AppStore，2=企业内测
	Platform     field.Int    // 平台，1=IOS、2=MAC_OS、3=UNIVERSAL
	Capabilities field.Field  // BundleID 的能力项，以英文逗号分隔
	CreatedTime  field.Time   // 创建时间
	UpdatedTime  field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (a appleBundleID) Table(newTableName string) *appleBundleID {
	a.appleBundleIDDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a appleBundleID) As(alias string) *appleBundleID {
	a.appleBundleIDDo.DO = *(a.appleBundleIDDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *appleBundleID) updateTableName(table string) *appleBundleID {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt(table, "id")
	a.AppID = field.NewInt(table, "app_id")
	a.UserID = field.NewInt(table, "user_id")
	a.InAppleID = field.NewString(table, "in_apple_id")
	a.BundleID = field.NewString(table, "bundle_id")
	a.Environment = field.NewInt(table, "environment")
	a.Platform = field.NewInt(table, "platform")
	a.Capabilities = field.NewField(table, "capabilities")
	a.CreatedTime = field.NewTime(table, "created_time")
	a.UpdatedTime = field.NewTime(table, "updated_time")

	a.fillFieldMap()

	return a
}

func (a *appleBundleID) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *appleBundleID) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["app_id"] = a.AppID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["in_apple_id"] = a.InAppleID
	a.fieldMap["bundle_id"] = a.BundleID
	a.fieldMap["environment"] = a.Environment
	a.fieldMap["platform"] = a.Platform
	a.fieldMap["capabilities"] = a.Capabilities
	a.fieldMap["created_time"] = a.CreatedTime
	a.fieldMap["updated_time"] = a.UpdatedTime
}

func (a appleBundleID) clone(db *gorm.DB) appleBundleID {
	a.appleBundleIDDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a appleBundleID) replaceDB(db *gorm.DB) appleBundleID {
	a.appleBundleIDDo.ReplaceDB(db)
	return a
}

type appleBundleIDDo struct{ gen.DO }

type IAppleBundleIDDo interface {
	gen.SubQuery
	Debug() IAppleBundleIDDo
	WithContext(ctx context.Context) IAppleBundleIDDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAppleBundleIDDo
	WriteDB() IAppleBundleIDDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAppleBundleIDDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAppleBundleIDDo
	Not(conds ...gen.Condition) IAppleBundleIDDo
	Or(conds ...gen.Condition) IAppleBundleIDDo
	Select(conds ...field.Expr) IAppleBundleIDDo
	Where(conds ...gen.Condition) IAppleBundleIDDo
	Order(conds ...field.Expr) IAppleBundleIDDo
	Distinct(cols ...field.Expr) IAppleBundleIDDo
	Omit(cols ...field.Expr) IAppleBundleIDDo
	Join(table schema.Tabler, on ...field.Expr) IAppleBundleIDDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAppleBundleIDDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAppleBundleIDDo
	Group(cols ...field.Expr) IAppleBundleIDDo
	Having(conds ...gen.Condition) IAppleBundleIDDo
	Limit(limit int) IAppleBundleIDDo
	Offset(offset int) IAppleBundleIDDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAppleBundleIDDo
	Unscoped() IAppleBundleIDDo
	Create(values ...*model.AppleBundleID) error
	CreateInBatches(values []*model.AppleBundleID, batchSize int) error
	Save(values ...*model.AppleBundleID) error
	First() (*model.AppleBundleID, error)
	Take() (*model.AppleBundleID, error)
	Last() (*model.AppleBundleID, error)
	Find() ([]*model.AppleBundleID, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AppleBundleID, err error)
	FindInBatches(result *[]*model.AppleBundleID, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AppleBundleID) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAppleBundleIDDo
	Assign(attrs ...field.AssignExpr) IAppleBundleIDDo
	Joins(fields ...field.RelationField) IAppleBundleIDDo
	Preload(fields ...field.RelationField) IAppleBundleIDDo
	FirstOrInit() (*model.AppleBundleID, error)
	FirstOrCreate() (*model.AppleBundleID, error)
	FindByPage(offset int, limit int) (result []*model.AppleBundleID, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAppleBundleIDDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a appleBundleIDDo) Debug() IAppleBundleIDDo {
	return a.withDO(a.DO.Debug())
}

func (a appleBundleIDDo) WithContext(ctx context.Context) IAppleBundleIDDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a appleBundleIDDo) ReadDB() IAppleBundleIDDo {
	return a.Clauses(dbresolver.Read)
}

func (a appleBundleIDDo) WriteDB() IAppleBundleIDDo {
	return a.Clauses(dbresolver.Write)
}

func (a appleBundleIDDo) Session(config *gorm.Session) IAppleBundleIDDo {
	return a.withDO(a.DO.Session(config))
}

func (a appleBundleIDDo) Clauses(conds ...clause.Expression) IAppleBundleIDDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a appleBundleIDDo) Returning(value interface{}, columns ...string) IAppleBundleIDDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a appleBundleIDDo) Not(conds ...gen.Condition) IAppleBundleIDDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a appleBundleIDDo) Or(conds ...gen.Condition) IAppleBundleIDDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a appleBundleIDDo) Select(conds ...field.Expr) IAppleBundleIDDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a appleBundleIDDo) Where(conds ...gen.Condition) IAppleBundleIDDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a appleBundleIDDo) Order(conds ...field.Expr) IAppleBundleIDDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a appleBundleIDDo) Distinct(cols ...field.Expr) IAppleBundleIDDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a appleBundleIDDo) Omit(cols ...field.Expr) IAppleBundleIDDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a appleBundleIDDo) Join(table schema.Tabler, on ...field.Expr) IAppleBundleIDDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a appleBundleIDDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAppleBundleIDDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a appleBundleIDDo) RightJoin(table schema.Tabler, on ...field.Expr) IAppleBundleIDDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a appleBundleIDDo) Group(cols ...field.Expr) IAppleBundleIDDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a appleBundleIDDo) Having(conds ...gen.Condition) IAppleBundleIDDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a appleBundleIDDo) Limit(limit int) IAppleBundleIDDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a appleBundleIDDo) Offset(offset int) IAppleBundleIDDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a appleBundleIDDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAppleBundleIDDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a appleBundleIDDo) Unscoped() IAppleBundleIDDo {
	return a.withDO(a.DO.Unscoped())
}

func (a appleBundleIDDo) Create(values ...*model.AppleBundleID) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a appleBundleIDDo) CreateInBatches(values []*model.AppleBundleID, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a appleBundleIDDo) Save(values ...*model.AppleBundleID) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a appleBundleIDDo) First() (*model.AppleBundleID, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleBundleID), nil
	}
}

func (a appleBundleIDDo) Take() (*model.AppleBundleID, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleBundleID), nil
	}
}

func (a appleBundleIDDo) Last() (*model.AppleBundleID, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleBundleID), nil
	}
}

func (a appleBundleIDDo) Find() ([]*model.AppleBundleID, error) {
	result, err := a.DO.Find()
	return result.([]*model.AppleBundleID), err
}

func (a appleBundleIDDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AppleBundleID, err error) {
	buf := make([]*model.AppleBundleID, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a appleBundleIDDo) FindInBatches(result *[]*model.AppleBundleID, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a appleBundleIDDo) Attrs(attrs ...field.AssignExpr) IAppleBundleIDDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a appleBundleIDDo) Assign(attrs ...field.AssignExpr) IAppleBundleIDDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a appleBundleIDDo) Joins(fields ...field.RelationField) IAppleBundleIDDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a appleBundleIDDo) Preload(fields ...field.RelationField) IAppleBundleIDDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a appleBundleIDDo) FirstOrInit() (*model.AppleBundleID, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleBundleID), nil
	}
}

func (a appleBundleIDDo) FirstOrCreate() (*model.AppleBundleID, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleBundleID), nil
	}
}

func (a appleBundleIDDo) FindByPage(offset int, limit int) (result []*model.AppleBundleID, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a appleBundleIDDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a appleBundleIDDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a appleBundleIDDo) Delete(models ...*model.AppleBundleID) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *appleBundleIDDo) withDO(do gen.Dao) *appleBundleIDDo {
	a.DO = *do.(*gen.DO)
	return a
}
