// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/ivfzhou/csms/comm/model"
)

func newAppleCertificate(db *gorm.DB, opts ...gen.DOOption) appleCertificate {
	_appleCertificate := appleCertificate{}

	_appleCertificate.appleCertificateDo.UseDB(db, opts...)
	_appleCertificate.appleCertificateDo.UseModel(&model.AppleCertificate{})

	tableName := _appleCertificate.appleCertificateDo.TableName()
	_appleCertificate.ALL = field.NewAsterisk(tableName)
	_appleCertificate.ID = field.NewInt(tableName, "id")
	_appleCertificate.CertificateID = field.NewString(tableName, "certificate_id")
	_appleCertificate.AppID = field.NewInt(tableName, "app_id")
	_appleCertificate.UserID = field.NewInt(tableName, "user_id")
	_appleCertificate.InAppleID = field.NewString(tableName, "in_apple_id")
	_appleCertificate.Environment = field.NewInt(tableName, "environment")
	_appleCertificate.BundleID = field.NewInt(tableName, "bundle_id")
	_appleCertificate.Category = field.NewInt(tableName, "category")
	_appleCertificate.Type = field.NewString(tableName, "type")
	_appleCertificate.Password = field.NewString(tableName, "password")
	_appleCertificate.Publisher = field.NewString(tableName, "publisher")
	_appleCertificate.Owner = field.NewString(tableName, "owner")
	_appleCertificate.SignatureAlgorithm = field.NewString(tableName, "signature_algorithm")
	_appleCertificate.PublicKeyAlgorithm = field.NewString(tableName, "public_key_algorithm")
	_appleCertificate.SerialNumber = field.NewString(tableName, "serial_number")
	_appleCertificate.NotBefore = field.NewTime(tableName, "not_before")
	_appleCertificate.AesKeyID = field.NewInt(tableName, "aes_key_id")
	_appleCertificate.NotAfter = field.NewTime(tableName, "not_after")
	_appleCertificate.Content = field.NewBytes(tableName, "content")
	_appleCertificate.CreatedTime = field.NewTime(tableName, "created_time")
	_appleCertificate.DeletedTime = field.NewTime(tableName, "deleted_time")

	_appleCertificate.fillFieldMap()

	return _appleCertificate
}

// appleCertificate 苹果相关证书信息表
type appleCertificate struct {
	appleCertificateDo

	ALL                field.Asterisk
	ID                 field.Int    // 自增主码
	CertificateID      field.String // 唯一标识
	AppID              field.Int    // Push 证书所属应用 ID
	UserID             field.Int    // 创建人 ID
	InAppleID          field.String // 在苹果服务器的 ID
	Environment        field.Int    // Push 证书环境，1=正式、2=开发、3=企业内测
	BundleID           field.Int    // Push 证书对应的 BundleID
	Category           field.Int    // 文件类型，1=签名证书、2=Push 证书
	Type               field.String // 签名证书类型，由苹果 API 中定义，例如：IOS_DEVELOPMENT
	Password           field.String // 密码
	Publisher          field.String // 颁发者
	Owner              field.String // 所有者
	SignatureAlgorithm field.String // 签名算法
	PublicKeyAlgorithm field.String // 公钥密码算法
	SerialNumber       field.String // 序列号
	NotBefore          field.Time   // 生效时间
	AesKeyID           field.Int    // 证书加密密钥 ID
	NotAfter           field.Time   // 失效时间
	Content            field.Bytes  // 加密了的证书内容
	CreatedTime        field.Time   // 创建时间
	DeletedTime        field.Time   // 删除时间

	fieldMap map[string]field.Expr
}

func (a appleCertificate) Table(newTableName string) *appleCertificate {
	a.appleCertificateDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a appleCertificate) As(alias string) *appleCertificate {
	a.appleCertificateDo.DO = *(a.appleCertificateDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *appleCertificate) updateTableName(table string) *appleCertificate {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt(table, "id")
	a.CertificateID = field.NewString(table, "certificate_id")
	a.AppID = field.NewInt(table, "app_id")
	a.UserID = field.NewInt(table, "user_id")
	a.InAppleID = field.NewString(table, "in_apple_id")
	a.Environment = field.NewInt(table, "environment")
	a.BundleID = field.NewInt(table, "bundle_id")
	a.Category = field.NewInt(table, "category")
	a.Type = field.NewString(table, "type")
	a.Password = field.NewString(table, "password")
	a.Publisher = field.NewString(table, "publisher")
	a.Owner = field.NewString(table, "owner")
	a.SignatureAlgorithm = field.NewString(table, "signature_algorithm")
	a.PublicKeyAlgorithm = field.NewString(table, "public_key_algorithm")
	a.SerialNumber = field.NewString(table, "serial_number")
	a.NotBefore = field.NewTime(table, "not_before")
	a.AesKeyID = field.NewInt(table, "aes_key_id")
	a.NotAfter = field.NewTime(table, "not_after")
	a.Content = field.NewBytes(table, "content")
	a.CreatedTime = field.NewTime(table, "created_time")
	a.DeletedTime = field.NewTime(table, "deleted_time")

	a.fillFieldMap()

	return a
}

func (a *appleCertificate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *appleCertificate) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 21)
	a.fieldMap["id"] = a.ID
	a.fieldMap["certificate_id"] = a.CertificateID
	a.fieldMap["app_id"] = a.AppID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["in_apple_id"] = a.InAppleID
	a.fieldMap["environment"] = a.Environment
	a.fieldMap["bundle_id"] = a.BundleID
	a.fieldMap["category"] = a.Category
	a.fieldMap["type"] = a.Type
	a.fieldMap["password"] = a.Password
	a.fieldMap["publisher"] = a.Publisher
	a.fieldMap["owner"] = a.Owner
	a.fieldMap["signature_algorithm"] = a.SignatureAlgorithm
	a.fieldMap["public_key_algorithm"] = a.PublicKeyAlgorithm
	a.fieldMap["serial_number"] = a.SerialNumber
	a.fieldMap["not_before"] = a.NotBefore
	a.fieldMap["aes_key_id"] = a.AesKeyID
	a.fieldMap["not_after"] = a.NotAfter
	a.fieldMap["content"] = a.Content
	a.fieldMap["created_time"] = a.CreatedTime
	a.fieldMap["deleted_time"] = a.DeletedTime
}

func (a appleCertificate) clone(db *gorm.DB) appleCertificate {
	a.appleCertificateDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a appleCertificate) replaceDB(db *gorm.DB) appleCertificate {
	a.appleCertificateDo.ReplaceDB(db)
	return a
}

type appleCertificateDo struct{ gen.DO }

type IAppleCertificateDo interface {
	gen.SubQuery
	Debug() IAppleCertificateDo
	WithContext(ctx context.Context) IAppleCertificateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAppleCertificateDo
	WriteDB() IAppleCertificateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAppleCertificateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAppleCertificateDo
	Not(conds ...gen.Condition) IAppleCertificateDo
	Or(conds ...gen.Condition) IAppleCertificateDo
	Select(conds ...field.Expr) IAppleCertificateDo
	Where(conds ...gen.Condition) IAppleCertificateDo
	Order(conds ...field.Expr) IAppleCertificateDo
	Distinct(cols ...field.Expr) IAppleCertificateDo
	Omit(cols ...field.Expr) IAppleCertificateDo
	Join(table schema.Tabler, on ...field.Expr) IAppleCertificateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAppleCertificateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAppleCertificateDo
	Group(cols ...field.Expr) IAppleCertificateDo
	Having(conds ...gen.Condition) IAppleCertificateDo
	Limit(limit int) IAppleCertificateDo
	Offset(offset int) IAppleCertificateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAppleCertificateDo
	Unscoped() IAppleCertificateDo
	Create(values ...*model.AppleCertificate) error
	CreateInBatches(values []*model.AppleCertificate, batchSize int) error
	Save(values ...*model.AppleCertificate) error
	First() (*model.AppleCertificate, error)
	Take() (*model.AppleCertificate, error)
	Last() (*model.AppleCertificate, error)
	Find() ([]*model.AppleCertificate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AppleCertificate, err error)
	FindInBatches(result *[]*model.AppleCertificate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AppleCertificate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAppleCertificateDo
	Assign(attrs ...field.AssignExpr) IAppleCertificateDo
	Joins(fields ...field.RelationField) IAppleCertificateDo
	Preload(fields ...field.RelationField) IAppleCertificateDo
	FirstOrInit() (*model.AppleCertificate, error)
	FirstOrCreate() (*model.AppleCertificate, error)
	FindByPage(offset int, limit int) (result []*model.AppleCertificate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAppleCertificateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a appleCertificateDo) Debug() IAppleCertificateDo {
	return a.withDO(a.DO.Debug())
}

func (a appleCertificateDo) WithContext(ctx context.Context) IAppleCertificateDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a appleCertificateDo) ReadDB() IAppleCertificateDo {
	return a.Clauses(dbresolver.Read)
}

func (a appleCertificateDo) WriteDB() IAppleCertificateDo {
	return a.Clauses(dbresolver.Write)
}

func (a appleCertificateDo) Session(config *gorm.Session) IAppleCertificateDo {
	return a.withDO(a.DO.Session(config))
}

func (a appleCertificateDo) Clauses(conds ...clause.Expression) IAppleCertificateDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a appleCertificateDo) Returning(value interface{}, columns ...string) IAppleCertificateDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a appleCertificateDo) Not(conds ...gen.Condition) IAppleCertificateDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a appleCertificateDo) Or(conds ...gen.Condition) IAppleCertificateDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a appleCertificateDo) Select(conds ...field.Expr) IAppleCertificateDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a appleCertificateDo) Where(conds ...gen.Condition) IAppleCertificateDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a appleCertificateDo) Order(conds ...field.Expr) IAppleCertificateDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a appleCertificateDo) Distinct(cols ...field.Expr) IAppleCertificateDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a appleCertificateDo) Omit(cols ...field.Expr) IAppleCertificateDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a appleCertificateDo) Join(table schema.Tabler, on ...field.Expr) IAppleCertificateDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a appleCertificateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAppleCertificateDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a appleCertificateDo) RightJoin(table schema.Tabler, on ...field.Expr) IAppleCertificateDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a appleCertificateDo) Group(cols ...field.Expr) IAppleCertificateDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a appleCertificateDo) Having(conds ...gen.Condition) IAppleCertificateDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a appleCertificateDo) Limit(limit int) IAppleCertificateDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a appleCertificateDo) Offset(offset int) IAppleCertificateDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a appleCertificateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAppleCertificateDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a appleCertificateDo) Unscoped() IAppleCertificateDo {
	return a.withDO(a.DO.Unscoped())
}

func (a appleCertificateDo) Create(values ...*model.AppleCertificate) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a appleCertificateDo) CreateInBatches(values []*model.AppleCertificate, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a appleCertificateDo) Save(values ...*model.AppleCertificate) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a appleCertificateDo) First() (*model.AppleCertificate, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleCertificate), nil
	}
}

func (a appleCertificateDo) Take() (*model.AppleCertificate, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleCertificate), nil
	}
}

func (a appleCertificateDo) Last() (*model.AppleCertificate, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleCertificate), nil
	}
}

func (a appleCertificateDo) Find() ([]*model.AppleCertificate, error) {
	result, err := a.DO.Find()
	return result.([]*model.AppleCertificate), err
}

func (a appleCertificateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AppleCertificate, err error) {
	buf := make([]*model.AppleCertificate, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a appleCertificateDo) FindInBatches(result *[]*model.AppleCertificate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a appleCertificateDo) Attrs(attrs ...field.AssignExpr) IAppleCertificateDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a appleCertificateDo) Assign(attrs ...field.AssignExpr) IAppleCertificateDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a appleCertificateDo) Joins(fields ...field.RelationField) IAppleCertificateDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a appleCertificateDo) Preload(fields ...field.RelationField) IAppleCertificateDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a appleCertificateDo) FirstOrInit() (*model.AppleCertificate, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleCertificate), nil
	}
}

func (a appleCertificateDo) FirstOrCreate() (*model.AppleCertificate, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleCertificate), nil
	}
}

func (a appleCertificateDo) FindByPage(offset int, limit int) (result []*model.AppleCertificate, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a appleCertificateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a appleCertificateDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a appleCertificateDo) Delete(models ...*model.AppleCertificate) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *appleCertificateDo) withDO(do gen.Dao) *appleCertificateDo {
	a.DO = *do.(*gen.DO)
	return a
}
