// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/ivfzhou/csms/comm/model"
)

func newAppleProfile(db *gorm.DB, opts ...gen.DOOption) appleProfile {
	_appleProfile := appleProfile{}

	_appleProfile.appleProfileDo.UseDB(db, opts...)
	_appleProfile.appleProfileDo.UseModel(&model.AppleProfile{})

	tableName := _appleProfile.appleProfileDo.TableName()
	_appleProfile.ALL = field.NewAsterisk(tableName)
	_appleProfile.ID = field.NewInt(tableName, "id")
	_appleProfile.ProfileID = field.NewString(tableName, "profile_id")
	_appleProfile.AppID = field.NewInt(tableName, "app_id")
	_appleProfile.UserID = field.NewInt(tableName, "user_id")
	_appleProfile.CertificateID = field.NewInt(tableName, "certificate_id")
	_appleProfile.InAppleID = field.NewString(tableName, "in_apple_id")
	_appleProfile.BundleID = field.NewInt(tableName, "bundle_id")
	_appleProfile.Text = field.NewString(tableName, "text")
	_appleProfile.Type = field.NewString(tableName, "type")
	_appleProfile.NotBefore = field.NewTime(tableName, "not_before")
	_appleProfile.NotAfter = field.NewTime(tableName, "not_after")
	_appleProfile.Content = field.NewBytes(tableName, "content")
	_appleProfile.CreatedTime = field.NewTime(tableName, "created_time")
	_appleProfile.DeletedTime = field.NewTime(tableName, "deleted_time")

	_appleProfile.fillFieldMap()

	return _appleProfile
}

// appleProfile 苹果描述文件信息表
type appleProfile struct {
	appleProfileDo

	ALL           field.Asterisk
	ID            field.Int    // 自增主码
	ProfileID     field.String // 唯一标识
	AppID         field.Int    // 所属应用 ID
	UserID        field.Int    // 创建人 ID
	CertificateID field.Int    // 证书表 ID，根据该证书申请的描述文件
	InAppleID     field.String // 在苹果服务器的 ID
	BundleID      field.Int    // 描述文件对应的 BundleID
	Text          field.String // 描述文件中的 XML 内容
	Type          field.String // 描述文件类型，由苹果 API 中定义，例如：IOS_APP_STORE
	NotBefore     field.Time   // 生效时间
	NotAfter      field.Time   // 失效时间
	Content       field.Bytes  // 描述文件的内容
	CreatedTime   field.Time   // 创建时间
	DeletedTime   field.Time   // 删除时间

	fieldMap map[string]field.Expr
}

func (a appleProfile) Table(newTableName string) *appleProfile {
	a.appleProfileDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a appleProfile) As(alias string) *appleProfile {
	a.appleProfileDo.DO = *(a.appleProfileDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *appleProfile) updateTableName(table string) *appleProfile {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt(table, "id")
	a.ProfileID = field.NewString(table, "profile_id")
	a.AppID = field.NewInt(table, "app_id")
	a.UserID = field.NewInt(table, "user_id")
	a.CertificateID = field.NewInt(table, "certificate_id")
	a.InAppleID = field.NewString(table, "in_apple_id")
	a.BundleID = field.NewInt(table, "bundle_id")
	a.Text = field.NewString(table, "text")
	a.Type = field.NewString(table, "type")
	a.NotBefore = field.NewTime(table, "not_before")
	a.NotAfter = field.NewTime(table, "not_after")
	a.Content = field.NewBytes(table, "content")
	a.CreatedTime = field.NewTime(table, "created_time")
	a.DeletedTime = field.NewTime(table, "deleted_time")

	a.fillFieldMap()

	return a
}

func (a *appleProfile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *appleProfile) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 14)
	a.fieldMap["id"] = a.ID
	a.fieldMap["profile_id"] = a.ProfileID
	a.fieldMap["app_id"] = a.AppID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["certificate_id"] = a.CertificateID
	a.fieldMap["in_apple_id"] = a.InAppleID
	a.fieldMap["bundle_id"] = a.BundleID
	a.fieldMap["text"] = a.Text
	a.fieldMap["type"] = a.Type
	a.fieldMap["not_before"] = a.NotBefore
	a.fieldMap["not_after"] = a.NotAfter
	a.fieldMap["content"] = a.Content
	a.fieldMap["created_time"] = a.CreatedTime
	a.fieldMap["deleted_time"] = a.DeletedTime
}

func (a appleProfile) clone(db *gorm.DB) appleProfile {
	a.appleProfileDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a appleProfile) replaceDB(db *gorm.DB) appleProfile {
	a.appleProfileDo.ReplaceDB(db)
	return a
}

type appleProfileDo struct{ gen.DO }

type IAppleProfileDo interface {
	gen.SubQuery
	Debug() IAppleProfileDo
	WithContext(ctx context.Context) IAppleProfileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAppleProfileDo
	WriteDB() IAppleProfileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAppleProfileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAppleProfileDo
	Not(conds ...gen.Condition) IAppleProfileDo
	Or(conds ...gen.Condition) IAppleProfileDo
	Select(conds ...field.Expr) IAppleProfileDo
	Where(conds ...gen.Condition) IAppleProfileDo
	Order(conds ...field.Expr) IAppleProfileDo
	Distinct(cols ...field.Expr) IAppleProfileDo
	Omit(cols ...field.Expr) IAppleProfileDo
	Join(table schema.Tabler, on ...field.Expr) IAppleProfileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAppleProfileDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAppleProfileDo
	Group(cols ...field.Expr) IAppleProfileDo
	Having(conds ...gen.Condition) IAppleProfileDo
	Limit(limit int) IAppleProfileDo
	Offset(offset int) IAppleProfileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAppleProfileDo
	Unscoped() IAppleProfileDo
	Create(values ...*model.AppleProfile) error
	CreateInBatches(values []*model.AppleProfile, batchSize int) error
	Save(values ...*model.AppleProfile) error
	First() (*model.AppleProfile, error)
	Take() (*model.AppleProfile, error)
	Last() (*model.AppleProfile, error)
	Find() ([]*model.AppleProfile, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AppleProfile, err error)
	FindInBatches(result *[]*model.AppleProfile, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AppleProfile) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAppleProfileDo
	Assign(attrs ...field.AssignExpr) IAppleProfileDo
	Joins(fields ...field.RelationField) IAppleProfileDo
	Preload(fields ...field.RelationField) IAppleProfileDo
	FirstOrInit() (*model.AppleProfile, error)
	FirstOrCreate() (*model.AppleProfile, error)
	FindByPage(offset int, limit int) (result []*model.AppleProfile, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAppleProfileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a appleProfileDo) Debug() IAppleProfileDo {
	return a.withDO(a.DO.Debug())
}

func (a appleProfileDo) WithContext(ctx context.Context) IAppleProfileDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a appleProfileDo) ReadDB() IAppleProfileDo {
	return a.Clauses(dbresolver.Read)
}

func (a appleProfileDo) WriteDB() IAppleProfileDo {
	return a.Clauses(dbresolver.Write)
}

func (a appleProfileDo) Session(config *gorm.Session) IAppleProfileDo {
	return a.withDO(a.DO.Session(config))
}

func (a appleProfileDo) Clauses(conds ...clause.Expression) IAppleProfileDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a appleProfileDo) Returning(value interface{}, columns ...string) IAppleProfileDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a appleProfileDo) Not(conds ...gen.Condition) IAppleProfileDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a appleProfileDo) Or(conds ...gen.Condition) IAppleProfileDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a appleProfileDo) Select(conds ...field.Expr) IAppleProfileDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a appleProfileDo) Where(conds ...gen.Condition) IAppleProfileDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a appleProfileDo) Order(conds ...field.Expr) IAppleProfileDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a appleProfileDo) Distinct(cols ...field.Expr) IAppleProfileDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a appleProfileDo) Omit(cols ...field.Expr) IAppleProfileDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a appleProfileDo) Join(table schema.Tabler, on ...field.Expr) IAppleProfileDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a appleProfileDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAppleProfileDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a appleProfileDo) RightJoin(table schema.Tabler, on ...field.Expr) IAppleProfileDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a appleProfileDo) Group(cols ...field.Expr) IAppleProfileDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a appleProfileDo) Having(conds ...gen.Condition) IAppleProfileDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a appleProfileDo) Limit(limit int) IAppleProfileDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a appleProfileDo) Offset(offset int) IAppleProfileDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a appleProfileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAppleProfileDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a appleProfileDo) Unscoped() IAppleProfileDo {
	return a.withDO(a.DO.Unscoped())
}

func (a appleProfileDo) Create(values ...*model.AppleProfile) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a appleProfileDo) CreateInBatches(values []*model.AppleProfile, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a appleProfileDo) Save(values ...*model.AppleProfile) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a appleProfileDo) First() (*model.AppleProfile, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleProfile), nil
	}
}

func (a appleProfileDo) Take() (*model.AppleProfile, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleProfile), nil
	}
}

func (a appleProfileDo) Last() (*model.AppleProfile, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleProfile), nil
	}
}

func (a appleProfileDo) Find() ([]*model.AppleProfile, error) {
	result, err := a.DO.Find()
	return result.([]*model.AppleProfile), err
}

func (a appleProfileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AppleProfile, err error) {
	buf := make([]*model.AppleProfile, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a appleProfileDo) FindInBatches(result *[]*model.AppleProfile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a appleProfileDo) Attrs(attrs ...field.AssignExpr) IAppleProfileDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a appleProfileDo) Assign(attrs ...field.AssignExpr) IAppleProfileDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a appleProfileDo) Joins(fields ...field.RelationField) IAppleProfileDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a appleProfileDo) Preload(fields ...field.RelationField) IAppleProfileDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a appleProfileDo) FirstOrInit() (*model.AppleProfile, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleProfile), nil
	}
}

func (a appleProfileDo) FirstOrCreate() (*model.AppleProfile, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppleProfile), nil
	}
}

func (a appleProfileDo) FindByPage(offset int, limit int) (result []*model.AppleProfile, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a appleProfileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a appleProfileDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a appleProfileDo) Delete(models ...*model.AppleProfile) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *appleProfileDo) withDO(do gen.Dao) *appleProfileDo {
	a.DO = *do.(*gen.DO)
	return a
}
