// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/ivfzhou/csms/comm/model"
)

func newAPIAuthorization(db *gorm.DB, opts ...gen.DOOption) aPIAuthorization {
	_aPIAuthorization := aPIAuthorization{}

	_aPIAuthorization.aPIAuthorizationDo.UseDB(db, opts...)
	_aPIAuthorization.aPIAuthorizationDo.UseModel(&model.APIAuthorization{})

	tableName := _aPIAuthorization.aPIAuthorizationDo.TableName()
	_aPIAuthorization.ALL = field.NewAsterisk(tableName)
	_aPIAuthorization.ID = field.NewInt(tableName, "id")
	_aPIAuthorization.APIAccountID = field.NewInt(tableName, "api_account_id")
	_aPIAuthorization.Capability = field.NewInt(tableName, "capability")

	_aPIAuthorization.fillFieldMap()

	return _aPIAuthorization
}

// aPIAuthorization OpenAPI 凭证授权表
type aPIAuthorization struct {
	aPIAuthorizationDo

	ALL          field.Asterisk
	ID           field.Int // 自增主码
	APIAccountID field.Int // OpenAPI 凭证信息表 ID
	Capability   field.Int // 权限项，对应表 3-5

	fieldMap map[string]field.Expr
}

func (a aPIAuthorization) Table(newTableName string) *aPIAuthorization {
	a.aPIAuthorizationDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a aPIAuthorization) As(alias string) *aPIAuthorization {
	a.aPIAuthorizationDo.DO = *(a.aPIAuthorizationDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *aPIAuthorization) updateTableName(table string) *aPIAuthorization {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt(table, "id")
	a.APIAccountID = field.NewInt(table, "api_account_id")
	a.Capability = field.NewInt(table, "capability")

	a.fillFieldMap()

	return a
}

func (a *aPIAuthorization) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *aPIAuthorization) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 3)
	a.fieldMap["id"] = a.ID
	a.fieldMap["api_account_id"] = a.APIAccountID
	a.fieldMap["capability"] = a.Capability
}

func (a aPIAuthorization) clone(db *gorm.DB) aPIAuthorization {
	a.aPIAuthorizationDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a aPIAuthorization) replaceDB(db *gorm.DB) aPIAuthorization {
	a.aPIAuthorizationDo.ReplaceDB(db)
	return a
}

type aPIAuthorizationDo struct{ gen.DO }

type IAPIAuthorizationDo interface {
	gen.SubQuery
	Debug() IAPIAuthorizationDo
	WithContext(ctx context.Context) IAPIAuthorizationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAPIAuthorizationDo
	WriteDB() IAPIAuthorizationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAPIAuthorizationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAPIAuthorizationDo
	Not(conds ...gen.Condition) IAPIAuthorizationDo
	Or(conds ...gen.Condition) IAPIAuthorizationDo
	Select(conds ...field.Expr) IAPIAuthorizationDo
	Where(conds ...gen.Condition) IAPIAuthorizationDo
	Order(conds ...field.Expr) IAPIAuthorizationDo
	Distinct(cols ...field.Expr) IAPIAuthorizationDo
	Omit(cols ...field.Expr) IAPIAuthorizationDo
	Join(table schema.Tabler, on ...field.Expr) IAPIAuthorizationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAPIAuthorizationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAPIAuthorizationDo
	Group(cols ...field.Expr) IAPIAuthorizationDo
	Having(conds ...gen.Condition) IAPIAuthorizationDo
	Limit(limit int) IAPIAuthorizationDo
	Offset(offset int) IAPIAuthorizationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAPIAuthorizationDo
	Unscoped() IAPIAuthorizationDo
	Create(values ...*model.APIAuthorization) error
	CreateInBatches(values []*model.APIAuthorization, batchSize int) error
	Save(values ...*model.APIAuthorization) error
	First() (*model.APIAuthorization, error)
	Take() (*model.APIAuthorization, error)
	Last() (*model.APIAuthorization, error)
	Find() ([]*model.APIAuthorization, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.APIAuthorization, err error)
	FindInBatches(result *[]*model.APIAuthorization, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.APIAuthorization) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAPIAuthorizationDo
	Assign(attrs ...field.AssignExpr) IAPIAuthorizationDo
	Joins(fields ...field.RelationField) IAPIAuthorizationDo
	Preload(fields ...field.RelationField) IAPIAuthorizationDo
	FirstOrInit() (*model.APIAuthorization, error)
	FirstOrCreate() (*model.APIAuthorization, error)
	FindByPage(offset int, limit int) (result []*model.APIAuthorization, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAPIAuthorizationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a aPIAuthorizationDo) Debug() IAPIAuthorizationDo {
	return a.withDO(a.DO.Debug())
}

func (a aPIAuthorizationDo) WithContext(ctx context.Context) IAPIAuthorizationDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a aPIAuthorizationDo) ReadDB() IAPIAuthorizationDo {
	return a.Clauses(dbresolver.Read)
}

func (a aPIAuthorizationDo) WriteDB() IAPIAuthorizationDo {
	return a.Clauses(dbresolver.Write)
}

func (a aPIAuthorizationDo) Session(config *gorm.Session) IAPIAuthorizationDo {
	return a.withDO(a.DO.Session(config))
}

func (a aPIAuthorizationDo) Clauses(conds ...clause.Expression) IAPIAuthorizationDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a aPIAuthorizationDo) Returning(value interface{}, columns ...string) IAPIAuthorizationDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a aPIAuthorizationDo) Not(conds ...gen.Condition) IAPIAuthorizationDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a aPIAuthorizationDo) Or(conds ...gen.Condition) IAPIAuthorizationDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a aPIAuthorizationDo) Select(conds ...field.Expr) IAPIAuthorizationDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a aPIAuthorizationDo) Where(conds ...gen.Condition) IAPIAuthorizationDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a aPIAuthorizationDo) Order(conds ...field.Expr) IAPIAuthorizationDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a aPIAuthorizationDo) Distinct(cols ...field.Expr) IAPIAuthorizationDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a aPIAuthorizationDo) Omit(cols ...field.Expr) IAPIAuthorizationDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a aPIAuthorizationDo) Join(table schema.Tabler, on ...field.Expr) IAPIAuthorizationDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a aPIAuthorizationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAPIAuthorizationDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a aPIAuthorizationDo) RightJoin(table schema.Tabler, on ...field.Expr) IAPIAuthorizationDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a aPIAuthorizationDo) Group(cols ...field.Expr) IAPIAuthorizationDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a aPIAuthorizationDo) Having(conds ...gen.Condition) IAPIAuthorizationDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a aPIAuthorizationDo) Limit(limit int) IAPIAuthorizationDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a aPIAuthorizationDo) Offset(offset int) IAPIAuthorizationDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a aPIAuthorizationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAPIAuthorizationDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a aPIAuthorizationDo) Unscoped() IAPIAuthorizationDo {
	return a.withDO(a.DO.Unscoped())
}

func (a aPIAuthorizationDo) Create(values ...*model.APIAuthorization) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a aPIAuthorizationDo) CreateInBatches(values []*model.APIAuthorization, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a aPIAuthorizationDo) Save(values ...*model.APIAuthorization) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a aPIAuthorizationDo) First() (*model.APIAuthorization, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIAuthorization), nil
	}
}

func (a aPIAuthorizationDo) Take() (*model.APIAuthorization, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIAuthorization), nil
	}
}

func (a aPIAuthorizationDo) Last() (*model.APIAuthorization, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIAuthorization), nil
	}
}

func (a aPIAuthorizationDo) Find() ([]*model.APIAuthorization, error) {
	result, err := a.DO.Find()
	return result.([]*model.APIAuthorization), err
}

func (a aPIAuthorizationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.APIAuthorization, err error) {
	buf := make([]*model.APIAuthorization, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a aPIAuthorizationDo) FindInBatches(result *[]*model.APIAuthorization, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a aPIAuthorizationDo) Attrs(attrs ...field.AssignExpr) IAPIAuthorizationDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a aPIAuthorizationDo) Assign(attrs ...field.AssignExpr) IAPIAuthorizationDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a aPIAuthorizationDo) Joins(fields ...field.RelationField) IAPIAuthorizationDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a aPIAuthorizationDo) Preload(fields ...field.RelationField) IAPIAuthorizationDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a aPIAuthorizationDo) FirstOrInit() (*model.APIAuthorization, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIAuthorization), nil
	}
}

func (a aPIAuthorizationDo) FirstOrCreate() (*model.APIAuthorization, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIAuthorization), nil
	}
}

func (a aPIAuthorizationDo) FindByPage(offset int, limit int) (result []*model.APIAuthorization, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a aPIAuthorizationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a aPIAuthorizationDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a aPIAuthorizationDo) Delete(models ...*model.APIAuthorization) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *aPIAuthorizationDo) withDO(do gen.Dao) *aPIAuthorizationDo {
	a.DO = *do.(*gen.DO)
	return a
}
