// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/ivfzhou/csms/comm/model"

	"time"
)

func newWhqlJob(db *gorm.DB, opts ...gen.DOOption) whqlJob {
	_whqlJob := whqlJob{}

	_whqlJob.whqlJobDo.UseDB(db, opts...)
	_whqlJob.whqlJobDo.UseModel(&model.WhqlJob{})

	tableName := _whqlJob.whqlJobDo.TableName()
	_whqlJob.ALL = field.NewAsterisk(tableName)
	_whqlJob.ID = field.NewInt(tableName, "id")
	_whqlJob.JobID = field.NewString(tableName, "job_id")
	_whqlJob.AppID = field.NewInt(tableName, "app_id")
	_whqlJob.UserID = field.NewInt(tableName, "user_id")
	_whqlJob.FileID = field.NewString(tableName, "file_id")
	_whqlJob.SignedFileID = field.NewString(tableName, "signed_file_id")
	_whqlJob.HlkLogFileID = field.NewString(tableName, "hlk_log_file_id")
	_whqlJob.HlkxFileID = field.NewString(tableName, "hlkx_file_id")
	_whqlJob.HlkxSignJobID = field.NewString(tableName, "hlkx_sign_job_id")
	_whqlJob.Type = field.NewInt(tableName, "type")
	_whqlJob.Log = field.NewString(tableName, "log")
	_whqlJob.ProductID = field.NewString(tableName, "product_id")
	_whqlJob.SubmissionID = field.NewString(tableName, "submission_id")
	_whqlJob.Source = field.NewInt(tableName, "source")
	_whqlJob.TestSystem = field.NewString(tableName, "test_system")
	_whqlJob.TestMachineName = field.NewString(tableName, "test_machine_name")
	_whqlJob.TestTarget = field.NewString(tableName, "test_target")
	_whqlJob.ServiceName = field.NewString(tableName, "service_name")
	_whqlJob.TestConfig = field.NewString(tableName, "test_config")
	_whqlJob.FinishedTime = field.NewTime(tableName, "finished_time")
	_whqlJob.FinishTestTime = field.NewTime(tableName, "finish_test_time")
	_whqlJob.Status = field.NewInt(tableName, "status")
	_whqlJob.CreatedTime = field.NewTime(tableName, "created_time")
	_whqlJob.UpdatedTime = field.NewTime(tableName, "updated_time")

	_whqlJob.fillFieldMap()

	return _whqlJob
}

// whqlJob WHQL 签名任务表
type whqlJob struct {
	whqlJobDo

	ALL             field.Asterisk
	ID              field.Int    // 自增主码
	JobID           field.String // 任务 ID
	AppID           field.Int    // 所属应用 ID
	UserID          field.Int    // 提交人 ID
	FileID          field.String // 待签名文件 ID
	SignedFileID    field.String // 已签名文件 ID
	HlkLogFileID    field.String // HLK Studio 日志包文件 ID
	HlkxFileID      field.String // HLKX 文件 ID
	HlkxSignJobID   field.String // HLKX 文件签名任务 ID，对应 Windows 任务表中的 ID
	Type            field.Int    // 类型，1=HLK 兼容性测试+WHQL 签名、2=仅 WHQL 签名
	Log             field.String // 任务日志
	ProductID       field.String // 微软侧的 ID
	SubmissionID    field.String // 微软侧的 ID
	Source          field.Int    // 来源，1=页面、2=OpenAPI
	TestSystem      field.String // 测试系统
	TestMachineName field.String // 测试机器名
	TestTarget      field.String // 测试目标名
	ServiceName     field.String // 服务名
	TestConfig      field.String // HLK 测试项配置
	FinishedTime    field.Time   // 结束时间
	FinishTestTime  field.Time   // 测试结束时间
	Status          field.Int    // 状态，1=待HLK测试、2=测试机初始化中、3=测试机初始化完毕，4=启动HLK测试中，5=HLK测试中，6=HLK测试完毕、7=HLKX 文件签名中、8=等待 WHQL认证结果中、9=失败、10=成功
	CreatedTime     field.Time   // 提交时间
	UpdatedTime     field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (w whqlJob) Table(newTableName string) *whqlJob {
	w.whqlJobDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w whqlJob) As(alias string) *whqlJob {
	w.whqlJobDo.DO = *(w.whqlJobDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *whqlJob) updateTableName(table string) *whqlJob {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt(table, "id")
	w.JobID = field.NewString(table, "job_id")
	w.AppID = field.NewInt(table, "app_id")
	w.UserID = field.NewInt(table, "user_id")
	w.FileID = field.NewString(table, "file_id")
	w.SignedFileID = field.NewString(table, "signed_file_id")
	w.HlkLogFileID = field.NewString(table, "hlk_log_file_id")
	w.HlkxFileID = field.NewString(table, "hlkx_file_id")
	w.HlkxSignJobID = field.NewString(table, "hlkx_sign_job_id")
	w.Type = field.NewInt(table, "type")
	w.Log = field.NewString(table, "log")
	w.ProductID = field.NewString(table, "product_id")
	w.SubmissionID = field.NewString(table, "submission_id")
	w.Source = field.NewInt(table, "source")
	w.TestSystem = field.NewString(table, "test_system")
	w.TestMachineName = field.NewString(table, "test_machine_name")
	w.TestTarget = field.NewString(table, "test_target")
	w.ServiceName = field.NewString(table, "service_name")
	w.TestConfig = field.NewString(table, "test_config")
	w.FinishedTime = field.NewTime(table, "finished_time")
	w.FinishTestTime = field.NewTime(table, "finish_test_time")
	w.Status = field.NewInt(table, "status")
	w.CreatedTime = field.NewTime(table, "created_time")
	w.UpdatedTime = field.NewTime(table, "updated_time")

	w.fillFieldMap()

	return w
}

func (w *whqlJob) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *whqlJob) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 24)
	w.fieldMap["id"] = w.ID
	w.fieldMap["job_id"] = w.JobID
	w.fieldMap["app_id"] = w.AppID
	w.fieldMap["user_id"] = w.UserID
	w.fieldMap["file_id"] = w.FileID
	w.fieldMap["signed_file_id"] = w.SignedFileID
	w.fieldMap["hlk_log_file_id"] = w.HlkLogFileID
	w.fieldMap["hlkx_file_id"] = w.HlkxFileID
	w.fieldMap["hlkx_sign_job_id"] = w.HlkxSignJobID
	w.fieldMap["type"] = w.Type
	w.fieldMap["log"] = w.Log
	w.fieldMap["product_id"] = w.ProductID
	w.fieldMap["submission_id"] = w.SubmissionID
	w.fieldMap["source"] = w.Source
	w.fieldMap["test_system"] = w.TestSystem
	w.fieldMap["test_machine_name"] = w.TestMachineName
	w.fieldMap["test_target"] = w.TestTarget
	w.fieldMap["service_name"] = w.ServiceName
	w.fieldMap["test_config"] = w.TestConfig
	w.fieldMap["finished_time"] = w.FinishedTime
	w.fieldMap["finish_test_time"] = w.FinishTestTime
	w.fieldMap["status"] = w.Status
	w.fieldMap["created_time"] = w.CreatedTime
	w.fieldMap["updated_time"] = w.UpdatedTime
}

func (w whqlJob) clone(db *gorm.DB) whqlJob {
	w.whqlJobDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w whqlJob) replaceDB(db *gorm.DB) whqlJob {
	w.whqlJobDo.ReplaceDB(db)
	return w
}

type whqlJobDo struct{ gen.DO }

type IWhqlJobDo interface {
	gen.SubQuery
	Debug() IWhqlJobDo
	WithContext(ctx context.Context) IWhqlJobDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWhqlJobDo
	WriteDB() IWhqlJobDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWhqlJobDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWhqlJobDo
	Not(conds ...gen.Condition) IWhqlJobDo
	Or(conds ...gen.Condition) IWhqlJobDo
	Select(conds ...field.Expr) IWhqlJobDo
	Where(conds ...gen.Condition) IWhqlJobDo
	Order(conds ...field.Expr) IWhqlJobDo
	Distinct(cols ...field.Expr) IWhqlJobDo
	Omit(cols ...field.Expr) IWhqlJobDo
	Join(table schema.Tabler, on ...field.Expr) IWhqlJobDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWhqlJobDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWhqlJobDo
	Group(cols ...field.Expr) IWhqlJobDo
	Having(conds ...gen.Condition) IWhqlJobDo
	Limit(limit int) IWhqlJobDo
	Offset(offset int) IWhqlJobDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWhqlJobDo
	Unscoped() IWhqlJobDo
	Create(values ...*model.WhqlJob) error
	CreateInBatches(values []*model.WhqlJob, batchSize int) error
	Save(values ...*model.WhqlJob) error
	First() (*model.WhqlJob, error)
	Take() (*model.WhqlJob, error)
	Last() (*model.WhqlJob, error)
	Find() ([]*model.WhqlJob, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WhqlJob, err error)
	FindInBatches(result *[]*model.WhqlJob, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WhqlJob) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWhqlJobDo
	Assign(attrs ...field.AssignExpr) IWhqlJobDo
	Joins(fields ...field.RelationField) IWhqlJobDo
	Preload(fields ...field.RelationField) IWhqlJobDo
	FirstOrInit() (*model.WhqlJob, error)
	FirstOrCreate() (*model.WhqlJob, error)
	FindByPage(offset int, limit int) (result []*model.WhqlJob, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWhqlJobDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	CountWithDay(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	CountWithWeek(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	CountWithMonth(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	CostWithDay(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	CostWithWeek(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	CostWithMonth(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	PassRateWithDay(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	PassRateWithWeek(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	PassRateWithMonth(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
}

// select type `type`, count(*) `count`, date_format(created_time, '%Y%m%d') `day` from t_whql_job
// where created_time between @begin and @end
//
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//
// group by `day`, `type`
// order by `day`
func (w whqlJobDo) CountWithDay(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, begin)
	params = append(params, end)
	generateSQL.WriteString("select type `type`, count(*) `count`, date_format(created_time, '%Y%m%d') `day` from t_whql_job where created_time between ? and ? ")
	if appID > 0 {
		params = append(params, appID)
		generateSQL.WriteString("and app_id = ? ")
	}
	generateSQL.WriteString("group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select type `type`, count(*) `count`, date_format(date_sub(created_time, INTERVAL (dayofweek(created_time)-2) DAY), '%Y%m%d') `day` from t_whql_job
// where created_time between @begin and @end
//
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//
// group by `day`, `type`
// order by `day`
func (w whqlJobDo) CountWithWeek(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, begin)
	params = append(params, end)
	generateSQL.WriteString("select type `type`, count(*) `count`, date_format(date_sub(created_time, INTERVAL (dayofweek(created_time)-2) DAY), '%Y%m%d') `day` from t_whql_job where created_time between ? and ? ")
	if appID > 0 {
		params = append(params, appID)
		generateSQL.WriteString("and app_id = ? ")
	}
	generateSQL.WriteString("group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select type `type`, count(*) `count`, date_format(created_time, '%Y%m') `day` from t_whql_job
// where created_time between @begin and @end
//
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//
// group by `day`, `type`
// order by `day`
func (w whqlJobDo) CountWithMonth(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, begin)
	params = append(params, end)
	generateSQL.WriteString("select type `type`, count(*) `count`, date_format(created_time, '%Y%m') `day` from t_whql_job where created_time between ? and ? ")
	if appID > 0 {
		params = append(params, appID)
		generateSQL.WriteString("and app_id = ? ")
	}
	generateSQL.WriteString("group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select type `type`, date_format(created_time, '%Y%m%d') `day`, cast(round(avg(timestampdiff(SECOND, created_time, ifnull(finished_time, now()))), 0) as signed) `cost` from t_whql_job
// where created_time between @begin and @end and status in (9, 10)
//
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//
// group by `day`, `type`
// order by `day`
func (w whqlJobDo) CostWithDay(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, begin)
	params = append(params, end)
	generateSQL.WriteString("select type `type`, date_format(created_time, '%Y%m%d') `day`, cast(round(avg(timestampdiff(SECOND, created_time, ifnull(finished_time, now()))), 0) as signed) `cost` from t_whql_job where created_time between ? and ? and status in (9, 10) ")
	if appID > 0 {
		params = append(params, appID)
		generateSQL.WriteString("and app_id = ? ")
	}
	generateSQL.WriteString("group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select type `type`, date_format(date_sub(created_time, INTERVAL (dayofweek(created_time)-2) DAY), '%Y%m%d') `day`, cast(round(avg(timestampdiff(SECOND, created_time, ifnull(finished_time, now()))), 0) as signed) `cost` from t_whql_job
// where created_time between @begin and @end and status in (9, 10)
//
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//
// group by `day`, `type`
// order by `day`
func (w whqlJobDo) CostWithWeek(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, begin)
	params = append(params, end)
	generateSQL.WriteString("select type `type`, date_format(date_sub(created_time, INTERVAL (dayofweek(created_time)-2) DAY), '%Y%m%d') `day`, cast(round(avg(timestampdiff(SECOND, created_time, ifnull(finished_time, now()))), 0) as signed) `cost` from t_whql_job where created_time between ? and ? and status in (9, 10) ")
	if appID > 0 {
		params = append(params, appID)
		generateSQL.WriteString("and app_id = ? ")
	}
	generateSQL.WriteString("group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select type `type`, date_format(created_time, '%Y%m') `day`, cast(round(avg(timestampdiff(SECOND, created_time, ifnull(finished_time, now()))), 0) as signed) `cost` from t_whql_job
// where created_time between @begin and @end and status in (9, 10)
//
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//
// group by `day`, `type`
// order by `day`
func (w whqlJobDo) CostWithMonth(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, begin)
	params = append(params, end)
	generateSQL.WriteString("select type `type`, date_format(created_time, '%Y%m') `day`, cast(round(avg(timestampdiff(SECOND, created_time, ifnull(finished_time, now()))), 0) as signed) `cost` from t_whql_job where created_time between ? and ? and status in (9, 10) ")
	if appID > 0 {
		params = append(params, appID)
		generateSQL.WriteString("and app_id = ? ")
	}
	generateSQL.WriteString("group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select type `type`, date_format(created_time, '%Y%m%d') `day`, cast(round(sum(case status when 10 then 1 else 0 end) * 10000 / count(*), 0) as signed) `rate` from t_whql_job
//
//	where created_time between @begin and @end and status in (9, 10)
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//
// group by `day`, `type`
// order by `day`
func (w whqlJobDo) PassRateWithDay(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, begin)
	params = append(params, end)
	generateSQL.WriteString("select type `type`, date_format(created_time, '%Y%m%d') `day`, cast(round(sum(case status when 10 then 1 else 0 end) * 10000 / count(*), 0) as signed) `rate` from t_whql_job where created_time between ? and ? and status in (9, 10) ")
	if appID > 0 {
		params = append(params, appID)
		generateSQL.WriteString("and app_id = ? ")
	}
	generateSQL.WriteString("group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select type `type`, date_format(date_sub(created_time, INTERVAL (dayofweek(created_time)-2) DAY), '%Y%m%d') `day`, cast(round(sum(case status when 10 then 1 else 0 end) * 10000 / count(*), 0) as signed) `rate` from t_whql_job
//
//	where created_time between @begin and @end and status in (9, 10)
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//
// group by `day`, `type`
// order by `day`
func (w whqlJobDo) PassRateWithWeek(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, begin)
	params = append(params, end)
	generateSQL.WriteString("select type `type`, date_format(date_sub(created_time, INTERVAL (dayofweek(created_time)-2) DAY), '%Y%m%d') `day`, cast(round(sum(case status when 10 then 1 else 0 end) * 10000 / count(*), 0) as signed) `rate` from t_whql_job where created_time between ? and ? and status in (9, 10) ")
	if appID > 0 {
		params = append(params, appID)
		generateSQL.WriteString("and app_id = ? ")
	}
	generateSQL.WriteString("group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select type `type`, date_format(created_time, '%Y%m') `day`, cast(round(sum(case status when 10 then 1 else 0 end) * 10000 / count(*), 0) as signed) `rate` from t_whql_job
//
//	where created_time between @begin and @end and status in (9, 10)
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//
// group by `day`, `type`
// order by `day`
func (w whqlJobDo) PassRateWithMonth(appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, begin)
	params = append(params, end)
	generateSQL.WriteString("select type `type`, date_format(created_time, '%Y%m') `day`, cast(round(sum(case status when 10 then 1 else 0 end) * 10000 / count(*), 0) as signed) `rate` from t_whql_job where created_time between ? and ? and status in (9, 10) ")
	if appID > 0 {
		params = append(params, appID)
		generateSQL.WriteString("and app_id = ? ")
	}
	generateSQL.WriteString("group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (w whqlJobDo) Debug() IWhqlJobDo {
	return w.withDO(w.DO.Debug())
}

func (w whqlJobDo) WithContext(ctx context.Context) IWhqlJobDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w whqlJobDo) ReadDB() IWhqlJobDo {
	return w.Clauses(dbresolver.Read)
}

func (w whqlJobDo) WriteDB() IWhqlJobDo {
	return w.Clauses(dbresolver.Write)
}

func (w whqlJobDo) Session(config *gorm.Session) IWhqlJobDo {
	return w.withDO(w.DO.Session(config))
}

func (w whqlJobDo) Clauses(conds ...clause.Expression) IWhqlJobDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w whqlJobDo) Returning(value interface{}, columns ...string) IWhqlJobDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w whqlJobDo) Not(conds ...gen.Condition) IWhqlJobDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w whqlJobDo) Or(conds ...gen.Condition) IWhqlJobDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w whqlJobDo) Select(conds ...field.Expr) IWhqlJobDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w whqlJobDo) Where(conds ...gen.Condition) IWhqlJobDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w whqlJobDo) Order(conds ...field.Expr) IWhqlJobDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w whqlJobDo) Distinct(cols ...field.Expr) IWhqlJobDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w whqlJobDo) Omit(cols ...field.Expr) IWhqlJobDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w whqlJobDo) Join(table schema.Tabler, on ...field.Expr) IWhqlJobDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w whqlJobDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWhqlJobDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w whqlJobDo) RightJoin(table schema.Tabler, on ...field.Expr) IWhqlJobDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w whqlJobDo) Group(cols ...field.Expr) IWhqlJobDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w whqlJobDo) Having(conds ...gen.Condition) IWhqlJobDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w whqlJobDo) Limit(limit int) IWhqlJobDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w whqlJobDo) Offset(offset int) IWhqlJobDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w whqlJobDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWhqlJobDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w whqlJobDo) Unscoped() IWhqlJobDo {
	return w.withDO(w.DO.Unscoped())
}

func (w whqlJobDo) Create(values ...*model.WhqlJob) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w whqlJobDo) CreateInBatches(values []*model.WhqlJob, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w whqlJobDo) Save(values ...*model.WhqlJob) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w whqlJobDo) First() (*model.WhqlJob, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WhqlJob), nil
	}
}

func (w whqlJobDo) Take() (*model.WhqlJob, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WhqlJob), nil
	}
}

func (w whqlJobDo) Last() (*model.WhqlJob, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WhqlJob), nil
	}
}

func (w whqlJobDo) Find() ([]*model.WhqlJob, error) {
	result, err := w.DO.Find()
	return result.([]*model.WhqlJob), err
}

func (w whqlJobDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WhqlJob, err error) {
	buf := make([]*model.WhqlJob, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w whqlJobDo) FindInBatches(result *[]*model.WhqlJob, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w whqlJobDo) Attrs(attrs ...field.AssignExpr) IWhqlJobDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w whqlJobDo) Assign(attrs ...field.AssignExpr) IWhqlJobDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w whqlJobDo) Joins(fields ...field.RelationField) IWhqlJobDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w whqlJobDo) Preload(fields ...field.RelationField) IWhqlJobDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w whqlJobDo) FirstOrInit() (*model.WhqlJob, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WhqlJob), nil
	}
}

func (w whqlJobDo) FirstOrCreate() (*model.WhqlJob, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WhqlJob), nil
	}
}

func (w whqlJobDo) FindByPage(offset int, limit int) (result []*model.WhqlJob, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w whqlJobDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w whqlJobDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w whqlJobDo) Delete(models ...*model.WhqlJob) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *whqlJobDo) withDO(do gen.Dao) *whqlJobDo {
	w.DO = *do.(*gen.DO)
	return w
}
