// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/ivfzhou/csms/comm/model"
)

func newWindowsCertificateAuthorization(db *gorm.DB, opts ...gen.DOOption) windowsCertificateAuthorization {
	_windowsCertificateAuthorization := windowsCertificateAuthorization{}

	_windowsCertificateAuthorization.windowsCertificateAuthorizationDo.UseDB(db, opts...)
	_windowsCertificateAuthorization.windowsCertificateAuthorizationDo.UseModel(&model.WindowsCertificateAuthorization{})

	tableName := _windowsCertificateAuthorization.windowsCertificateAuthorizationDo.TableName()
	_windowsCertificateAuthorization.ALL = field.NewAsterisk(tableName)
	_windowsCertificateAuthorization.ID = field.NewInt(tableName, "id")
	_windowsCertificateAuthorization.AppID = field.NewInt(tableName, "app_id")
	_windowsCertificateAuthorization.UserID = field.NewInt(tableName, "user_id")
	_windowsCertificateAuthorization.CertificateID = field.NewInt(tableName, "certificate_id")
	_windowsCertificateAuthorization.CreatedTime = field.NewTime(tableName, "created_time")

	_windowsCertificateAuthorization.fillFieldMap()

	return _windowsCertificateAuthorization
}

// windowsCertificateAuthorization 授权应用 EV 证书表
type windowsCertificateAuthorization struct {
	windowsCertificateAuthorizationDo

	ALL           field.Asterisk
	ID            field.Int  // 自增主码
	AppID         field.Int  // 所属应用 ID
	UserID        field.Int  // 操作人 ID
	CertificateID field.Int  // Windows 证书表 ID
	CreatedTime   field.Time // 授权时间

	fieldMap map[string]field.Expr
}

func (w windowsCertificateAuthorization) Table(newTableName string) *windowsCertificateAuthorization {
	w.windowsCertificateAuthorizationDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w windowsCertificateAuthorization) As(alias string) *windowsCertificateAuthorization {
	w.windowsCertificateAuthorizationDo.DO = *(w.windowsCertificateAuthorizationDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *windowsCertificateAuthorization) updateTableName(table string) *windowsCertificateAuthorization {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt(table, "id")
	w.AppID = field.NewInt(table, "app_id")
	w.UserID = field.NewInt(table, "user_id")
	w.CertificateID = field.NewInt(table, "certificate_id")
	w.CreatedTime = field.NewTime(table, "created_time")

	w.fillFieldMap()

	return w
}

func (w *windowsCertificateAuthorization) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *windowsCertificateAuthorization) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 5)
	w.fieldMap["id"] = w.ID
	w.fieldMap["app_id"] = w.AppID
	w.fieldMap["user_id"] = w.UserID
	w.fieldMap["certificate_id"] = w.CertificateID
	w.fieldMap["created_time"] = w.CreatedTime
}

func (w windowsCertificateAuthorization) clone(db *gorm.DB) windowsCertificateAuthorization {
	w.windowsCertificateAuthorizationDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w windowsCertificateAuthorization) replaceDB(db *gorm.DB) windowsCertificateAuthorization {
	w.windowsCertificateAuthorizationDo.ReplaceDB(db)
	return w
}

type windowsCertificateAuthorizationDo struct{ gen.DO }

type IWindowsCertificateAuthorizationDo interface {
	gen.SubQuery
	Debug() IWindowsCertificateAuthorizationDo
	WithContext(ctx context.Context) IWindowsCertificateAuthorizationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWindowsCertificateAuthorizationDo
	WriteDB() IWindowsCertificateAuthorizationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWindowsCertificateAuthorizationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWindowsCertificateAuthorizationDo
	Not(conds ...gen.Condition) IWindowsCertificateAuthorizationDo
	Or(conds ...gen.Condition) IWindowsCertificateAuthorizationDo
	Select(conds ...field.Expr) IWindowsCertificateAuthorizationDo
	Where(conds ...gen.Condition) IWindowsCertificateAuthorizationDo
	Order(conds ...field.Expr) IWindowsCertificateAuthorizationDo
	Distinct(cols ...field.Expr) IWindowsCertificateAuthorizationDo
	Omit(cols ...field.Expr) IWindowsCertificateAuthorizationDo
	Join(table schema.Tabler, on ...field.Expr) IWindowsCertificateAuthorizationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWindowsCertificateAuthorizationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWindowsCertificateAuthorizationDo
	Group(cols ...field.Expr) IWindowsCertificateAuthorizationDo
	Having(conds ...gen.Condition) IWindowsCertificateAuthorizationDo
	Limit(limit int) IWindowsCertificateAuthorizationDo
	Offset(offset int) IWindowsCertificateAuthorizationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWindowsCertificateAuthorizationDo
	Unscoped() IWindowsCertificateAuthorizationDo
	Create(values ...*model.WindowsCertificateAuthorization) error
	CreateInBatches(values []*model.WindowsCertificateAuthorization, batchSize int) error
	Save(values ...*model.WindowsCertificateAuthorization) error
	First() (*model.WindowsCertificateAuthorization, error)
	Take() (*model.WindowsCertificateAuthorization, error)
	Last() (*model.WindowsCertificateAuthorization, error)
	Find() ([]*model.WindowsCertificateAuthorization, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WindowsCertificateAuthorization, err error)
	FindInBatches(result *[]*model.WindowsCertificateAuthorization, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WindowsCertificateAuthorization) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWindowsCertificateAuthorizationDo
	Assign(attrs ...field.AssignExpr) IWindowsCertificateAuthorizationDo
	Joins(fields ...field.RelationField) IWindowsCertificateAuthorizationDo
	Preload(fields ...field.RelationField) IWindowsCertificateAuthorizationDo
	FirstOrInit() (*model.WindowsCertificateAuthorization, error)
	FirstOrCreate() (*model.WindowsCertificateAuthorization, error)
	FindByPage(offset int, limit int) (result []*model.WindowsCertificateAuthorization, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWindowsCertificateAuthorizationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w windowsCertificateAuthorizationDo) Debug() IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Debug())
}

func (w windowsCertificateAuthorizationDo) WithContext(ctx context.Context) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w windowsCertificateAuthorizationDo) ReadDB() IWindowsCertificateAuthorizationDo {
	return w.Clauses(dbresolver.Read)
}

func (w windowsCertificateAuthorizationDo) WriteDB() IWindowsCertificateAuthorizationDo {
	return w.Clauses(dbresolver.Write)
}

func (w windowsCertificateAuthorizationDo) Session(config *gorm.Session) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Session(config))
}

func (w windowsCertificateAuthorizationDo) Clauses(conds ...clause.Expression) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w windowsCertificateAuthorizationDo) Returning(value interface{}, columns ...string) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w windowsCertificateAuthorizationDo) Not(conds ...gen.Condition) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w windowsCertificateAuthorizationDo) Or(conds ...gen.Condition) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w windowsCertificateAuthorizationDo) Select(conds ...field.Expr) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w windowsCertificateAuthorizationDo) Where(conds ...gen.Condition) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w windowsCertificateAuthorizationDo) Order(conds ...field.Expr) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w windowsCertificateAuthorizationDo) Distinct(cols ...field.Expr) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w windowsCertificateAuthorizationDo) Omit(cols ...field.Expr) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w windowsCertificateAuthorizationDo) Join(table schema.Tabler, on ...field.Expr) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w windowsCertificateAuthorizationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w windowsCertificateAuthorizationDo) RightJoin(table schema.Tabler, on ...field.Expr) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w windowsCertificateAuthorizationDo) Group(cols ...field.Expr) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w windowsCertificateAuthorizationDo) Having(conds ...gen.Condition) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w windowsCertificateAuthorizationDo) Limit(limit int) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w windowsCertificateAuthorizationDo) Offset(offset int) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w windowsCertificateAuthorizationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w windowsCertificateAuthorizationDo) Unscoped() IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Unscoped())
}

func (w windowsCertificateAuthorizationDo) Create(values ...*model.WindowsCertificateAuthorization) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w windowsCertificateAuthorizationDo) CreateInBatches(values []*model.WindowsCertificateAuthorization, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w windowsCertificateAuthorizationDo) Save(values ...*model.WindowsCertificateAuthorization) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w windowsCertificateAuthorizationDo) First() (*model.WindowsCertificateAuthorization, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WindowsCertificateAuthorization), nil
	}
}

func (w windowsCertificateAuthorizationDo) Take() (*model.WindowsCertificateAuthorization, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WindowsCertificateAuthorization), nil
	}
}

func (w windowsCertificateAuthorizationDo) Last() (*model.WindowsCertificateAuthorization, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WindowsCertificateAuthorization), nil
	}
}

func (w windowsCertificateAuthorizationDo) Find() ([]*model.WindowsCertificateAuthorization, error) {
	result, err := w.DO.Find()
	return result.([]*model.WindowsCertificateAuthorization), err
}

func (w windowsCertificateAuthorizationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WindowsCertificateAuthorization, err error) {
	buf := make([]*model.WindowsCertificateAuthorization, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w windowsCertificateAuthorizationDo) FindInBatches(result *[]*model.WindowsCertificateAuthorization, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w windowsCertificateAuthorizationDo) Attrs(attrs ...field.AssignExpr) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w windowsCertificateAuthorizationDo) Assign(attrs ...field.AssignExpr) IWindowsCertificateAuthorizationDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w windowsCertificateAuthorizationDo) Joins(fields ...field.RelationField) IWindowsCertificateAuthorizationDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w windowsCertificateAuthorizationDo) Preload(fields ...field.RelationField) IWindowsCertificateAuthorizationDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w windowsCertificateAuthorizationDo) FirstOrInit() (*model.WindowsCertificateAuthorization, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WindowsCertificateAuthorization), nil
	}
}

func (w windowsCertificateAuthorizationDo) FirstOrCreate() (*model.WindowsCertificateAuthorization, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WindowsCertificateAuthorization), nil
	}
}

func (w windowsCertificateAuthorizationDo) FindByPage(offset int, limit int) (result []*model.WindowsCertificateAuthorization, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w windowsCertificateAuthorizationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w windowsCertificateAuthorizationDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w windowsCertificateAuthorizationDo) Delete(models ...*model.WindowsCertificateAuthorization) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *windowsCertificateAuthorizationDo) withDO(do gen.Dao) *windowsCertificateAuthorizationDo {
	w.DO = *do.(*gen.DO)
	return w
}
