// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/ivfzhou/csms/comm/model"
)

func newWindowsCertificate(db *gorm.DB, opts ...gen.DOOption) windowsCertificate {
	_windowsCertificate := windowsCertificate{}

	_windowsCertificate.windowsCertificateDo.UseDB(db, opts...)
	_windowsCertificate.windowsCertificateDo.UseModel(&model.WindowsCertificate{})

	tableName := _windowsCertificate.windowsCertificateDo.TableName()
	_windowsCertificate.ALL = field.NewAsterisk(tableName)
	_windowsCertificate.ID = field.NewInt(tableName, "id")
	_windowsCertificate.CertificateID = field.NewString(tableName, "certificate_id")
	_windowsCertificate.AppID = field.NewInt(tableName, "app_id")
	_windowsCertificate.UserID = field.NewInt(tableName, "user_id")
	_windowsCertificate.Sha1 = field.NewString(tableName, "sha1")
	_windowsCertificate.Type = field.NewInt(tableName, "type")
	_windowsCertificate.IP = field.NewString(tableName, "ip")
	_windowsCertificate.IsMicrosoftVerifyCertificate = field.NewField(tableName, "is_microsoft_verify_certificate")
	_windowsCertificate.Password = field.NewString(tableName, "password")
	_windowsCertificate.Version = field.NewInt(tableName, "version")
	_windowsCertificate.Publisher = field.NewString(tableName, "publisher")
	_windowsCertificate.CommonName = field.NewString(tableName, "common_name")
	_windowsCertificate.Owner = field.NewString(tableName, "owner")
	_windowsCertificate.SignatureAlgorithm = field.NewString(tableName, "signature_algorithm")
	_windowsCertificate.PublicKeyAlgorithm = field.NewString(tableName, "public_key_algorithm")
	_windowsCertificate.SerialNumber = field.NewString(tableName, "serial_number")
	_windowsCertificate.NotBefore = field.NewTime(tableName, "not_before")
	_windowsCertificate.NotAfter = field.NewTime(tableName, "not_after")
	_windowsCertificate.AesKeyID = field.NewInt(tableName, "aes_key_id")
	_windowsCertificate.Content = field.NewBytes(tableName, "content")
	_windowsCertificate.CreatedTime = field.NewTime(tableName, "created_time")
	_windowsCertificate.DeletedTime = field.NewTime(tableName, "deleted_time")

	_windowsCertificate.fillFieldMap()

	return _windowsCertificate
}

// windowsCertificate Windows 证书信息表
type windowsCertificate struct {
	windowsCertificateDo

	ALL                          field.Asterisk
	ID                           field.Int    // 自增主码
	CertificateID                field.String // 唯一标识
	AppID                        field.Int    // 所属应用 ID
	UserID                       field.Int    // 创建人 ID
	Sha1                         field.String // 指纹
	Type                         field.Int    // 类型，1=公司EV、2=公司OV、3=个人EV、4=个人OV
	IP                           field.String // UKEY 所在机器 IP
	IsMicrosoftVerifyCertificate field.Field  // 是否是微软网站的验证证书
	Password                     field.String // 密码
	Version                      field.Int    // 版本号
	Publisher                    field.String // 颁发者
	CommonName                   field.String // 通用名
	Owner                        field.String // 所有者
	SignatureAlgorithm           field.String // 签名算法
	PublicKeyAlgorithm           field.String // 公钥密码算法
	SerialNumber                 field.String // 序列号
	NotBefore                    field.Time   // 生效时间
	NotAfter                     field.Time   // 失效时间
	AesKeyID                     field.Int    // 证书加密密钥 ID
	Content                      field.Bytes  // 加密了的证书内容
	CreatedTime                  field.Time   // 创建时间
	DeletedTime                  field.Time   // 删除时间

	fieldMap map[string]field.Expr
}

func (w windowsCertificate) Table(newTableName string) *windowsCertificate {
	w.windowsCertificateDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w windowsCertificate) As(alias string) *windowsCertificate {
	w.windowsCertificateDo.DO = *(w.windowsCertificateDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *windowsCertificate) updateTableName(table string) *windowsCertificate {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt(table, "id")
	w.CertificateID = field.NewString(table, "certificate_id")
	w.AppID = field.NewInt(table, "app_id")
	w.UserID = field.NewInt(table, "user_id")
	w.Sha1 = field.NewString(table, "sha1")
	w.Type = field.NewInt(table, "type")
	w.IP = field.NewString(table, "ip")
	w.IsMicrosoftVerifyCertificate = field.NewField(table, "is_microsoft_verify_certificate")
	w.Password = field.NewString(table, "password")
	w.Version = field.NewInt(table, "version")
	w.Publisher = field.NewString(table, "publisher")
	w.CommonName = field.NewString(table, "common_name")
	w.Owner = field.NewString(table, "owner")
	w.SignatureAlgorithm = field.NewString(table, "signature_algorithm")
	w.PublicKeyAlgorithm = field.NewString(table, "public_key_algorithm")
	w.SerialNumber = field.NewString(table, "serial_number")
	w.NotBefore = field.NewTime(table, "not_before")
	w.NotAfter = field.NewTime(table, "not_after")
	w.AesKeyID = field.NewInt(table, "aes_key_id")
	w.Content = field.NewBytes(table, "content")
	w.CreatedTime = field.NewTime(table, "created_time")
	w.DeletedTime = field.NewTime(table, "deleted_time")

	w.fillFieldMap()

	return w
}

func (w *windowsCertificate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *windowsCertificate) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 22)
	w.fieldMap["id"] = w.ID
	w.fieldMap["certificate_id"] = w.CertificateID
	w.fieldMap["app_id"] = w.AppID
	w.fieldMap["user_id"] = w.UserID
	w.fieldMap["sha1"] = w.Sha1
	w.fieldMap["type"] = w.Type
	w.fieldMap["ip"] = w.IP
	w.fieldMap["is_microsoft_verify_certificate"] = w.IsMicrosoftVerifyCertificate
	w.fieldMap["password"] = w.Password
	w.fieldMap["version"] = w.Version
	w.fieldMap["publisher"] = w.Publisher
	w.fieldMap["common_name"] = w.CommonName
	w.fieldMap["owner"] = w.Owner
	w.fieldMap["signature_algorithm"] = w.SignatureAlgorithm
	w.fieldMap["public_key_algorithm"] = w.PublicKeyAlgorithm
	w.fieldMap["serial_number"] = w.SerialNumber
	w.fieldMap["not_before"] = w.NotBefore
	w.fieldMap["not_after"] = w.NotAfter
	w.fieldMap["aes_key_id"] = w.AesKeyID
	w.fieldMap["content"] = w.Content
	w.fieldMap["created_time"] = w.CreatedTime
	w.fieldMap["deleted_time"] = w.DeletedTime
}

func (w windowsCertificate) clone(db *gorm.DB) windowsCertificate {
	w.windowsCertificateDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w windowsCertificate) replaceDB(db *gorm.DB) windowsCertificate {
	w.windowsCertificateDo.ReplaceDB(db)
	return w
}

type windowsCertificateDo struct{ gen.DO }

type IWindowsCertificateDo interface {
	gen.SubQuery
	Debug() IWindowsCertificateDo
	WithContext(ctx context.Context) IWindowsCertificateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWindowsCertificateDo
	WriteDB() IWindowsCertificateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWindowsCertificateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWindowsCertificateDo
	Not(conds ...gen.Condition) IWindowsCertificateDo
	Or(conds ...gen.Condition) IWindowsCertificateDo
	Select(conds ...field.Expr) IWindowsCertificateDo
	Where(conds ...gen.Condition) IWindowsCertificateDo
	Order(conds ...field.Expr) IWindowsCertificateDo
	Distinct(cols ...field.Expr) IWindowsCertificateDo
	Omit(cols ...field.Expr) IWindowsCertificateDo
	Join(table schema.Tabler, on ...field.Expr) IWindowsCertificateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWindowsCertificateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWindowsCertificateDo
	Group(cols ...field.Expr) IWindowsCertificateDo
	Having(conds ...gen.Condition) IWindowsCertificateDo
	Limit(limit int) IWindowsCertificateDo
	Offset(offset int) IWindowsCertificateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWindowsCertificateDo
	Unscoped() IWindowsCertificateDo
	Create(values ...*model.WindowsCertificate) error
	CreateInBatches(values []*model.WindowsCertificate, batchSize int) error
	Save(values ...*model.WindowsCertificate) error
	First() (*model.WindowsCertificate, error)
	Take() (*model.WindowsCertificate, error)
	Last() (*model.WindowsCertificate, error)
	Find() ([]*model.WindowsCertificate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WindowsCertificate, err error)
	FindInBatches(result *[]*model.WindowsCertificate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WindowsCertificate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWindowsCertificateDo
	Assign(attrs ...field.AssignExpr) IWindowsCertificateDo
	Joins(fields ...field.RelationField) IWindowsCertificateDo
	Preload(fields ...field.RelationField) IWindowsCertificateDo
	FirstOrInit() (*model.WindowsCertificate, error)
	FirstOrCreate() (*model.WindowsCertificate, error)
	FindByPage(offset int, limit int) (result []*model.WindowsCertificate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWindowsCertificateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w windowsCertificateDo) Debug() IWindowsCertificateDo {
	return w.withDO(w.DO.Debug())
}

func (w windowsCertificateDo) WithContext(ctx context.Context) IWindowsCertificateDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w windowsCertificateDo) ReadDB() IWindowsCertificateDo {
	return w.Clauses(dbresolver.Read)
}

func (w windowsCertificateDo) WriteDB() IWindowsCertificateDo {
	return w.Clauses(dbresolver.Write)
}

func (w windowsCertificateDo) Session(config *gorm.Session) IWindowsCertificateDo {
	return w.withDO(w.DO.Session(config))
}

func (w windowsCertificateDo) Clauses(conds ...clause.Expression) IWindowsCertificateDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w windowsCertificateDo) Returning(value interface{}, columns ...string) IWindowsCertificateDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w windowsCertificateDo) Not(conds ...gen.Condition) IWindowsCertificateDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w windowsCertificateDo) Or(conds ...gen.Condition) IWindowsCertificateDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w windowsCertificateDo) Select(conds ...field.Expr) IWindowsCertificateDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w windowsCertificateDo) Where(conds ...gen.Condition) IWindowsCertificateDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w windowsCertificateDo) Order(conds ...field.Expr) IWindowsCertificateDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w windowsCertificateDo) Distinct(cols ...field.Expr) IWindowsCertificateDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w windowsCertificateDo) Omit(cols ...field.Expr) IWindowsCertificateDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w windowsCertificateDo) Join(table schema.Tabler, on ...field.Expr) IWindowsCertificateDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w windowsCertificateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWindowsCertificateDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w windowsCertificateDo) RightJoin(table schema.Tabler, on ...field.Expr) IWindowsCertificateDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w windowsCertificateDo) Group(cols ...field.Expr) IWindowsCertificateDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w windowsCertificateDo) Having(conds ...gen.Condition) IWindowsCertificateDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w windowsCertificateDo) Limit(limit int) IWindowsCertificateDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w windowsCertificateDo) Offset(offset int) IWindowsCertificateDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w windowsCertificateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWindowsCertificateDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w windowsCertificateDo) Unscoped() IWindowsCertificateDo {
	return w.withDO(w.DO.Unscoped())
}

func (w windowsCertificateDo) Create(values ...*model.WindowsCertificate) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w windowsCertificateDo) CreateInBatches(values []*model.WindowsCertificate, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w windowsCertificateDo) Save(values ...*model.WindowsCertificate) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w windowsCertificateDo) First() (*model.WindowsCertificate, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WindowsCertificate), nil
	}
}

func (w windowsCertificateDo) Take() (*model.WindowsCertificate, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WindowsCertificate), nil
	}
}

func (w windowsCertificateDo) Last() (*model.WindowsCertificate, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WindowsCertificate), nil
	}
}

func (w windowsCertificateDo) Find() ([]*model.WindowsCertificate, error) {
	result, err := w.DO.Find()
	return result.([]*model.WindowsCertificate), err
}

func (w windowsCertificateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WindowsCertificate, err error) {
	buf := make([]*model.WindowsCertificate, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w windowsCertificateDo) FindInBatches(result *[]*model.WindowsCertificate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w windowsCertificateDo) Attrs(attrs ...field.AssignExpr) IWindowsCertificateDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w windowsCertificateDo) Assign(attrs ...field.AssignExpr) IWindowsCertificateDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w windowsCertificateDo) Joins(fields ...field.RelationField) IWindowsCertificateDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w windowsCertificateDo) Preload(fields ...field.RelationField) IWindowsCertificateDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w windowsCertificateDo) FirstOrInit() (*model.WindowsCertificate, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WindowsCertificate), nil
	}
}

func (w windowsCertificateDo) FirstOrCreate() (*model.WindowsCertificate, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WindowsCertificate), nil
	}
}

func (w windowsCertificateDo) FindByPage(offset int, limit int) (result []*model.WindowsCertificate, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w windowsCertificateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w windowsCertificateDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w windowsCertificateDo) Delete(models ...*model.WindowsCertificate) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *windowsCertificateDo) withDO(do gen.Dao) *windowsCertificateDo {
	w.DO = *do.(*gen.DO)
	return w
}
