// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/ivfzhou/csms/comm/model"

	"time"
)

func newWindowsSigningJob(db *gorm.DB, opts ...gen.DOOption) windowsSigningJob {
	_windowsSigningJob := windowsSigningJob{}

	_windowsSigningJob.windowsSigningJobDo.UseDB(db, opts...)
	_windowsSigningJob.windowsSigningJobDo.UseModel(&model.WindowsSigningJob{})

	tableName := _windowsSigningJob.windowsSigningJobDo.TableName()
	_windowsSigningJob.ALL = field.NewAsterisk(tableName)
	_windowsSigningJob.ID = field.NewInt(tableName, "id")
	_windowsSigningJob.JobID = field.NewString(tableName, "job_id")
	_windowsSigningJob.Type = field.NewInt(tableName, "type")
	_windowsSigningJob.AppID = field.NewInt(tableName, "app_id")
	_windowsSigningJob.UserID = field.NewInt(tableName, "user_id")
	_windowsSigningJob.CertificateID = field.NewInt(tableName, "certificate_id")
	_windowsSigningJob.FileID = field.NewString(tableName, "file_id")
	_windowsSigningJob.SignedFileID = field.NewString(tableName, "signed_file_id")
	_windowsSigningJob.Log = field.NewString(tableName, "log")
	_windowsSigningJob.ProductID = field.NewString(tableName, "product_id")
	_windowsSigningJob.SubmissionID = field.NewString(tableName, "submission_id")
	_windowsSigningJob.Source = field.NewInt(tableName, "source")
	_windowsSigningJob.FinishedTime = field.NewTime(tableName, "finished_time")
	_windowsSigningJob.FinishPeTime = field.NewTime(tableName, "finish_pe_time")
	_windowsSigningJob.Status = field.NewInt(tableName, "status")
	_windowsSigningJob.CreatedTime = field.NewTime(tableName, "created_time")
	_windowsSigningJob.UpdatedTime = field.NewTime(tableName, "updated_time")

	_windowsSigningJob.fillFieldMap()

	return _windowsSigningJob
}

// windowsSigningJob Windows 签名任务表
type windowsSigningJob struct {
	windowsSigningJobDo

	ALL           field.Asterisk
	ID            field.Int    // 自增主码
	JobID         field.String // 任务 ID，前 6 为是年月，后面是 UUID
	Type          field.Int    // 类型，1=PE 签名、2=微软 Attestation 签名、3=PE+微软 Attestation 签名、4=HLKX 文件签名
	AppID         field.Int    // 所属应用 ID
	UserID        field.Int    // 提交人 ID
	CertificateID field.Int    // Windows 证书表 ID
	FileID        field.String // 待签名文件 ID
	SignedFileID  field.String // 已签名文件 ID
	Log           field.String // 任务日志
	ProductID     field.String // 微软侧的 ID
	SubmissionID  field.String // 微软侧的 ID
	Source        field.Int    // 来源，1=页面，2=OpenAPI、3=内部
	FinishedTime  field.Time   // 结束时间
	FinishPeTime  field.Time   // 完成 PE 签名时间
	Status        field.Int    // 状态，1=签名中、2=等待 Cab 签名、3=Cab 签名中、4=待 Attestation 签名、5=Attestation 签名中、6=失败、7=成功
	CreatedTime   field.Time   // 提交时间
	UpdatedTime   field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (w windowsSigningJob) Table(newTableName string) *windowsSigningJob {
	w.windowsSigningJobDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w windowsSigningJob) As(alias string) *windowsSigningJob {
	w.windowsSigningJobDo.DO = *(w.windowsSigningJobDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *windowsSigningJob) updateTableName(table string) *windowsSigningJob {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt(table, "id")
	w.JobID = field.NewString(table, "job_id")
	w.Type = field.NewInt(table, "type")
	w.AppID = field.NewInt(table, "app_id")
	w.UserID = field.NewInt(table, "user_id")
	w.CertificateID = field.NewInt(table, "certificate_id")
	w.FileID = field.NewString(table, "file_id")
	w.SignedFileID = field.NewString(table, "signed_file_id")
	w.Log = field.NewString(table, "log")
	w.ProductID = field.NewString(table, "product_id")
	w.SubmissionID = field.NewString(table, "submission_id")
	w.Source = field.NewInt(table, "source")
	w.FinishedTime = field.NewTime(table, "finished_time")
	w.FinishPeTime = field.NewTime(table, "finish_pe_time")
	w.Status = field.NewInt(table, "status")
	w.CreatedTime = field.NewTime(table, "created_time")
	w.UpdatedTime = field.NewTime(table, "updated_time")

	w.fillFieldMap()

	return w
}

func (w *windowsSigningJob) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *windowsSigningJob) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 17)
	w.fieldMap["id"] = w.ID
	w.fieldMap["job_id"] = w.JobID
	w.fieldMap["type"] = w.Type
	w.fieldMap["app_id"] = w.AppID
	w.fieldMap["user_id"] = w.UserID
	w.fieldMap["certificate_id"] = w.CertificateID
	w.fieldMap["file_id"] = w.FileID
	w.fieldMap["signed_file_id"] = w.SignedFileID
	w.fieldMap["log"] = w.Log
	w.fieldMap["product_id"] = w.ProductID
	w.fieldMap["submission_id"] = w.SubmissionID
	w.fieldMap["source"] = w.Source
	w.fieldMap["finished_time"] = w.FinishedTime
	w.fieldMap["finish_pe_time"] = w.FinishPeTime
	w.fieldMap["status"] = w.Status
	w.fieldMap["created_time"] = w.CreatedTime
	w.fieldMap["updated_time"] = w.UpdatedTime
}

func (w windowsSigningJob) clone(db *gorm.DB) windowsSigningJob {
	w.windowsSigningJobDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w windowsSigningJob) replaceDB(db *gorm.DB) windowsSigningJob {
	w.windowsSigningJobDo.ReplaceDB(db)
	return w
}

type windowsSigningJobDo struct{ gen.DO }

type IWindowsSigningJobDo interface {
	gen.SubQuery
	Debug() IWindowsSigningJobDo
	WithContext(ctx context.Context) IWindowsSigningJobDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWindowsSigningJobDo
	WriteDB() IWindowsSigningJobDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWindowsSigningJobDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWindowsSigningJobDo
	Not(conds ...gen.Condition) IWindowsSigningJobDo
	Or(conds ...gen.Condition) IWindowsSigningJobDo
	Select(conds ...field.Expr) IWindowsSigningJobDo
	Where(conds ...gen.Condition) IWindowsSigningJobDo
	Order(conds ...field.Expr) IWindowsSigningJobDo
	Distinct(cols ...field.Expr) IWindowsSigningJobDo
	Omit(cols ...field.Expr) IWindowsSigningJobDo
	Join(table schema.Tabler, on ...field.Expr) IWindowsSigningJobDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWindowsSigningJobDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWindowsSigningJobDo
	Group(cols ...field.Expr) IWindowsSigningJobDo
	Having(conds ...gen.Condition) IWindowsSigningJobDo
	Limit(limit int) IWindowsSigningJobDo
	Offset(offset int) IWindowsSigningJobDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWindowsSigningJobDo
	Unscoped() IWindowsSigningJobDo
	Create(values ...*model.WindowsSigningJob) error
	CreateInBatches(values []*model.WindowsSigningJob, batchSize int) error
	Save(values ...*model.WindowsSigningJob) error
	First() (*model.WindowsSigningJob, error)
	Take() (*model.WindowsSigningJob, error)
	Last() (*model.WindowsSigningJob, error)
	Find() ([]*model.WindowsSigningJob, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WindowsSigningJob, err error)
	FindInBatches(result *[]*model.WindowsSigningJob, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WindowsSigningJob) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWindowsSigningJobDo
	Assign(attrs ...field.AssignExpr) IWindowsSigningJobDo
	Joins(fields ...field.RelationField) IWindowsSigningJobDo
	Preload(fields ...field.RelationField) IWindowsSigningJobDo
	FirstOrInit() (*model.WindowsSigningJob, error)
	FirstOrCreate() (*model.WindowsSigningJob, error)
	FindByPage(offset int, limit int) (result []*model.WindowsSigningJob, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWindowsSigningJobDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetTables(db string) (result []string, err error)
	List(tables []string, appID int, keyWord string, signingType int, status int, certificateIDs []int, userIDs []int, limit int, offset int) (result []*model.WindowsSigningJob, err error)
	Count2(tables []string, appID int, keyWord string, signingType int, status int, certificateIDs []int, userIDs []int) (result int, err error)
	CountWithDay(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	CountWithWeek(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	CountWithMonth(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	CostWithDay(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	CostWithWeek(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	CostWithMonth(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	PassRateWithDay(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	PassRateWithWeek(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	PassRateWithMonth(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error)
	GetJobIDByStatus(tables []string, status int) (result []string, err error)
}

// select TABLE_NAME from information_schema.TABLES where TABLE_SCHEMA = @db
// and TABLE_NAME like 't_windows_signing_job%'
func (w windowsSigningJobDo) GetTables(db string) (result []string, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, db)
	generateSQL.WriteString("select TABLE_NAME from information_schema.TABLES where TABLE_SCHEMA = ? and TABLE_NAME like 't_windows_signing_job%' ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select * from (
// {{ for i, t := range tables }}
//
//	select * from @@t {{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// where t.app_id = @appID and t.source in (1, 2)
// {{ if signingType > 0 }} and t.type = @signingType {{ end }}
// {{ if status > 0 }} and t.status = @status {{ end }}
// {{ if len(keyWord) > 0 }}
//
//	and (
//	  t.job_id = @keyWord or t.file_id = @keyWord or t.signed_file_id = @keyWord
//	  {{ if len(certificateIDs) > 0 }} or t.certificate_id in (@certificateIDs) {{ end }}
//	  {{ if len(userIDs) > 0 }} or t.user_id in (@userIDs) {{ end }}
//	)
//
// {{ end }}
// order by t.created_time desc, t.id desc limit @limit offset @offset
func (w windowsSigningJobDo) List(tables []string, appID int, keyWord string, signingType int, status int, certificateIDs []int, userIDs []int, limit int, offset int) (result []*model.WindowsSigningJob, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from ( ")
	for i, t := range tables {
		generateSQL.WriteString("select * from " + w.Quote(t) + " ")
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	params = append(params, appID)
	generateSQL.WriteString(") t where t.app_id = ? and t.source in (1, 2) ")
	if signingType > 0 {
		params = append(params, signingType)
		generateSQL.WriteString("and t.type = ? ")
	}
	if status > 0 {
		params = append(params, status)
		generateSQL.WriteString("and t.status = ? ")
	}
	if len(keyWord) > 0 {
		params = append(params, keyWord)
		params = append(params, keyWord)
		params = append(params, keyWord)
		generateSQL.WriteString("and ( t.job_id = ? or t.file_id = ? or t.signed_file_id = ? ")
		if len(certificateIDs) > 0 {
			params = append(params, certificateIDs)
			generateSQL.WriteString("or t.certificate_id in (?) ")
		}
		if len(userIDs) > 0 {
			params = append(params, userIDs)
			generateSQL.WriteString("or t.user_id in (?) ")
		}
		generateSQL.WriteString(") ")
	}
	params = append(params, limit)
	params = append(params, offset)
	generateSQL.WriteString("order by t.created_time desc, t.id desc limit ? offset ? ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select count(*) from (
// {{ for i, t := range tables }}
//
//	select * from @@t {{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// where t.app_id = @appID and t.source in (1, 2)
// {{ if signingType > 0 }} and t.type = @signingType {{ end }}
// {{ if status > 0 }} and t.status = @status {{ end }}
// {{ if len(keyWord) > 0 }}
//
//	and (
//	  t.job_id = @keyWord or t.file_id = @keyWord or t.signed_file_id = @keyWord
//	  {{ if len(certificateIDs) > 0 }} or t.certificate_id in (@certificateIDs) {{ end }}
//	  {{ if len(userIDs) > 0 }} or t.user_id in (@userIDs) {{ end }}
//	)
//
// {{ end }}
func (w windowsSigningJobDo) Count2(tables []string, appID int, keyWord string, signingType int, status int, certificateIDs []int, userIDs []int) (result int, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select count(*) from ( ")
	for i, t := range tables {
		generateSQL.WriteString("select * from " + w.Quote(t) + " ")
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	params = append(params, appID)
	generateSQL.WriteString(") t where t.app_id = ? and t.source in (1, 2) ")
	if signingType > 0 {
		params = append(params, signingType)
		generateSQL.WriteString("and t.type = ? ")
	}
	if status > 0 {
		params = append(params, status)
		generateSQL.WriteString("and t.status = ? ")
	}
	if len(keyWord) > 0 {
		params = append(params, keyWord)
		params = append(params, keyWord)
		params = append(params, keyWord)
		generateSQL.WriteString("and ( t.job_id = ? or t.file_id = ? or t.signed_file_id = ? ")
		if len(certificateIDs) > 0 {
			params = append(params, certificateIDs)
			generateSQL.WriteString("or t.certificate_id in (?) ")
		}
		if len(userIDs) > 0 {
			params = append(params, userIDs)
			generateSQL.WriteString("or t.user_id in (?) ")
		}
		generateSQL.WriteString(") ")
	}

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.type `type`, count(*) `count`, date_format(t.created_time, '%Y%m%d') `day` from (
// {{ for i, t := range tables }}
//
//	select * from @@t where created_time between @begin and @end
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//	{{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// group by `day`, `type`
// order by `day`
func (w windowsSigningJobDo) CountWithDay(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.type `type`, count(*) `count`, date_format(t.created_time, '%Y%m%d') `day` from ( ")
	for i, t := range tables {
		params = append(params, begin)
		params = append(params, end)
		generateSQL.WriteString("select * from " + w.Quote(t) + " where created_time between ? and ? ")
		if appID > 0 {
			params = append(params, appID)
			generateSQL.WriteString("and app_id = ? ")
		}
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	generateSQL.WriteString(") t group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.type `type`, count(*) `count`, date_format(date_sub(t.created_time, INTERVAL (dayofweek(t.created_time)-2) DAY), '%Y%m%d') `day` from (
// {{ for i, t := range tables }}
//
//	select * from @@t where created_time between @begin and @end
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//	{{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// group by `day`, `type`
// order by `day`
func (w windowsSigningJobDo) CountWithWeek(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.type `type`, count(*) `count`, date_format(date_sub(t.created_time, INTERVAL (dayofweek(t.created_time)-2) DAY), '%Y%m%d') `day` from ( ")
	for i, t := range tables {
		params = append(params, begin)
		params = append(params, end)
		generateSQL.WriteString("select * from " + w.Quote(t) + " where created_time between ? and ? ")
		if appID > 0 {
			params = append(params, appID)
			generateSQL.WriteString("and app_id = ? ")
		}
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	generateSQL.WriteString(") t group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.type `type`, count(*) `count`, date_format(t.created_time, '%Y%m') `day` from (
// {{ for i, t := range tables }}
//
//	select * from @@t where created_time between @begin and @end
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//	{{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// group by `day`, `type`
// order by `day`
func (w windowsSigningJobDo) CountWithMonth(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.type `type`, count(*) `count`, date_format(t.created_time, '%Y%m') `day` from ( ")
	for i, t := range tables {
		params = append(params, begin)
		params = append(params, end)
		generateSQL.WriteString("select * from " + w.Quote(t) + " where created_time between ? and ? ")
		if appID > 0 {
			params = append(params, appID)
			generateSQL.WriteString("and app_id = ? ")
		}
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	generateSQL.WriteString(") t group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.type `type`, date_format(t.created_time, '%Y%m%d') `day`, cast(round(avg(timestampdiff(SECOND, t.created_time, ifnull(t.finished_time, now()))), 0) as signed) `cost` from (
// {{ for i, t := range tables }}
//
//	select * from @@t where created_time between @begin and @end and status in (6, 7)
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//	{{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// group by `day`, `type`
// order by `day`
func (w windowsSigningJobDo) CostWithDay(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.type `type`, date_format(t.created_time, '%Y%m%d') `day`, cast(round(avg(timestampdiff(SECOND, t.created_time, ifnull(t.finished_time, now()))), 0) as signed) `cost` from ( ")
	for i, t := range tables {
		params = append(params, begin)
		params = append(params, end)
		generateSQL.WriteString("select * from " + w.Quote(t) + " where created_time between ? and ? and status in (6, 7) ")
		if appID > 0 {
			params = append(params, appID)
			generateSQL.WriteString("and app_id = ? ")
		}
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	generateSQL.WriteString(") t group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.type `type`, date_format(date_sub(t.created_time, INTERVAL (dayofweek(t.created_time)-2) DAY), '%Y%m%d') `day`, cast(round(avg(timestampdiff(SECOND, t.created_time, ifnull(t.finished_time, now()))), 0) as signed) `cost` from (
// {{ for i, t := range tables }}
//
//	select * from @@t where created_time between @begin and @end and status in (6, 7)
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//	{{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// group by `day`, `type`
// order by `day`
func (w windowsSigningJobDo) CostWithWeek(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.type `type`, date_format(date_sub(t.created_time, INTERVAL (dayofweek(t.created_time)-2) DAY), '%Y%m%d') `day`, cast(round(avg(timestampdiff(SECOND, t.created_time, ifnull(t.finished_time, now()))), 0) as signed) `cost` from ( ")
	for i, t := range tables {
		params = append(params, begin)
		params = append(params, end)
		generateSQL.WriteString("select * from " + w.Quote(t) + " where created_time between ? and ? and status in (6, 7) ")
		if appID > 0 {
			params = append(params, appID)
			generateSQL.WriteString("and app_id = ? ")
		}
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	generateSQL.WriteString(") t group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.type `type`, date_format(t.created_time, '%Y%m') `day`, cast(round(avg(timestampdiff(SECOND, t.created_time, ifnull(t.finished_time, now()))), 0) as signed) `cost` from (
// {{ for i, t := range tables }}
//
//	select * from @@t where created_time between @begin and @end and status in (6, 7)
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//	{{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// group by `day`, `type`
// order by `day`
func (w windowsSigningJobDo) CostWithMonth(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.type `type`, date_format(t.created_time, '%Y%m') `day`, cast(round(avg(timestampdiff(SECOND, t.created_time, ifnull(t.finished_time, now()))), 0) as signed) `cost` from ( ")
	for i, t := range tables {
		params = append(params, begin)
		params = append(params, end)
		generateSQL.WriteString("select * from " + w.Quote(t) + " where created_time between ? and ? and status in (6, 7) ")
		if appID > 0 {
			params = append(params, appID)
			generateSQL.WriteString("and app_id = ? ")
		}
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	generateSQL.WriteString(") t group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.type `type`, date_format(t.created_time, '%Y%m%d') `day`, cast(round(sum(case t.status when 7 then 1 else 0 end) * 10000 / count(*), 0) as signed) `rate` from (
// {{ for i, t := range tables }}
//
//	select * from @@t where created_time between @begin and @end and status in (6, 7)
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//	{{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// group by `day`, `type`
// order by `day`
func (w windowsSigningJobDo) PassRateWithDay(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.type `type`, date_format(t.created_time, '%Y%m%d') `day`, cast(round(sum(case t.status when 7 then 1 else 0 end) * 10000 / count(*), 0) as signed) `rate` from ( ")
	for i, t := range tables {
		params = append(params, begin)
		params = append(params, end)
		generateSQL.WriteString("select * from " + w.Quote(t) + " where created_time between ? and ? and status in (6, 7) ")
		if appID > 0 {
			params = append(params, appID)
			generateSQL.WriteString("and app_id = ? ")
		}
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	generateSQL.WriteString(") t group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.type `type`, date_format(date_sub(t.created_time, INTERVAL (dayofweek(t.created_time)-2) DAY), '%Y%m%d') `day`, cast(round(sum(case t.status when 7 then 1 else 0 end) * 10000 / count(*), 0) as signed) `rate` from (
// {{ for i, t := range tables }}
//
//	select * from @@t where created_time between @begin and @end and status in (6, 7)
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//	{{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// group by `day`, `type`
// order by `day`
func (w windowsSigningJobDo) PassRateWithWeek(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.type `type`, date_format(date_sub(t.created_time, INTERVAL (dayofweek(t.created_time)-2) DAY), '%Y%m%d') `day`, cast(round(sum(case t.status when 7 then 1 else 0 end) * 10000 / count(*), 0) as signed) `rate` from ( ")
	for i, t := range tables {
		params = append(params, begin)
		params = append(params, end)
		generateSQL.WriteString("select * from " + w.Quote(t) + " where created_time between ? and ? and status in (6, 7) ")
		if appID > 0 {
			params = append(params, appID)
			generateSQL.WriteString("and app_id = ? ")
		}
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	generateSQL.WriteString(") t group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.type `type`, date_format(t.created_time, '%Y%m') `day`, cast(round(sum(case t.status when 7 then 1 else 0 end) * 10000 / count(*), 0) as signed) `rate` from (
// {{ for i, t := range tables }}
//
//	select * from @@t where created_time between @begin and @end and status in (6, 7)
//	{{ if appID > 0 }} and app_id = @appID {{ end }}
//	{{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// group by `day`, `type`
// order by `day`
func (w windowsSigningJobDo) PassRateWithMonth(tables []string, appID int, begin time.Time, end time.Time) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.type `type`, date_format(t.created_time, '%Y%m') `day`, cast(round(sum(case t.status when 7 then 1 else 0 end) * 10000 / count(*), 0) as signed) `rate` from ( ")
	for i, t := range tables {
		params = append(params, begin)
		params = append(params, end)
		generateSQL.WriteString("select * from " + w.Quote(t) + " where created_time between ? and ? and status in (6, 7) ")
		if appID > 0 {
			params = append(params, appID)
			generateSQL.WriteString("and app_id = ? ")
		}
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	generateSQL.WriteString(") t group by `day`, `type` order by `day` ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// select t.job_id from (
// {{ for i, t := range tables }}
//
//	select * from @@t {{ if len(tables) - 1 != i }} union all {{ end }}
//
// {{ end }} ) t
// where t.status = @status
func (w windowsSigningJobDo) GetJobIDByStatus(tables []string, status int) (result []string, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select t.job_id from ( ")
	for i, t := range tables {
		generateSQL.WriteString("select * from " + w.Quote(t) + " ")
		if len(tables)-1 != i {
			generateSQL.WriteString("union all ")
		}
	}
	params = append(params, status)
	generateSQL.WriteString(") t where t.status = ? ")

	var executeSQL *gorm.DB
	executeSQL = w.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (w windowsSigningJobDo) Debug() IWindowsSigningJobDo {
	return w.withDO(w.DO.Debug())
}

func (w windowsSigningJobDo) WithContext(ctx context.Context) IWindowsSigningJobDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w windowsSigningJobDo) ReadDB() IWindowsSigningJobDo {
	return w.Clauses(dbresolver.Read)
}

func (w windowsSigningJobDo) WriteDB() IWindowsSigningJobDo {
	return w.Clauses(dbresolver.Write)
}

func (w windowsSigningJobDo) Session(config *gorm.Session) IWindowsSigningJobDo {
	return w.withDO(w.DO.Session(config))
}

func (w windowsSigningJobDo) Clauses(conds ...clause.Expression) IWindowsSigningJobDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w windowsSigningJobDo) Returning(value interface{}, columns ...string) IWindowsSigningJobDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w windowsSigningJobDo) Not(conds ...gen.Condition) IWindowsSigningJobDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w windowsSigningJobDo) Or(conds ...gen.Condition) IWindowsSigningJobDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w windowsSigningJobDo) Select(conds ...field.Expr) IWindowsSigningJobDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w windowsSigningJobDo) Where(conds ...gen.Condition) IWindowsSigningJobDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w windowsSigningJobDo) Order(conds ...field.Expr) IWindowsSigningJobDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w windowsSigningJobDo) Distinct(cols ...field.Expr) IWindowsSigningJobDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w windowsSigningJobDo) Omit(cols ...field.Expr) IWindowsSigningJobDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w windowsSigningJobDo) Join(table schema.Tabler, on ...field.Expr) IWindowsSigningJobDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w windowsSigningJobDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWindowsSigningJobDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w windowsSigningJobDo) RightJoin(table schema.Tabler, on ...field.Expr) IWindowsSigningJobDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w windowsSigningJobDo) Group(cols ...field.Expr) IWindowsSigningJobDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w windowsSigningJobDo) Having(conds ...gen.Condition) IWindowsSigningJobDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w windowsSigningJobDo) Limit(limit int) IWindowsSigningJobDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w windowsSigningJobDo) Offset(offset int) IWindowsSigningJobDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w windowsSigningJobDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWindowsSigningJobDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w windowsSigningJobDo) Unscoped() IWindowsSigningJobDo {
	return w.withDO(w.DO.Unscoped())
}

func (w windowsSigningJobDo) Create(values ...*model.WindowsSigningJob) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w windowsSigningJobDo) CreateInBatches(values []*model.WindowsSigningJob, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w windowsSigningJobDo) Save(values ...*model.WindowsSigningJob) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w windowsSigningJobDo) First() (*model.WindowsSigningJob, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WindowsSigningJob), nil
	}
}

func (w windowsSigningJobDo) Take() (*model.WindowsSigningJob, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WindowsSigningJob), nil
	}
}

func (w windowsSigningJobDo) Last() (*model.WindowsSigningJob, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WindowsSigningJob), nil
	}
}

func (w windowsSigningJobDo) Find() ([]*model.WindowsSigningJob, error) {
	result, err := w.DO.Find()
	return result.([]*model.WindowsSigningJob), err
}

func (w windowsSigningJobDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WindowsSigningJob, err error) {
	buf := make([]*model.WindowsSigningJob, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w windowsSigningJobDo) FindInBatches(result *[]*model.WindowsSigningJob, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w windowsSigningJobDo) Attrs(attrs ...field.AssignExpr) IWindowsSigningJobDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w windowsSigningJobDo) Assign(attrs ...field.AssignExpr) IWindowsSigningJobDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w windowsSigningJobDo) Joins(fields ...field.RelationField) IWindowsSigningJobDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w windowsSigningJobDo) Preload(fields ...field.RelationField) IWindowsSigningJobDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w windowsSigningJobDo) FirstOrInit() (*model.WindowsSigningJob, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WindowsSigningJob), nil
	}
}

func (w windowsSigningJobDo) FirstOrCreate() (*model.WindowsSigningJob, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WindowsSigningJob), nil
	}
}

func (w windowsSigningJobDo) FindByPage(offset int, limit int) (result []*model.WindowsSigningJob, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w windowsSigningJobDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w windowsSigningJobDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w windowsSigningJobDo) Delete(models ...*model.WindowsSigningJob) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *windowsSigningJobDo) withDO(do gen.Dao) *windowsSigningJobDo {
	w.DO = *do.(*gen.DO)
	return w
}
