// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAesKey = "t_aes_key"

// AesKey 证书加密密钥表
type AesKey struct {
	ID          int       `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                   // 自增主码
	Secret      []byte    `gorm:"column:secret;type:binary(16);not null;comment:密钥" json:"secret"`                                        // 密钥
	CreatedTime time.Time `gorm:"column:created_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_time"` // 创建时间
}

// TableName AesKey's table name
func (*AesKey) TableName() string {
	return TableNameAesKey
}
