// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAndroidCertificate = "t_android_certificate"

// AndroidCertificate 安卓证书信息表
type AndroidCertificate struct {
	ID                 int       `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                                       // 自增主码
	CertificateID      string    `gorm:"column:certificate_id;type:char(32);not null;uniqueIndex:uidx_certificate_id,priority:1;comment:唯一标识" json:"certificate_id"` // 唯一标识
	AppID              int       `gorm:"column:app_id;type:int(11) unsigned;not null;index:idx_app_id,priority:1;comment:所属应用 ID" json:"app_id"`                     // 所属应用 ID
	UserID             int       `gorm:"column:user_id;type:int(11) unsigned;not null;comment:创建人 ID" json:"user_id"`                                                // 创建人 ID
	Alias_             string    `gorm:"column:alias;type:varchar(64);not null;comment:别名" json:"alias"`                                                             // 别名
	Category           int       `gorm:"column:category;type:tinyint(4) unsigned;not null;comment:类型，1=调试、2=发布" json:"category"`                                     // 类型，1=调试、2=发布
	Publisher          string    `gorm:"column:publisher;type:varchar(1024);comment:颁发者" json:"publisher"`                                                           // 颁发者
	Owner              string    `gorm:"column:owner;type:varchar(1024);comment:所有者" json:"owner"`                                                                   // 所有者
	SignatureAlgorithm string    `gorm:"column:signature_algorithm;type:varchar(64);comment:签名算法" json:"signature_algorithm"`                                        // 签名算法
	PublicKeyAlgorithm string    `gorm:"column:public_key_algorithm;type:varchar(64);comment:公钥密码算法" json:"public_key_algorithm"`                                    // 公钥密码算法
	Version            string    `gorm:"column:version;type:varchar(32);comment:版本号" json:"version"`                                                                 // 版本号
	SerialNumber       string    `gorm:"column:serial_number;type:varchar(64);comment:序列号" json:"serial_number"`                                                     // 序列号
	StoreProvider      string    `gorm:"column:store_provider;type:varchar(64);comment:证书提供方" json:"store_provider"`                                                 // 证书提供方
	StoreType          string    `gorm:"column:store_type;type:varchar(64);comment:证书格式类型" json:"store_type"`                                                        // 证书格式类型
	CreationDate       time.Time `gorm:"column:creation_date;type:date;comment:证书创建时间" json:"creation_date"`                                                         // 证书创建时间
	Sha1               string    `gorm:"column:sha1;type:char(40);comment:证书 SHA1 摘要值" json:"sha1"`                                                                  // 证书 SHA1 摘要值
	Sha256             string    `gorm:"column:sha256;type:char(64);comment:证书 SHA256 摘要值" json:"sha256"`                                                            // 证书 SHA256 摘要值
	Storepass          string    `gorm:"column:storepass;type:varchar(32);not null;comment:密钥库解密密码" json:"storepass"`                                                // 密钥库解密密码
	Keypass            string    `gorm:"column:keypass;type:varchar(32);not null;comment:私钥解密密码" json:"keypass"`                                                     // 私钥解密密码
	NotBefore          time.Time `gorm:"column:not_before;type:datetime;not null;comment:生效时间" json:"not_before"`                                                    // 生效时间
	NotAfter           time.Time `gorm:"column:not_after;type:datetime;not null;comment:失效时间" json:"not_after"`                                                      // 失效时间
	AesKeyID           int       `gorm:"column:aes_key_id;type:int(11) unsigned;not null;comment:证书加密密钥 ID" json:"aes_key_id"`                                       // 证书加密密钥 ID
	Content            []byte    `gorm:"column:content;type:mediumblob binary;not null;comment:加密了的密钥库" json:"content"`                                              // 加密了的密钥库
	CreatedTime        time.Time `gorm:"column:created_time;type:timestamp;not null;comment:创建时间" json:"created_time"`                                               // 创建时间
	DeletedTime        time.Time `gorm:"column:deleted_time;type:timestamp;comment:删除时间" json:"deleted_time"`                                                        // 删除时间
}

// TableName AndroidCertificate's table name
func (*AndroidCertificate) TableName() string {
	return TableNameAndroidCertificate
}
