// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAndroidOrganization = "t_android_organization"

// AndroidOrganization 安卓证书主体表
type AndroidOrganization struct {
	ID          int       `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`     // 自增主码
	Name        string    `gorm:"column:name;type:varchar(32);not null;comment:通用名 CN" json:"name"`                         // 通用名 CN
	UserID      int       `gorm:"column:user_id;type:int(11) unsigned;not null;comment:添加人 ID" json:"user_id"`              // 添加人 ID
	Owner       string    `gorm:"column:owner;type:varchar(256);not null;comment:所有者，用于 keytool 中的 dname 参数值" json:"owner"` // 所有者，用于 keytool 中的 dname 参数值
	CreatedTime time.Time `gorm:"column:created_time;type:timestamp;not null;comment:创建时间" json:"created_time"`             // 创建时间
}

// TableName AndroidOrganization's table name
func (*AndroidOrganization) TableName() string {
	return TableNameAndroidOrganization
}
