// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAppleBundleID = "t_apple_bundle_id"

// AppleBundleID BundleID 信息表
type AppleBundleID struct {
	ID           int        `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                                               // 自增主码
	AppID        int        `gorm:"column:app_id;type:int(11) unsigned;not null;index:idx_app_id,priority:1;comment:所属应用 ID" json:"app_id"`                             // 所属应用 ID
	UserID       int        `gorm:"column:user_id;type:int(11) unsigned;not null;comment:申请人 ID" json:"user_id"`                                                        // 申请人 ID
	InAppleID    string     `gorm:"column:in_apple_id;type:char(10);not null;comment:在苹果服务中的 ID" json:"in_apple_id"`                                                    // 在苹果服务中的 ID
	BundleID     string     `gorm:"column:bundle_id;type:varchar(64);not null;uniqueIndex:uidx_bundle_id,priority:1;comment:Apple 应用唯一标识，域名倒置点号分隔的形式" json:"bundle_id"` // Apple 应用唯一标识，域名倒置点号分隔的形式
	Environment  int        `gorm:"column:environment;type:tinyint(4) unsigned;not null;comment:环境，1=AppStore，2=企业内测" json:"environment"`                               // 环境，1=AppStore，2=企业内测
	Platform     int        `gorm:"column:platform;type:tinyint(4) unsigned;not null;comment:平台，1=IOS、2=MAC_OS、3=UNIVERSAL" json:"platform"`                            // 平台，1=IOS、2=MAC_OS、3=UNIVERSAL
	Capabilities StringList `gorm:"column:capabilities;type:mediumtext;comment:BundleID 的能力项，以英文逗号分隔" json:"capabilities"`                                              // BundleID 的能力项，以英文逗号分隔
	CreatedTime  time.Time  `gorm:"column:created_time;type:timestamp;not null;comment:创建时间" json:"created_time"`                                                       // 创建时间
	UpdatedTime  time.Time  `gorm:"column:updated_time;type:timestamp;comment:更新时间" json:"updated_time"`                                                                // 更新时间
}

// TableName AppleBundleID's table name
func (*AppleBundleID) TableName() string {
	return TableNameAppleBundleID
}
