// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAPIAuthorization = "t_api_authorization"

// APIAuthorization OpenAPI 凭证授权表
type APIAuthorization struct {
	ID           int `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                                           // 自增主码
	APIAccountID int `gorm:"column:api_account_id;type:int(11) unsigned;index:idx_api_account_id,priority:1;comment:OpenAPI 凭证信息表 ID" json:"api_account_id"` // OpenAPI 凭证信息表 ID
	Capability   int `gorm:"column:capability;type:tinyint(4) unsigned;not null;comment:权限项，对应表 3-5" json:"capability"`                                      // 权限项，对应表 3-5
}

// TableName APIAuthorization's table name
func (*APIAuthorization) TableName() string {
	return TableNameAPIAuthorization
}
