// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAppleCertificate = "t_apple_certificate"

// AppleCertificate 苹果相关证书信息表
type AppleCertificate struct {
	ID                 int       `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                                       // 自增主码
	CertificateID      string    `gorm:"column:certificate_id;type:char(32);not null;uniqueIndex:uidx_certificate_id,priority:1;comment:唯一标识" json:"certificate_id"` // 唯一标识
	AppID              int       `gorm:"column:app_id;type:int(11) unsigned;index:idx_app_id,priority:1;comment:Push 证书所属应用 ID" json:"app_id"`                       // Push 证书所属应用 ID
	UserID             int       `gorm:"column:user_id;type:int(11) unsigned;not null;comment:创建人 ID" json:"user_id"`                                                // 创建人 ID
	InAppleID          string    `gorm:"column:in_apple_id;type:char(10);not null;comment:在苹果服务器的 ID" json:"in_apple_id"`                                            // 在苹果服务器的 ID
	Environment        int       `gorm:"column:environment;type:tinyint(4) unsigned;comment:Push 证书环境，1=正式、2=开发、3=企业内测" json:"environment"`                          // Push 证书环境，1=正式、2=开发、3=企业内测
	BundleID           int       `gorm:"column:bundle_id;type:int(11) unsigned;comment:Push 证书对应的 BundleID" json:"bundle_id"`                                        // Push 证书对应的 BundleID
	Category           int       `gorm:"column:category;type:tinyint(4) unsigned;not null;comment:文件类型，1=签名证书、2=Push 证书" json:"category"`                            // 文件类型，1=签名证书、2=Push 证书
	Type               string    `gorm:"column:type;type:varchar(32);comment:签名证书类型，由苹果 API 中定义，例如：IOS_DEVELOPMENT" json:"type"`                                     // 签名证书类型，由苹果 API 中定义，例如：IOS_DEVELOPMENT
	Password           string    `gorm:"column:password;type:varchar(16);not null;comment:密码" json:"password"`                                                       // 密码
	Publisher          string    `gorm:"column:publisher;type:varchar(1024);comment:颁发者" json:"publisher"`                                                           // 颁发者
	Owner              string    `gorm:"column:owner;type:varchar(1024);comment:所有者" json:"owner"`                                                                   // 所有者
	SignatureAlgorithm string    `gorm:"column:signature_algorithm;type:varchar(64);comment:签名算法" json:"signature_algorithm"`                                        // 签名算法
	PublicKeyAlgorithm string    `gorm:"column:public_key_algorithm;type:varchar(64);comment:公钥密码算法" json:"public_key_algorithm"`                                    // 公钥密码算法
	SerialNumber       string    `gorm:"column:serial_number;type:varchar(64);comment:序列号" json:"serial_number"`                                                     // 序列号
	NotBefore          time.Time `gorm:"column:not_before;type:datetime;not null;comment:生效时间" json:"not_before"`                                                    // 生效时间
	AesKeyID           int       `gorm:"column:aes_key_id;type:int(11) unsigned;not null;comment:证书加密密钥 ID" json:"aes_key_id"`                                       // 证书加密密钥 ID
	NotAfter           time.Time `gorm:"column:not_after;type:datetime;not null;comment:失效时间" json:"not_after"`                                                      // 失效时间
	Content            []byte    `gorm:"column:content;type:mediumblob binary;not null;comment:加密了的证书内容" json:"content"`                                             // 加密了的证书内容
	CreatedTime        time.Time `gorm:"column:created_time;type:timestamp;not null;comment:创建时间" json:"created_time"`                                               // 创建时间
	DeletedTime        time.Time `gorm:"column:deleted_time;type:timestamp;comment:删除时间" json:"deleted_time"`                                                        // 删除时间
}

// TableName AppleCertificate's table name
func (*AppleCertificate) TableName() string {
	return TableNameAppleCertificate
}
