// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAppleDevice = "t_apple_device"

// AppleDevice 苹果测试设备信息表
type AppleDevice struct {
	ID          int       `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                   // 自增主码
	AppID       int       `gorm:"column:app_id;type:int(11) unsigned;not null;index:idx_app_id,priority:1;comment:所属应用 ID" json:"app_id"` // 所属应用 ID
	UserID      int       `gorm:"column:user_id;type:int(11) unsigned;not null;comment:申请人 ID" json:"user_id"`                            // 申请人 ID
	InAppleID   string    `gorm:"column:in_apple_id;type:char(10);comment:在苹果服务器中的 ID" json:"in_apple_id"`                                // 在苹果服务器中的 ID
	Udid        string    `gorm:"column:udid;type:varchar(128);not null;comment:设备 ID" json:"udid"`                                       // 设备 ID
	Model       string    `gorm:"column:model;type:varchar(32);comment:设备型号" json:"model"`                                                // 设备型号
	Remark      string    `gorm:"column:remark;type:varchar(1024);comment:备注" json:"remark"`                                              // 备注
	Platform    string    `gorm:"column:platform;type:varchar(64);not null;comment:平台" json:"platform"`                                   // 平台
	Status      int       `gorm:"column:status;type:tinyint(4) unsigned;not null;comment:状态，1=正常、2=待审核、3=未通过" json:"status"`              // 状态，1=正常、2=待审核、3=未通过
	CreatedTime time.Time `gorm:"column:created_time;type:timestamp;not null;comment:创建时间" json:"created_time"`                           // 创建时间
	UpdatedTime time.Time `gorm:"column:updated_time;type:timestamp;comment:更新时间" json:"updated_time"`                                    // 更新时间
}

// TableName AppleDevice's table name
func (*AppleDevice) TableName() string {
	return TableNameAppleDevice
}
