// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApp = "t_app"

// App 应用信息表
type App struct {
	ID          int       `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                                        // 自增主码
	AppID       string    `gorm:"column:app_id;type:char(32);not null;uniqueIndex:uidx_app_id,priority:1;comment:唯一标识" json:"app_id"`                          // 唯一标识
	UserID      int       `gorm:"column:user_id;type:int(11) unsigned;not null;comment:创建人 ID" json:"user_id"`                                                 // 创建人 ID
	Name        string    `gorm:"column:name;type:varchar(64);not null;comment:应用名" json:"name"`                                                               // 应用名
	LogoFileID  string    `gorm:"column:logo_file_id;type:char(38);not null;comment:图标文件 ID" json:"logo_file_id"`                                              // 图标文件 ID
	Platform    int       `gorm:"column:platform;type:tinyint(4) unsigned;not null;comment:平台，1=Windows、2=Apple、3=Android" json:"platform"`                    // 平台，1=Windows、2=Apple、3=Android
	Status      int       `gorm:"column:status;type:tinyint(4) unsigned;not null;index:idx_status,priority:1;comment:状态，1=有效、2=无效、3=审批中、4=审批驳回" json:"status"` // 状态，1=有效、2=无效、3=审批中、4=审批驳回
	CreatedTime time.Time `gorm:"column:created_time;type:timestamp;not null;comment:注册时间" json:"created_time"`                                                // 注册时间
	UpdatedTime time.Time `gorm:"column:updated_time;type:timestamp;comment:更新时间" json:"updated_time"`                                                         // 更新时间
}

// TableName App's table name
func (*App) TableName() string {
	return TableNameApp
}
