// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAppleSigningJob = "t_apple_signing_job"

// AppleSigningJob 苹果签名任务表
type AppleSigningJob struct {
	ID           int       `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                                  // 自增主码
	JobID        string    `gorm:"column:job_id;type:char(38);not null;uniqueIndex:uidx_job_id,priority:1;comment:任务 ID，前 6 为是年月，后面是 UUID" json:"job_id"` // 任务 ID，前 6 为是年月，后面是 UUID
	AppID        int       `gorm:"column:app_id;type:int(11) unsigned;not null;index:idx_app_id,priority:1;comment:所属应用 ID" json:"app_id"`                // 所属应用 ID
	UserID       int       `gorm:"column:user_id;type:int(11) unsigned;not null;comment:提交人 ID" json:"user_id"`                                           // 提交人 ID
	ProfileID    int       `gorm:"column:profile_id;type:int(11) unsigned;not null;comment:描述文件表 ID" json:"profile_id"`                                   // 描述文件表 ID
	FileID       string    `gorm:"column:file_id;type:char(38);not null;comment:待签名文件 ID" json:"file_id"`                                                 // 待签名文件 ID
	SignedFileID string    `gorm:"column:signed_file_id;type:char(38);comment:已签名文件 ID" json:"signed_file_id"`                                            // 已签名文件 ID
	Log          string    `gorm:"column:log;type:mediumtext;comment:任务日志" json:"log"`                                                                    // 任务日志
	Source       int       `gorm:"column:source;type:tinyint(4) unsigned;not null;comment:来源，1=页面、2=OpenAPI" json:"source"`                               // 来源，1=页面、2=OpenAPI
	FinishedTime time.Time `gorm:"column:finished_time;type:timestamp;comment:结束时间" json:"finished_time"`                                                 // 结束时间
	Status       int       `gorm:"column:status;type:tinyint(4) unsigned;not null;comment:状态，1=进行中、2=成功、3=失败" json:"status"`                              // 状态，1=进行中、2=成功、3=失败
	CreatedTime  time.Time `gorm:"column:created_time;type:timestamp;not null;index:idx_created_time,priority:1;comment:提交时间" json:"created_time"`        // 提交时间
}

// TableName AppleSigningJob's table name
func (*AppleSigningJob) TableName() string {
	return TableNameAppleSigningJob
}
