// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAppleProfile = "t_apple_profile"

// AppleProfile 苹果描述文件信息表
type AppleProfile struct {
	ID            int       `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                           // 自增主码
	ProfileID     string    `gorm:"column:profile_id;type:char(32);not null;uniqueIndex:uidx_profile_id,priority:1;comment:唯一标识" json:"profile_id"` // 唯一标识
	AppID         int       `gorm:"column:app_id;type:int(11) unsigned;not null;index:idx_app_id,priority:1;comment:所属应用 ID" json:"app_id"`         // 所属应用 ID
	UserID        int       `gorm:"column:user_id;type:int(11) unsigned;not null;comment:创建人 ID" json:"user_id"`                                    // 创建人 ID
	CertificateID int       `gorm:"column:certificate_id;type:int(11) unsigned;not null;comment:证书表 ID，根据该证书申请的描述文件" json:"certificate_id"`         // 证书表 ID，根据该证书申请的描述文件
	InAppleID     string    `gorm:"column:in_apple_id;type:char(10);not null;comment:在苹果服务器的 ID" json:"in_apple_id"`                                // 在苹果服务器的 ID
	BundleID      int       `gorm:"column:bundle_id;type:int(11) unsigned;comment:描述文件对应的 BundleID" json:"bundle_id"`                               // 描述文件对应的 BundleID
	Text          string    `gorm:"column:text;type:text;not null;comment:描述文件中的 XML 内容" json:"text"`                                               // 描述文件中的 XML 内容
	Type          string    `gorm:"column:type;type:varchar(32);not null;comment:描述文件类型，由苹果 API 中定义，例如：IOS_APP_STORE" json:"type"`                  // 描述文件类型，由苹果 API 中定义，例如：IOS_APP_STORE
	NotBefore     time.Time `gorm:"column:not_before;type:datetime;not null;comment:生效时间" json:"not_before"`                                        // 生效时间
	NotAfter      time.Time `gorm:"column:not_after;type:datetime;not null;comment:失效时间" json:"not_after"`                                          // 失效时间
	Content       []byte    `gorm:"column:content;type:mediumblob binary;not null;comment:描述文件的内容" json:"content"`                                  // 描述文件的内容
	CreatedTime   time.Time `gorm:"column:created_time;type:timestamp;not null;comment:创建时间" json:"created_time"`                                   // 创建时间
	DeletedTime   time.Time `gorm:"column:deleted_time;type:timestamp;comment:删除时间" json:"deleted_time"`                                            // 删除时间
}

// TableName AppleProfile's table name
func (*AppleProfile) TableName() string {
	return TableNameAppleProfile
}
