// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAPIAccount = "t_api_account"

// APIAccount OpenAPI 凭证信息表
type APIAccount struct {
	ID          int        `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                                     // 自增主码
	AppID       int        `gorm:"column:app_id;type:int(11) unsigned;not null;uniqueIndex:idx_app_id_account_id,priority:1;comment:所属应用 ID" json:"app_id"`  // 所属应用 ID
	UserID      int        `gorm:"column:user_id;type:int(11) unsigned;not null;comment:申请人 ID" json:"user_id"`                                              // 申请人 ID
	AccountID   string     `gorm:"column:account_id;type:varchar(64);not null;uniqueIndex:idx_app_id_account_id,priority:2;comment:凭证 ID" json:"account_id"` // 凭证 ID
	IP          StringList `gorm:"column:ip;type:varchar(256);not null;comment:凭证可以放行的 IP、IP 段，*号表示所有，逗号分隔" json:"ip"`                                       // 凭证可以放行的 IP、IP 段，*号表示所有，逗号分隔
	Frequency   int        `gorm:"column:frequency;type:int(11) unsigned;not null;comment:每分钟最高请求次数" json:"frequency"`                                       // 每分钟最高请求次数
	Secret      string     `gorm:"column:secret;type:char(128);not null;comment:密钥" json:"secret"`                                                           // 密钥
	ExpiredTime time.Time  `gorm:"column:expired_time;type:timestamp;not null;comment:失效时间" json:"expired_time"`                                             // 失效时间
	CreatedTime time.Time  `gorm:"column:created_time;type:timestamp;not null;comment:创建时间" json:"created_time"`                                             // 创建时间
	UpdatedTime time.Time  `gorm:"column:updated_time;type:timestamp;comment:创建时间" json:"updated_time"`                                                      // 创建时间
}

// TableName APIAccount's table name
func (*APIAccount) TableName() string {
	return TableNameAPIAccount
}
