// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNotice = "t_notice"

// Notice 公告信息表
type Notice struct {
	ID            int       `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                           // 自增主码
	Content       string    `gorm:"column:content;type:mediumtext;not null;comment:公告内容" json:"content"`                                            // 公告内容
	UserID        int       `gorm:"column:user_id;type:int(11) unsigned;not null;comment:创建人 ID" json:"user_id"`                                    // 创建人 ID
	ExpiredTime   time.Time `gorm:"column:expired_time;type:timestamp;not null;comment:失效时间" json:"expired_time"`                                   // 失效时间
	ActivatedTime time.Time `gorm:"column:activated_time;type:timestamp;not null;comment:生效时间" json:"activated_time"`                               // 生效时间
	CreatedTime   time.Time `gorm:"column:created_time;type:timestamp;not null;index:idx_created_time,priority:1;comment:创建时间" json:"created_time"` // 创建时间
}

// TableName Notice's table name
func (*Notice) TableName() string {
	return TableNameNotice
}
