// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTodo = "t_todo"

// Todo 待办表
type Todo struct {
	ID             int       `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                                 // 自增主码
	AppID          int       `gorm:"column:app_id;type:int(11) unsigned;not null;index:idx_app_id_type,priority:1;comment:所属应用 ID" json:"app_id"`          // 所属应用 ID
	Type           int       `gorm:"column:type;type:tinyint(4) unsigned;not null;index:idx_app_id_type,priority:2;comment:类型，见表 3-4" json:"type"`         // 类型，见表 3-4
	ApplierID      int       `gorm:"column:applier_id;type:int(11) unsigned;not null;index:idx_applier_id,priority:1;comment:申请人 ID" json:"applier_id"`    // 申请人 ID
	ApproverID     int       `gorm:"column:approver_id;type:int(11) unsigned;index:idx_approver_id,priority:1;comment:审批人 ID" json:"approver_id"`          // 审批人 ID
	Candidates     IntList   `gorm:"column:candidates;type:varchar(256);not null;comment:待办可审批的人 ID，英文逗号分隔" json:"candidates"`                             // 待办可审批的人 ID，英文逗号分隔
	ApplyReason    string    `gorm:"column:apply_reason;type:varchar(256);comment:申请理由" json:"apply_reason"`                                               // 申请理由
	ApproveMessage string    `gorm:"column:approve_message;type:varchar(256);comment:审批语" json:"approve_message"`                                          // 审批语
	Information    string    `gorm:"column:information;type:text;comment:审批对象信息" json:"information"`                                                       // 审批对象信息
	Status         int       `gorm:"column:status;type:tinyint(4) unsigned;not null;index:idx_status,priority:1;comment:状态，1=待处理、2=驳回、3=同意" json:"status"` // 状态，1=待处理、2=驳回、3=同意
	CreatedTime    time.Time `gorm:"column:created_time;type:timestamp;index:idx_created_time,priority:1;comment:创建时间" json:"created_time"`                // 创建时间
	FinishedTime   time.Time `gorm:"column:finished_time;type:timestamp;comment:结束时间" json:"finished_time"`                                                // 结束时间
}

// TableName Todo's table name
func (*Todo) TableName() string {
	return TableNameTodo
}
