// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "t_user"

// User 用户信息表
type User struct {
	ID             int       `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                    // 自增主码
	NameEn         string    `gorm:"column:name_en;type:varchar(32);not null;uniqueIndex:uidx_name_en,priority:1;comment:英文名" json:"name_en"` // 英文名
	NameZh         string    `gorm:"column:name_zh;type:varchar(16);not null;comment:中文名" json:"name_zh"`                                     // 中文名
	AvatarFileID   string    `gorm:"column:avatar_file_id;type:char(38);not null;comment:头像文件 ID" json:"avatar_file_id"`                      // 头像文件 ID
	Department     string    `gorm:"column:department;type:varchar(1024);not null;comment:部门组织，以/分隔" json:"department"`                       // 部门组织，以/分隔
	PasswordDigest string    `gorm:"column:password_digest;type:char(32);not null;comment:密码 MD5" json:"password_digest"`                     // 密码 MD5
	PasswordSalt   string    `gorm:"column:password_salt;type:char(128);not null;comment:密码盐值" json:"password_salt"`                          // 密码盐值
	CreatedTime    time.Time `gorm:"column:created_time;type:timestamp;not null;comment:注册时间" json:"created_time"`                            // 注册时间
	UpdatedTime    time.Time `gorm:"column:updated_time;type:timestamp;comment:更新时间" json:"updated_time"`                                     // 更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
