// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserRole = "t_user_role"

// UserRole 用户权限表
type UserRole struct {
	ID     int `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                                                                    // 自增主码
	AppID  int `gorm:"column:app_id;type:int(11) unsigned;uniqueIndex:uidx_app_id_user_id_role,priority:3;comment:所属应用 ID" json:"app_id"`                                       // 所属应用 ID
	UserID int `gorm:"column:user_id;type:int(11) unsigned;not null;uniqueIndex:uidx_app_id_user_id_role,priority:1;index:idx_user_id,priority:1;comment:用户 ID" json:"user_id"` // 用户 ID
	Role   int `gorm:"column:role;type:tinyint(4) unsigned;not null;uniqueIndex:uidx_app_id_user_id_role,priority:2;comment:角色，1=系统运营员、2=应用管理员、3=应用成员、4=可使用签名服务" json:"role"`   // 角色，1=系统运营员、2=应用管理员、3=应用成员、4=可使用签名服务
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
