// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWhqlJob = "t_whql_job"

// WhqlJob WHQL 签名任务表
type WhqlJob struct {
	ID              int       `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                                                                                                                    // 自增主码
	JobID           string    `gorm:"column:job_id;type:char(32);not null;uniqueIndex:uidx_job_id,priority:1;comment:任务 ID" json:"job_id"`                                                                                                     // 任务 ID
	AppID           int       `gorm:"column:app_id;type:int(11) unsigned;not null;index:idx_app_id,priority:1;comment:所属应用 ID" json:"app_id"`                                                                                                  // 所属应用 ID
	UserID          int       `gorm:"column:user_id;type:int(11) unsigned;not null;comment:提交人 ID" json:"user_id"`                                                                                                                             // 提交人 ID
	FileID          string    `gorm:"column:file_id;type:char(38);not null;comment:待签名文件 ID" json:"file_id"`                                                                                                                                   // 待签名文件 ID
	SignedFileID    string    `gorm:"column:signed_file_id;type:char(38);comment:已签名文件 ID" json:"signed_file_id"`                                                                                                                              // 已签名文件 ID
	HlkLogFileID    string    `gorm:"column:hlk_log_file_id;type:char(38);comment:HLK Studio 日志包文件 ID" json:"hlk_log_file_id"`                                                                                                                 // HLK Studio 日志包文件 ID
	HlkxFileID      string    `gorm:"column:hlkx_file_id;type:char(38);comment:HLKX 文件 ID" json:"hlkx_file_id"`                                                                                                                                // HLKX 文件 ID
	HlkxSignJobID   string    `gorm:"column:hlkx_sign_job_id;type:char(38);comment:HLKX 文件签名任务 ID，对应 Windows 任务表中的 ID" json:"hlkx_sign_job_id"`                                                                                                // HLKX 文件签名任务 ID，对应 Windows 任务表中的 ID
	Type            int       `gorm:"column:type;type:tinyint(4) unsigned;not null;comment:类型，1=HLK 兼容性测试+WHQL 签名、2=仅 WHQL 签名" json:"type"`                                                                                                    // 类型，1=HLK 兼容性测试+WHQL 签名、2=仅 WHQL 签名
	Log             string    `gorm:"column:log;type:mediumtext;comment:任务日志" json:"log"`                                                                                                                                                      // 任务日志
	ProductID       string    `gorm:"column:product_id;type:char(17);comment:微软侧的 ID" json:"product_id"`                                                                                                                                       // 微软侧的 ID
	SubmissionID    string    `gorm:"column:submission_id;type:char(19);comment:微软侧的 ID" json:"submission_id"`                                                                                                                                 // 微软侧的 ID
	Source          int       `gorm:"column:source;type:tinyint(4) unsigned;not null;comment:来源，1=页面、2=OpenAPI" json:"source"`                                                                                                                 // 来源，1=页面、2=OpenAPI
	TestSystem      string    `gorm:"column:test_system;type:varchar(32);comment:测试系统" json:"test_system"`                                                                                                                                     // 测试系统
	TestMachineName string    `gorm:"column:test_machine_name;type:char(15);comment:测试机器名" json:"test_machine_name"`                                                                                                                           // 测试机器名
	TestTarget      string    `gorm:"column:test_target;type:varchar(256);comment:测试目标名" json:"test_target"`                                                                                                                                   // 测试目标名
	ServiceName     string    `gorm:"column:service_name;type:varchar(256);comment:服务名" json:"service_name"`                                                                                                                                   // 服务名
	TestConfig      string    `gorm:"column:test_config;type:text;comment:HLK 测试项配置" json:"test_config"`                                                                                                                                       // HLK 测试项配置
	FinishedTime    time.Time `gorm:"column:finished_time;type:timestamp;comment:结束时间" json:"finished_time"`                                                                                                                                   // 结束时间
	FinishTestTime  time.Time `gorm:"column:finish_test_time;type:timestamp;comment:测试结束时间" json:"finish_test_time"`                                                                                                                           // 测试结束时间
	Status          int       `gorm:"column:status;type:tinyint(4) unsigned;not null;index:idx_status,priority:1;comment:状态，1=待HLK测试、2=测试机初始化中、3=测试机初始化完毕，4=启动HLK测试中，5=HLK测试中，6=HLK测试完毕、7=HLKX 文件签名中、8=等待 WHQL认证结果中、9=失败、10=成功" json:"status"` // 状态，1=待HLK测试、2=测试机初始化中、3=测试机初始化完毕，4=启动HLK测试中，5=HLK测试中，6=HLK测试完毕、7=HLKX 文件签名中、8=等待 WHQL认证结果中、9=失败、10=成功
	CreatedTime     time.Time `gorm:"column:created_time;type:timestamp;not null;comment:提交时间" json:"created_time"`                                                                                                                            // 提交时间
	UpdatedTime     time.Time `gorm:"column:updated_time;type:timestamp;comment:更新时间" json:"updated_time"`                                                                                                                                     // 更新时间
}

// TableName WhqlJob's table name
func (*WhqlJob) TableName() string {
	return TableNameWhqlJob
}
