// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWindowsCertificate = "t_windows_certificate"

// WindowsCertificate Windows 证书信息表
type WindowsCertificate struct {
	ID                           int       `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                                       // 自增主码
	CertificateID                string    `gorm:"column:certificate_id;type:char(32);not null;uniqueIndex:uidx_certificate_id,priority:1;comment:唯一标识" json:"certificate_id"` // 唯一标识
	AppID                        int       `gorm:"column:app_id;type:int(11) unsigned;index:idx_app_id,priority:1;comment:所属应用 ID" json:"app_id"`                              // 所属应用 ID
	UserID                       int       `gorm:"column:user_id;type:int(11) unsigned;not null;comment:创建人 ID" json:"user_id"`                                                // 创建人 ID
	Sha1                         string    `gorm:"column:sha1;type:char(40);not null;comment:指纹" json:"sha1"`                                                                  // 指纹
	Type                         int       `gorm:"column:type;type:tinyint(4) unsigned;not null;comment:类型，1=公司EV、2=公司OV、3=个人EV、4=个人OV" json:"type"`                           // 类型，1=公司EV、2=公司OV、3=个人EV、4=个人OV
	IP                           string    `gorm:"column:ip;type:varchar(15);comment:UKEY 所在机器 IP" json:"ip"`                                                                  // UKEY 所在机器 IP
	IsMicrosoftVerifyCertificate Bool      `gorm:"column:is_microsoft_verify_certificate;type:bit(1);comment:是否是微软网站的验证证书" json:"is_microsoft_verify_certificate"`             // 是否是微软网站的验证证书
	Password                     string    `gorm:"column:password;type:varchar(64);not null;comment:密码" json:"password"`                                                       // 密码
	Version                      int       `gorm:"column:version;type:int(11) unsigned;comment:版本号" json:"version"`                                                            // 版本号
	Publisher                    string    `gorm:"column:publisher;type:varchar(1024);comment:颁发者" json:"publisher"`                                                           // 颁发者
	CommonName                   string    `gorm:"column:common_name;type:varchar(64);not null;comment:通用名" json:"common_name"`                                                // 通用名
	Owner                        string    `gorm:"column:owner;type:varchar(1024);comment:所有者" json:"owner"`                                                                   // 所有者
	SignatureAlgorithm           string    `gorm:"column:signature_algorithm;type:varchar(64);comment:签名算法" json:"signature_algorithm"`                                        // 签名算法
	PublicKeyAlgorithm           string    `gorm:"column:public_key_algorithm;type:varchar(64);comment:公钥密码算法" json:"public_key_algorithm"`                                    // 公钥密码算法
	SerialNumber                 string    `gorm:"column:serial_number;type:varchar(1024);comment:序列号" json:"serial_number"`                                                   // 序列号
	NotBefore                    time.Time `gorm:"column:not_before;type:datetime;not null;comment:生效时间" json:"not_before"`                                                    // 生效时间
	NotAfter                     time.Time `gorm:"column:not_after;type:datetime;not null;comment:失效时间" json:"not_after"`                                                      // 失效时间
	AesKeyID                     int       `gorm:"column:aes_key_id;type:int(11) unsigned;comment:证书加密密钥 ID" json:"aes_key_id"`                                                // 证书加密密钥 ID
	Content                      []byte    `gorm:"column:content;type:mediumblob binary;comment:加密了的证书内容" json:"content"`                                                      // 加密了的证书内容
	CreatedTime                  time.Time `gorm:"column:created_time;type:timestamp;not null;comment:创建时间" json:"created_time"`                                               // 创建时间
	DeletedTime                  time.Time `gorm:"column:deleted_time;type:timestamp;comment:删除时间" json:"deleted_time"`                                                        // 删除时间
}

// TableName WindowsCertificate's table name
func (*WindowsCertificate) TableName() string {
	return TableNameWindowsCertificate
}
