// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWindowsCertificateAuthorization = "t_windows_certificate_authorization"

// WindowsCertificateAuthorization 授权应用 EV 证书表
type WindowsCertificateAuthorization struct {
	ID            int       `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                                                               // 自增主码
	AppID         int       `gorm:"column:app_id;type:int(11) unsigned;not null;uniqueIndex:idx_certificate_id_app_id,priority:2;comment:所属应用 ID" json:"app_id"`                        // 所属应用 ID
	UserID        int       `gorm:"column:user_id;type:int(11) unsigned;not null;comment:操作人 ID" json:"user_id"`                                                                        // 操作人 ID
	CertificateID int       `gorm:"column:certificate_id;type:int(11) unsigned;not null;uniqueIndex:idx_certificate_id_app_id,priority:1;comment:Windows 证书表 ID" json:"certificate_id"` // Windows 证书表 ID
	CreatedTime   time.Time `gorm:"column:created_time;type:timestamp;not null;comment:授权时间" json:"created_time"`                                                                       // 授权时间
}

// TableName WindowsCertificateAuthorization's table name
func (*WindowsCertificateAuthorization) TableName() string {
	return TableNameWindowsCertificateAuthorization
}
