// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWindowsSigningJob = "t_windows_signing_job"

// WindowsSigningJob Windows 签名任务表
type WindowsSigningJob struct {
	ID            int       `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:自增主码" json:"id"`                                                                                            // 自增主码
	JobID         string    `gorm:"column:job_id;type:char(38);not null;uniqueIndex:uidx_job_id,priority:1;comment:任务 ID，前 6 为是年月，后面是 UUID" json:"job_id"`                                                           // 任务 ID，前 6 为是年月，后面是 UUID
	Type          int       `gorm:"column:type;type:tinyint(4) unsigned;not null;comment:类型，1=PE 签名、2=微软 Attestation 签名、3=PE+微软 Attestation 签名、4=HLKX 文件签名" json:"type"`                                             // 类型，1=PE 签名、2=微软 Attestation 签名、3=PE+微软 Attestation 签名、4=HLKX 文件签名
	AppID         int       `gorm:"column:app_id;type:int(11) unsigned;index:idx_app_id,priority:1;comment:所属应用 ID" json:"app_id"`                                                                                   // 所属应用 ID
	UserID        int       `gorm:"column:user_id;type:int(11) unsigned;not null;comment:提交人 ID" json:"user_id"`                                                                                                     // 提交人 ID
	CertificateID int       `gorm:"column:certificate_id;type:int(11) unsigned;not null;comment:Windows 证书表 ID" json:"certificate_id"`                                                                               // Windows 证书表 ID
	FileID        string    `gorm:"column:file_id;type:char(38);not null;comment:待签名文件 ID" json:"file_id"`                                                                                                           // 待签名文件 ID
	SignedFileID  string    `gorm:"column:signed_file_id;type:char(38);comment:已签名文件 ID" json:"signed_file_id"`                                                                                                      // 已签名文件 ID
	Log           string    `gorm:"column:log;type:mediumtext;comment:任务日志" json:"log"`                                                                                                                              // 任务日志
	ProductID     string    `gorm:"column:product_id;type:char(17);comment:微软侧的 ID" json:"product_id"`                                                                                                               // 微软侧的 ID
	SubmissionID  string    `gorm:"column:submission_id;type:char(19);comment:微软侧的 ID" json:"submission_id"`                                                                                                         // 微软侧的 ID
	Source        int       `gorm:"column:source;type:tinyint(4) unsigned;not null;comment:来源，1=页面，2=OpenAPI、3=内部" json:"source"`                                                                                    // 来源，1=页面，2=OpenAPI、3=内部
	FinishedTime  time.Time `gorm:"column:finished_time;type:timestamp;comment:结束时间" json:"finished_time"`                                                                                                           // 结束时间
	FinishPeTime  time.Time `gorm:"column:finish_pe_time;type:timestamp;comment:完成 PE 签名时间" json:"finish_pe_time"`                                                                                                   // 完成 PE 签名时间
	Status        int       `gorm:"column:status;type:tinyint(4) unsigned;not null;index:idx_status,priority:1;comment:状态，1=签名中、2=等待 Cab 签名、3=Cab 签名中、4=待 Attestation 签名、5=Attestation 签名中、6=失败、7=成功" json:"status"` // 状态，1=签名中、2=等待 Cab 签名、3=Cab 签名中、4=待 Attestation 签名、5=Attestation 签名中、6=失败、7=成功
	CreatedTime   time.Time `gorm:"column:created_time;type:timestamp;not null;index:idx_created_time,priority:1;comment:提交时间" json:"created_time"`                                                                  // 提交时间
	UpdatedTime   time.Time `gorm:"column:updated_time;type:timestamp;comment:更新时间" json:"updated_time"`                                                                                                             // 更新时间
}

// TableName WindowsSigningJob's table name
func (*WindowsSigningJob) TableName() string {
	return TableNameWindowsSigningJob
}
